### ISSUE TITLE
Add resources to `compute path` answers

### ISSUE THREAD

**Issue by ghost** [vaticle/typedb#2179]
Currently the answer to `compute path` is:
```
>>> compute path from 'V36912' to 'V32920';
id V36912 isa person
id V45208 (lover: id V82112, loved: id V36912) isa love
id V82112 isa cat
id V45264 (lover: id V32920, loved: id V82112) isa love
id V32920 isa dog
```
If I need to know which `person` loves which `cat` and `dog`,
I think It forces me to issue 3 queries separatly each of the `person, cat, dog` like this: 
`match $x id 'V36912';`
`match $x id 'V81112';`
`match $x id 'V32920';` 

One solution would be to give more detailled answers for `compute path` by including resources like this:

```
>>> compute path from 'V36912' to 'V32920';
id V36912 isa person, has identifier 'john'
id V45208 (lover: id V82112, loved: id V36912) isa love
id V82112 isa cat, has identifier 'fluffy_the_cat', has name 'FLUFFY!'
id V45264 (lover: id V32920, loved: id V82112) isa love
id V32920 isa dog, has name 'wooffy'
```

For me this kind of enhanced answers would be more useful in the [python driver](https://github.com/graknlabs/grakn-python),
That could in many use cases save a lot of secondary queries.

python driver response would be example:

```
[
{
'id': 'V36912', 
'isa': 'person',
'resources': [{'identifier': 'john', 'lastname': 'DOE'}]
},
 {
'id': 'V82112', 
'isa': 'cat', 
'resources': [{'identifier': 'fluffy_the_cat', 'name': 'FLUFFY!'}]},
...
]

**Comment by duckofyork** [comment]
An entity may have no attributes (resources) or too many of them. And in most cases it's difficult to figure out which attribute(s) the user wants to see. Therefore, we only show the id and type of an entity.
Cheers.json

**Comment by pouledodue** [comment]
imho, a default of `all` would be better than `none`

**Comment by krishnangovindraj** [comment]
Closing as analytics is not on the roadmap
