### ISSUE TITLE
Query for rules which includes a particular type

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3251]
_This issue was originally posted by @haikalpribadi  on 2018-01-05 17:06_.

e.g. `match $rule concludes person;`, `match grandparent-rule hypothesis $x;`
or `match $rule when contains person;`
Use Cases:
1. Be able to lookup rules once rules no longer have sub links
2. It is also an interesting way to see which types are affected/influenced by rules

**Comment by flyingsilverfin** [comment]
We can't query for rules via `match` anymore, closing
