### ISSUE TITLE
Compute cluster should accept min and max size arguments

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3585]
_This issue was originally posted by @haikalpribadi  on 2018-04-23 18:26_.

This is the current method for collecting result of cluster query 
```
 public ClusterMemberMapReduce(String clusterLabel, @Nullable Long clusterSize); public ClusterSizeMapReduce(String clusterLabel, @Nullable Long clusterSize) ; 
```
 If `clusterSize` is not null, we only want cluster with size = `clusterSize`. We'd like to expand this method so we can set `minClusterSize` and `maxClusterSize`.

**Comment by krishnangovindraj** [comment]
No longer relevant since the component it concerns no longer exists
