### ISSUE TITLE
When returning relation, console returns all role-players

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3745]
_This issue was originally posted by @jmsfltchr  on 2018-05-09 13:44_.

A query such as: 
```
match $r isa relation-link; get;
```
 Returns all of the role-players of the n-ary relation $r 
```
{$r id V4120 (link-source: id V413728, link-dest: id V340024) isa relation-link;}
```

This can be seen as a problem, since we didn't explicitly ask for the roleplayers. Should a relation have many roleplayers, this would create an unreadably long console output.

If we were to change the behaviour to just return the relation $r:
```
{$r id V4120}
```
then we won't have a way to fetch a relation with all the roleplayers attached to it.

So we might want to consider expanding Graql syntax to allow the user to specify whether include all the role-players in the result.

**Comment by flyingsilverfin** [comment]
Closing as it hasn't really been an issue yet. We will re-create and reconsider in the future if the issue becomes prominent
