### ISSUE TITLE
Large Scale Deletion Leading to Timeouts

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3771]
_This issue was originally posted by @haikalpribadi  on 2017-03-15 10:57_.

Another bug report from Antonio:
It often happens that the engine hangs when I try to delete several thousands of entities. For example:

>>> match $x isa interactionMiRNA; aggregate count;
149971
>>> match $x isa interactionMiRNA; limit 15000; delete $x;
>>> commit;
Timeout while contacting engine
`./bin/grakn.sh stop` just stops Cassandra and I have to manually `kill -9` the engine and restart to work again.

**Comment by vmax** [comment]
This should no longer happen as we don't use Cassandra for storage.
