### ISSUE TITLE
Problem handling reflexivity with full substitution

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3784]
_This issue was originally posted by @kasper-piskorski  on 2017-06-09 18:42_.

Example from snb: Rule: 
```
 post($p) -> original-post($p, $p) 
```
 Query: 
```
 orignal-post($x, $y) [$x/a, $y/b] 
```
 Unifier: 
```
 [$p/{$x, $y}] 
```
 The rule is non-applicable in this case, however it is applied and yields a variable mapping duplicate. When propagating the ids to the rule a contradiction is created (via the inverse of the unifier: `[x/p, y/p]`) which is not handled properly.

**Comment by flyingsilverfin** [comment]
This will fail at forward unification in 2.0
