### ISSUE TITLE
Reasoner: Breadth-first db lookups

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3822]
_This issue was originally posted by @kasper-piskorski  on 2018-01-08 15:57_.

Query: 
```
 $Z id 'a'; ($Z, $X) isa db-relation; ($X, $Y) isa rule-expendable-relation; 
```
 So currently the order of the events will be the following: - planner will pick up db-relation as a starting atom - ($Z, $X) isa db-relation;$Z id 'a'; will be checked against the database with a list of results, let’s call each single result delta Now for each value of delta: - the delta result will be passed to the next atom picked by the planner - the rule-expendable-relation atom - database lookup for ($X, $Y) isa rule-expendable-relation; $X id 'delta' will be performed - if lookup succeeds all partial answers will be merged and returned - if there are no answers/all answers were returned, a rule will be applied to ($X, $Y) isa rule-expendable-relation; $X id 'delta' What could be done instead is: - fetch the db results of the full query and cache partial queries - follow the procedure above to get rule answers The difference is that the first procedure goes depth-first for each delta so a branch has to be exhaustively depleted before moving to next branch (different delta value). Basically, we could go breadth-first in terms of db lookups.

**Comment by krishnangovindraj** [comment]
Closing since the new reasoner does something similar.
