### ISSUE TITLE
Removing a role-player can still fail at commit

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3840]
_This issue was originally posted by @haikalpribadi  on 2018-03-06 12:17_.

Where `dunstan isa dog` who is allowed to `chase`, but not to be `chased`: 
```
 Relationship rel = chases.addRelationship(); rel.addRolePlayer(chaser, dunstan); rel.addRolePlayer(chased, dunstan).removeRolePlayer(chased, dunstan); tx.commit(); 
```
 
```
 The type [dog] of role player [V1591] is not allowed to play Role [chased] 
```
 Running `rel.allRolePlayers()` correctly reports that the `dunstan` is not playing `chased`. It seems to be a validation issue. It's likely related to caching of role-players.

**Comment by flyingsilverfin** [comment]
not reproducible in 2.0
