### ISSUE TITLE
Flights dataset: slow queries

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3937]
_This issue was originally posted by @kasper-piskorski  on 2018-05-28 15:50_.

Example slow queries: NB: implicit relations are used because of Bug #20143. Which airlines can i fly between Poland and UK? 
```
 match
$a isa airport;
$a2 isa airport;
($a, $ac) isa @has-country; $ac val "Poland"; 
($a2, $a2c) isa @has-country; $a2c val "United Kingdom"; 
($a, $a2, $line) isa route;
 $line isa airline; $line has name $n;
get $n; 
```
Takes 20-25 s. Half if we don't ask for airline name. Which countries can i fly to from London with Ryanair? 
```
match
$a isa airport;
$a2 isa airport;
($a, $ac) isa @has-city;$ac val "London";
($a, $a2, $line) isa route;
$line isa airline has name "Ryanair"; 
$a2 isa airport has city $c; 
get $c; 
```
 Takes more > 10 s.

**Comment by krishnangovindraj** [comment]
Closing as we can't find the dataset and it's likely too old to reproduce.

**Comment by haikalpribadi** [comment]
This issue from 5 years ago is no longer valid in TypeDB 2.14+.
