### ISSUE TITLE
Graql: Query Builder needs to take in Graql concepts

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3953]
_This issue was originally posted by @jmsfltchr  on 2018-06-05 15:51_.

For example, right now isa() only accepts String or VarPattern. So, right now we have to do: 
```
 QueryBuilder qb = this.tx.graql(); query = qb.insert(var("x").isa(this.strategy.getType().getLabel().getValue()); 
```
 Where of course 
```
this.strategy.getType()
```
 returns a Type. We want to do: 
```
 QueryBuilder qb = this.tx.graql(); query = qb.insert(var("x").isa(this.strategy.getType()) 
```

**Comment by flyingsilverfin** [comment]
We shouldn't make `typeql-lang-java` depend on `typedb-client-java` so this should not be implemented
