### ISSUE TITLE
compute count; incorrect

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3962]
_This issue was originally posted by @jmsfltchr  on 2018-06-12 12:47_.

I found this: 
```
>>> compute count; 
285 
>>> match $x; aggregate count; 
538 
```
 Compute count seems to be incorrect here. Unless I misunderstand something, the latter should return 38 more than the former, since it includes the schema concepts. Checking to see how many concepts we have of each type: 
```
>>> match $x isa person; aggregate count; 
205 
>>> match $x isa occupation; aggregate count; 
200 
>>> match $x isa employment; aggregate count;
95 
```
 205+200+95 = 500, which agrees with my code. So, aggregate count is correct, compute count is not. This is reproducible on my running Grakn instance, using my current version of the benchmarking system. I'll create a commit specifically to reproduce this.

**Comment by flyingsilverfin** [comment]
compute count is no longer supported in 2.x
