### ISSUE TITLE
Inferring roleplayer not working pt II

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4017]
_This issue was originally posted by @kasper-piskorski  on 2018-07-01 13:26_.

For some reason I couldn't get the roleplayer below to be inferred. Replacing 
```
when
```
 with 
```
match
```
 and 
```
when
```
 with 
```
insert
```
 correctly inserted the roleplayer connection. 
```
link-bill-payment-with-platform sub rule, 
when { 
$c isa customer; $p isa platform; 
$bp(payer: $c) isa bill-payment, has event-date $e; 
$i(user: $c, host: $p) isa customer-interaction, has log-on-time $l1, has log-off-time $l2; 
$l1 <= $e; $e <= $l2; 
} then { 
$bp(payment-platform: $p); }; 
```

**Comment by flyingsilverfin** [comment]
we no longer support extending relations with new role players in 2.0
