### ISSUE TITLE
Core: Replace the term "BaseType" with "Class"

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4140]
_This issue was originally posted by @haikalpribadi  on 2018-07-30 19:20_.

**Comment by marco-scoppetta** [comment]
@haikalpribadi is this still needed?

**Comment by haikalpribadi** [comment]
Yes, @marco-scoppetta, I still want to do this when I get to refactor Concept Types.

**Comment by flyingsilverfin** [comment]
No longer applicable
