### ISSUE TITLE
Graql: Mismatch in count of relationship instances

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4218]
_This issue was originally posted by @tomassabat  on 2018-08-15 13:42_.

The following answer to the query is wrong: match $x isa PPI_ASSOCIATION; aggregate count; 151782 There were at least 540k instances of PPI_ASSOCIATION inserted. Dist is zipped in Datasets folder as: tomas-dataset-biomed-bugs Keyspace is "disease_networks" Migrator files attached. (you don't have to migrate reactome as the bug appeared before importing reactome) The file "PPIs(2).csv" is in the datasets folder as it was too big to add here.

**Comment by flyingsilverfin** [comment]
Closing, outdated and non-reproducible
