### ISSUE TITLE
Boot-up analytics (with first query) during server boot-up

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4310]
_This issue was originally posted by @haikalpribadi  on 2018-09-07 01:36_.

As it stands right now, when we do a Graql `compute` query for the first time, there are lots of _"initialisation task"_ related to HadoopGraph and Spark that takes time for the first query. We should move these initialisation tasks to the bootup stage of the database, in which the time can be more tolerable. Then by the time a `compute` query is performed, it can be much faster.

**Comment by marco-scoppetta** [comment]
@haikalpribadi do you remember what this issue means, or we can close it?

**Comment by haikalpribadi** [comment]
Yes, I still remember what this issue means. And I think so does @lolski who can help us implement it. I will update the issue description now.

**Comment by flyingsilverfin** [comment]
Analytics has been removed in 2.0, will be brought back differently in the future
