### ISSUE TITLE
Compute centrality finishes with RESOURCE_EXHAUSTED

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4311]
_This issue was originally posted by @tomassabat  on 2018-09-07 13:37_.

**Description:** Compute centrality finishes with Resource exhausted. **Grakn Version:** 1.4.0-snapshot **Reproducible Steps:** 
```
 unzip grakn-core-1.4.0-SNAPSHOT [biograkn].zip (from DATASETS in Dropbox) 
./grakn server start graql console -k 'disease_networks'
 compute centrality using degree; 
```
 **Actual Results:** 
```
RESOURCE_EXHAUSTED: io.grpc.netty.NettyClientTransport$3: Frame size 6149527 exceeds maximum: 4194304. 
```
 **Expected Results:** Should finish returning some numbers.

**Comment by flyingsilverfin** [comment]
Compute has been removed for the time being in 2.0, and will look different in the future
