### ISSUE TITLE
Optimise web services repositories and hostings

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4313]
_This issue was originally posted by @haikalpribadi  on 2018-09-08 16:31_.

Why: We have quite a few web services at this point, such as Grakn's website (grakn.ai), docs (dev.grakn.ai), discuss (discuss.grakn.ai), slack signup (grakn.ai/slack), CMS (cms.grakn.ai) and so on. It's getting hard to manage and them, especially as they continue to grow. Right now there's repo in GitHub and Heroku for Grakn's website and docs, and both are hosted on Heroku. Discuss and CMS is hosted on Digital Ocean.
How: We need to migrate all projects' source code to GitHub, and just have one repository each. We also need to migrate their hosting to all be on one platform, such Heroku.

**Comment by krishnangovindraj** [comment]
This has since been. Closing.
