### ISSUE TITLE
Global schema for tests, benchmarking and docs

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4320]
_This issue was originally posted by @jmsfltchr  on 2018-09-11 11:30_.

Write a schema with as many examples as possible that are required for tests. Ideally this should work towards a societal model that can be used for tests and benchmarking. Also aim to demonstrate inferred relationships, roleplayers, attributes and entities to be used to test workbase.

**Comment by krishnangovindraj** [comment]
We've reached a neat point with separate schemas
