### ISSUE TITLE
Supplying an id but match query still slow

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4335]
_This issue was originally posted by @jmsfltchr  on 2018-09-17 14:21_.

**Description:** Making a short query where an id is given generally ought to be very fast. Just loading genealogy and making a basic query I find it to be quite slow. This could be because rules are being hit. **Grakn Version:** 1.4 **Reproducible Steps:** Load genealogy dataset This first query returns in a few seconds: 
```
match $x id V94432; $x($y) isa parentship; limit 3; get; 
{$x id V94432 (parent: id V98552, child: id V98424) isa parentship; $y id V98424 isa person;} 
{$y id V98552 isa person; $x id V94432 (parent: id V98552, child: id V98424) isa parentship;} 
```
 This second query takes way longer to return: 
```
match $x id V94432; $x($y); limit 3; get; 
{$x id V94432 (parent: id V98552, child: id V98424) isa parentship; $y id V98424 isa person;} 
{$y id V98552 isa person; $x id V94432 (parent: id V98552, child: id V98424) isa parentship;} 
```
 **Actual Results:** Queries take different amounts of time to execute **Expected Results:** Queries should both take the same time, since when we know a concept's ID, we also know it's type, so the first query doesn't supply any additional information compared to the first.

**Comment by flyingsilverfin** [comment]
Not an issue anymore!
