### ISSUE TITLE
Attach univocal explanation to inferred concepts

### ISSUE THREAD

**Issue by marco-scoppetta** [vaticle/typedb#4398]
Make pattern attached to explanation to be univocal so that a specific inferred concept is retrievable also from a different transaction.

E.g. on an inferred `marriage` relationship, instead of `$x isa marriage` as a pattern, we would need
`$r (spouse1:$x, spouse2:$y) isa marriage; $x id 1234; $y 4567; get $r;`

This is strongly needed for Workbase, so that we can show explanation for inferred concepts

**Comment by Irtazaraza** [comment]
@kasper-piskorski, Do you think this is possible in 1.5?

**Comment by sorsaffari** [comment]
@kasper-piskorski do you think we can prioritise this for the next release? It's blocking https://github.com/graknlabs/workbase/issues/43

**Comment by flyingsilverfin** [comment]
We can't exactly return the same inference across transactions now, but we do return all explanations in 2.0 which should alleviate this issue. Plus workbase now runs in 1 read transaction
