### ISSUE TITLE
In CircleCI, Grakn needs to be started with 'nohup ./grakn server start'

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#4526]
CircleCI runs each command as subprocesses. This introduces an issue for commands which starts a background process such as `grakn server start`. When `grakn server start` has just started Grakn and Storage and terminates, the OS thinks it will also need to kill Grakn and Storage as they are its child processes. 

The current workaround is by using `nohup`, ie., `nohup ./grakn server start` which tells the OS not to kill any child process even when the parent command has finished.

**Comment by vmax** [comment]
@lolski could you elaborate on what needs to be done here and whether `nohup` approach is fine for us to apply?

**Comment by lolski** [comment]
Ideally we should not use `nohup`. We still need to investigate why this is even an issue on CirclecI (and not on shells on our computer). Let's not priorities this issue now, I think it shouldn't be marked as 1.5.

**Comment by vmax** [comment]
Given Grakn is now a foreground process and is started via `./grakn server` or managed via systemD, this issue is no longer relevant.
