### ISSUE TITLE
Add MultiAnswer state to handle cases with multiple unifiers

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#4549]
For cases when we have multiple answers being permutations of each other it might be beneficial to introduce a MultiAnswer state dealing with the permutations instead of progressing in the standard way.

Currently all states use `Unifier`s with the following logic applied when matching rules with multiple unifiers:
```
getApplicableRules(atom)
                .flatMap(r -> r.getMultiUnifier(atom).stream().map(unifier -> new Pair<>(r, unifier)))
                .sorted(Comparator.comparing(rt -> -rt.getKey().resolutionPriority()));
```
hence decomposing the multiunifier and creating separate states for each. Instead we can adapt the states to handle multiunifier and avoid redundant rule operations.

**Comment by flyingsilverfin** [comment]
Multipl eunifiers are handled differently in Grakn 2.0
