### ISSUE TITLE
Allow disjunctions in rule bodies

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#4561]
Disjunctions can be written int DNF and hence we can decompose a disjunctive rule into a set of conjunctive ones.

**Comment by flyingsilverfin** [comment]
In 2.x, we could now handle this as a "nice-to-have" directly in a rule without too much difficulty.

**Comment by mathieuisabel** [comment]
FYI I did encounter that as a limitation today. i.e. I was creating a rule that matched specific software version to create a inferred relation for deprecation. i.e.

when {
        $os isa operating-system, has name $os-name, has major-version $os-major-version, has software-edition $os-edition;
        $osi isa operating-system-instance, has host-name $osi-name;
        $si (software: $os, instance: $osi) isa software-instantiation;
        {$os-major-version contains "x";} or {$os-major-version contains "y";};
    }
    then {
         (software: $os, instance: $osi) isa deprecated-software-instantiation;
    };

The workaround being I would need to create a rule per specific software version to deprecate. Depending on the domain that can be fine but I can see other situations where that would be problematic.

**Comment by mathieuisabel** [comment]
FYI For the use case I had posted above, I went down another route to workaround that through a different schema design. 

I did face this issue in another use case and in that particular situation, I worked around that using a regex that would handle the OR logic. i.e.

$de-name like "(^.*[Pp]atient[Aa]ddress.*$|^.*[Cc]laimant[Aa]ddress.*$)(.*)";

**Comment by flyingsilverfin** [comment]
We are planning on implementing disjunctions in rules sooner rathere than later now @mathieuisabel !

**Comment by krishnangovindraj** [comment]
Done in #6677
