### ISSUE TITLE
Graql: Unexpected additional owners found when querying for attribute type owners

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#4562]
Using the attached schema, querying for types having an attribute gives unexpected results.
```
>>> match $x has job-title; get;
{$x label employment sub affiliation;}
{$x label organisation sub entity;}
{$x label company sub organisation;}
{$x label person sub entity;}
```
Only `employment` should have a `job-title`. But `job-title` subs `name`. The additional results match those received as follows:
```
 >>> match $x has name; get;
{$x label organisation sub entity;}
{$x label company sub organisation;}
{$x label person sub entity;}
```
[schema.txt](https://codetreeusercontent.s3.amazonaws.com/uploads/32b363d6-a5ed-48db-a8fa-9f9c267f1e71/schema.txt)

**Comment by flyingsilverfin** [comment]
No longer reproducible in 2.x
