### ISSUE TITLE
For benchmark, make the Zipkin host / port configurable

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#4592]
In grakn.properties, add the following configurations:
```
benchmark.host = "localhost"
benchmark.port =  9411
```

In https://github.com/graknlabs/benchmark: `ServerTracingInstrumentation. initInstrumentation` needs to take `host` and `port` as parameters
In `client-java` (benchmark distribution), needs  to take`host` and `port` parameters

**Comment by flyingsilverfin** [comment]
We no longer use zipkin for benchmarking
