### ISSUE TITLE
Revamp explanations

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#4605]
The grpc explanations are not in sync with the code, related issues:
- grpc explanation tests are commented out, bring them back,
- thorough docs are needed as explanations tend to confuse people (#3157)
- <del> make Explanation object to store `Pattern` rather than `ReasonerQuery` (#4197), 
- <del> Answer.explanations() should return a stream of Explanation objects (#4545),
- <del> make sure explanations are available via python client (#3897).

**Comment by flyingsilverfin** [comment]
https://github.com/graknlabs/client-python/pull/75 fixes one of these points

**Comment by flyingsilverfin** [comment]
We've superceded the previous explanations with new style explanations in Grakn 2.0
