### ISSUE TITLE
the returned value of attrType.dataType() (in Concept API) varies depending on the client

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb#4733]
To my understanding what is returned by calling dataType() on an AttributeType should be consistent across different clients and in accordance with datatypes allowed for attributes in Grakn, that is string, long, double, boolean and date

At the moment, running the aforementioned method on an AttributeType with datatype of `string` returns as follows:
- Client Java: `java.lang.String`
- Client Python: `DataType.String`
- Client Node.js: `string`

**Comment by sorsaffari** [comment]
@marco-scoppetta `attribute.dataType()` to return `"string" | "long" | "double" | "boolean" | "date"`

**Comment by flyingsilverfin** [comment]
This is now consistent in 2.0
