### ISSUE TITLE
Database schema introspection query

### ISSUE THREAD

**Issue by umaxfun** [vaticle/typedb#4769]
It would be very useful to have a mechanism of the database introspection.
I see it similar to SQL's `show create table`.

You define a schema using any tool you want:
```
define 
 company sub entity has name plays owner;
 asset sub entity has name plays property;
 ownership sub relationship relates owner property;
```

then you may issue a query and see DML which should be able recreate all entities, relationships, rules etc. in the target keyspace:

```
> show schema;
define 
 company sub entity has name plays owner;
 asset sub entity has name plays property;
 ownership sub relationship relates owner property;
```

**Comment by flyingsilverfin** [comment]
Implement in Grakn 2.0 - available via clients or console.

In console do:
```
> database schema <database name>
```
