### ISSUE TITLE
Compute path should accept key instead of (just) id

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb#4879]
At the moment to compute the shortest path between to instances, we need to pass the `id`s of the two instances, like so:

```
compute path from V446496, to V229424;
```

However, as `id` is not expected to be a first-class citizen property of a concept, no Graql query should depend on it. Therefore, the compute path query should require another property of an instance that uniqly identifies it, i.e. `key`.

Given that we want to find the shortest path between the `person` instance with `email` (key) of `"instance1@email.com"` and the `car` instance with `model` (key) of `"X224J"`, we'd write the query that looks along the lines of:

```
compute path from person "instance1@email.com", to car "X224J";
```

(should the attributes `email` and `model`, which are the keys that identifiy the two instances, be included in the query?)

**Comment by krishnangovindraj** [comment]
Closing as we don't have analytics since Grakn/TypeDB 2.0
