### ISSUE TITLE
Improve Graql Statements to be "strong typing"

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb#4899]
We will refine the Graql Statement data structure to be "strong typing", by making `Graql.var(...)` return a `StatementBuilder` which implements all the builder interfaces. From there the user will have to continue calling the builder methods which will create a specific type of `Statement` in which a Graql query will expect.

**Comment by flyingsilverfin** [comment]
In Graql 2.0, we indeed a have a structure similar to this, starting with `UnboundVariable` instead of `Statement`
