### ISSUE TITLE
client-java does not set a client-side timeout, and will stall forever if the network gets interrupted

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#4940]
**Grakn version**:
1.5

**Reproducible step**:
1. Start grakn: `grakn server start`
2. Run the following queries using client-java:
```
try (GraknClient.Session session = new GraknClient("localhost:48555").session("grakn")) {
        while (true) {
                GraknClient.Transaction tx = session.transaction(Transaction.Type.WRITE);
                tx.execute(Graql.match(var("x").sub("thing")).get());
                System.out.println("query");
                tx.commit();
        }
}
```
3. Pause grakn in the middle: `kill -STOP <grakn process id>`
4. Observe that the queries will stall and never times out

**TODO**
1. The client should be able to set a timeout when instantiating the client. We need to set a default, eg., 15 seconds.
```
client1 = new GraknClient(DEFAULT_URI, 20) // timeout set to 20 seconds
client2 = new GraknClient(DEFAULT_URI) // timeout set to the default timeout, eg., 15 seconds
```
2. The provided timeout value should be used to set the deadline of GRPC requests.

**Comment by krishnangovindraj** [comment]
The server now has a default timeout, clients have a timeout option as well.
