### ISSUE TITLE
performing >, >=, < and <= operators on the value of a `double` requires a decimal number

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb#5014]
Related feature: https://github.com/graknlabs/grakn/issues/5124
## Description

performing `>`, `>=`, `<` and `<=` operators on the value of a `double` attribute requires the value to be a decimal.

## Environment

1. OS (where Grakn server runs): Mac OS 10.14.2
2. Grakn version (and platform): Grakn Core 1.5 SNAPSHOT
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. `./grakn console -k test`
2. `test> define score sub attribute, datatype double;`
3. `test> commit`
4. `test> insert $x isa score; $x 1.1;`
5. `test> match $x isa score; $x > 1; get;`

## Expected Output

`{$x 1.1 isa score;}`

## Actual Output

nothin`
 
## Additional information
the following queries behave as expected:
- `match $x isa score; $x > 1.0; get;`
- `insert $x isa score; $x 1;`
- `match $x isa score; $x 1; get;`

**Comment by kasper-piskorski** [comment]
Not sure if that's a bug. As far as I know we don't do implicit number conversions any more so this would be the expected behaviour. @sorsaffari @haikalpribadi

**Comment by haikalpribadi** [comment]
It's not a bug, but it s definitely a limitation that we need to resolve @kasper-piskorski. I will work on this in 1.6, @sorsaffari.

**Comment by krishnangovindraj** [comment]
This has since been fixed. Tested in 2.14.3
