### ISSUE TITLE
Semantically invalid attribute queries recognised as mutually subsuming each other

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#5034]
## Description

Dataset: resourceAttachment.gql

Queries:
```
Q1 := genericEntity($r1), genericEntity($x), $x has reattachable-resource-string $r1
```

and
```
Q2 := genericEntity($x), $x has reattachable-resource-string $r1
```

are recognised as mutually subsuming each other, whereas Q1 is semantically invalid -
$r1 is of type `reattachable-resource-string`.

## Expected Output

! Q1 subsumes Q2 
! Q2 subsume Q1.

## Actual Output

Q1 subsumes Q2 
Q2 subsumes Q1

**Comment by flyingsilverfin** [comment]
We no longer have a subsumption cache, so this is irrelevant
