### ISSUE TITLE
Inconsistent value predicate semantics

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#5065]
Two insert queries:

```
insert $x isa amount; $x 1000.0;
```

and
```
insert $x isa amount; $x == 1000.0;
```

Have different outcomes. The second one fails. 

As we treat `$x 1000.0;` and ` $x == 1000.0;` as equivalent (`==` is optional), this equivalence is violated during inserts.

**Comment by krishnangovindraj** [comment]
Tested on 2.11.0; Both succeed
