### ISSUE TITLE
undefining a subtype with instances looks like it was successful

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5080]
## Description

Trying to `undefine` a type that has instances doesn't throw an error when:
- That type is has a supertype
- That supertype isn't used as `sub <supertype>` in the `undefine` statement, and the base Type is used instead

## Environment

1. OS (where Grakn server runs): Mac OS 10.14.3
2. Grakn version (and platform): Grakn Core 1.5
3. Grakn client: console
4. Other environment details: --

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load the schema and data below
2. Try to `undefine company sub organisation;` and see an error (correct behaviour)
3. Try to `undefine company sub entity;` and see `{}`, and `commit` seemingly with success (incorrect behaviour)
4. See that the `company` instance still exists `match $x isa thing; get;`
5. See that the `company` Type still exists `match $x sub thing; get;`
6. Conclude that `undefine company sub entity;` had no effect, but didn't throw an error

```
define

name sub attribute,
  datatype string;

organisation sub entity;

company sub organisation, 
  plays employer,
  has name;

person sub entity,
  has name,
  plays employee;

employment sub relation,
  relates employee,
  relates employer;

insert $x isa company, has name "Grakn"; $p isa person, has name "James"; (employer:$x, employee:$p) isa employment;
```
## Expected Output

Expected to receive the error: 
```
example> undefine company sub entity;
Error: INVALID_ARGUMENT: grakn.core.server.exception.TransactionException-Type [company] cannot be deleted as it still has incoming edges. Please check server logs for the stack trace.
All uncommitted data is cleared
example>
```

## Actual Output
```
example> undefine company sub entity;
{}
example> commit
example>
```

## Additional information
--

**Comment by krishnangovindraj** [comment]
This has since been fixed.

Tested on 2.11.0
```
## Running> Undefine query:
undefine
company sub entity;

## Error> [TYW04] Invalid Type Write: The type 'company' has instances, and cannot be deleted.
```
