### ISSUE TITLE
Rethink Relation-RelationImpl-RelationStructure-ReifiedRelation-EdgeRelation hierarchy

### ISSUE THREAD

**Issue by marco-scoppetta** [vaticle/typedb#5122]
## Problem to Solve
The current structure and hierarchy of the following classes is quite confusing to work with:

-Relation
-RelationImpl
-RelationStructure
-ReifiedRelation
-EdgeRelation

## Proposed Solution
 Rethink the relation between these classes and make code more clean and more maintainable, specially when working with caches and wrappers (`RelationImpl` wraps `RelationStructure`)

**Comment by flyingsilverfin** [comment]
Completely refactored and differently implemented in 2.0
