### ISSUE TITLE
Docker image startup on OpenShift (Minishift)

### ISSUE THREAD

**Issue by Eldarrin** [vaticle/typedb#5179]
## Description

When installing from the base Docker image onto an OpenShift cluster in test mode (no volumes attached); in this case a Minishift test environment. The server fails to start declaring that it cannot find storage. If you then RSH into the pod directly and run ./grakn server start it declares the storage is running and starts the server. 

## Environment

1. OS (where Grakn server runs): Docker / Minishift v1.33.0+ba29431
2. Grakn version (and platform): 1.5.2
3. Grakn client: n/a
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install Minishift
2. Log into OpenShift web console, then "My Project"
3. Click "Add to Project", select Deploy Image, Use "Image Name"
4. When deployed, spin 1 pod up
5. Once up, click on "grakn", then "View Log"

## Expected Output

Server Start and log display correct startup

## Actual Output

Server fails to start due to storage unavailable
 
## Additional information

Go to command line and using command line tools (oc), you can view the pods. 1 will have the name of grakn-n-xxxxx. use oc rsh grakn-n-xxxxx which will ssh you into the pod.
run /grakn-core-all-linux/grakn server start
The server starts as it should, stating the storage is already running. This leads me to believe that the server startup is timing out before the storage has completed initialising.

This means that although it is now running on OpenShift the logs are not viewable making things a lot more guess-work.

Let me know if you want any more info.

Cheers, Andy

**Comment by vmax** [comment]
We've verified that newest version of 2.0 doesn't have any issues booting up on OpenShift.
