### ISSUE TITLE
Change implicit Relation Type added with `match-insert` attributes

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5181]
## Description
We expect to be able to "elevate" the type of an attribute to a supertype on insert. For example, if we have defined `name` and `first-name sub name`, we want to do the following:

`match $x isa person, has first-name $a; insert $y isa person, has name $a`. This is re-attaching a first-name concrete instance as a name. We should store this with an `@has-name` implicit relation rather than `@has-first-name` because that's the user's intent.

## Environment
Grakn Core 1.5.3

## Reproducible Steps
1. `define person sub entity; name sub attribute datatype string; first-name sub name, datatype string;`
2. `insert $x isa person, has first-name "John";`
3. `match $x isa person, has first-name $a; insert $y isa person, has name $a`

## Expected Output
4. `match $z isa person, has first-name $a; get;` -- this should return only 1 person (the original John) rather than two, because the `match-insert` didn't store first-names, but names.

## Actual Output
We get two peopel back, rather than 1
 
## Additional information
Related to #5145

**Comment by krishnangovindraj** [comment]
Closing since it is no longer applicable.
The semantics have since changed. This scenario is now illegal since super-attributes must now be abstract, and you cannot change the type of an attribute in a match-insert
