### ISSUE TITLE
Different execution time between query and rule with Python API

### ISSUE THREAD

**Issue by andreadegiorgi91** [vaticle/typedb#5227]
```python
abc =  "" # myquery
with GraknClient(uri="localhost:48555") as client:
  with client.session(keyspace="my_keyspace") as session:
    with session.transaction().read() as read_transaction:
      answer_iterator = read_transaction.query(abc)
      for answer in answer_iterator:
        concept_x = answer.get("x")
        attributeTypes = concept_x.attributes()
        for attribute in attributeTypes:
          attr_name = attribute.type().label()
          attr_value = attribute.value()
          print(attr_name + ": " + str(attr_value))
```

I noticed a significant change in the time taken to execute the lines of code from line 7 to line 13 when the value of the variable abc on line 6 is a simple query or a rule. In both cases there were 11 iterations and it emerged that:
- For a simple query the time taken is about 1.5 seconds
- For a rule the time taken is about 5 seconds.

How is such a difference possible?
PS. If it should be necessary, I can upload the relevant portion of the Knowledge Base, the query and the rule used to github.

**Comment by kasper-piskorski** [comment]
In general the execution and processing is slightly different for queries with and without reasoning so differences in execution times can arise. If you could post how the query/rule looks like we could have a more detailed look.

**Comment by andreadegiorgi91** [comment]
RULE

purchasable-products sub relation,
  relates potentialBuyer,
  relates canEat;

products-that-a-person-can-buy sub rule,
  when {
	$prod1 isa product;
	$p1 isa person;
	not{
		(suffer-of: $p1, suffered-by: $int1) isa person-intollerance;
		(generated-by: $int1, generates: $ing1) isa ingredient-intollerance;
		(contained: $ing1, includes: $prod1) isa product-ingredient;
	};
  }, then {
		(potentialBuyer: $p1, canEat: $prod1) isa purchasable-products;
  };

Simple query
abc = "match $x isa product; get;"  

Query with rule
abc = 'match $pe isa person; $x isa product; $r (potentialBuyer: $pe, canEat: $x) isa purchasable-products; $pe has username "andrew" ; get;'

**Comment by krishnangovindraj** [comment]
Not informative; Likely no longer an issue
