### ISSUE TITLE
Explanation answer does not contain correct concept

### ISSUE THREAD

**Issue by Irtazaraza** [vaticle/typedb#5268]
## Description
The answers of the explanation of an inferred concept does not contain the correct concepts which led to the inference

## Environment

1. OS (where Grakn server runs):Mac OS 10
2. Grakn version (and platform): Grakn 1.5.4
3. Grakn client: client-nodejs

## Reproducible Steps

Steps to create the smallest reproducible scenario:
```
define

person sub entity,
	plays child,
	plays parent;

fatherhood sub relation,
	relates child,
	relates parent;

parentship sub relation,
	relates child,
	relates parent;

rule1 sub rule,
when {
	(child: $x, parent: $y) isa fatherhood;
}, then {
	(child: $x, parent: $y) isa parentship;
};

insert $x isa person; $y isa person; $r (child: $x, parent: $y) isa fatherhood;
```
1) load above schema
2) Query: `match $x isa parentship; get;`
3) Get Explanation of the parentship concept

## Expected Output
The answers of the explanation should contain the fathehood concept

## Actual Output
answers is empty
 
## Additional information
N/A

**Comment by krishnangovindraj** [comment]
Has been since fixed; Tested on 2.14.3
