### ISSUE TITLE
Improve the UI/UX of the clean keyspace command

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#5316]
_This comment was originally posted by @lolski on 2018-05-16 12:10:04+02:00_.

We have two methods of cleaning Grakn keyspaces.

1. Clean all keyspaces: `grakn server clean`.
This command deletes every keyspaces by deleting the data directory: `rm -rf $GRAKN_HOME/db`

2. Clean a single keyspace: `graql console -k $KEYSPACE` followed by `clean` and `confirm`.
This command deletes every the data from a single keyspace (the one you're connected to)

Both commands are for cleaning up keyspaces yet they both:
1. Have a completely different user experience (one is executed from `grakn`, the other from `graql`)
2. Uses a completely different functions

We should simplify it by having only one single command `clean `. 
The command should perform deletion via graql query, not via `rm -rf`, ie., `match $x isa thing; delete $x;` on the said keyspace.

**Comment by krishnangovindraj** [comment]
Database deletions are now done through the clients
