### ISSUE TITLE
Undefining a Type can corrupt its super Type

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5322]
## Description

Undefining a Type hierarchy doesn't work if a subtype is undefined by referencing a MetaType

## Environment

1. OS (where Grakn server runs): macOS 10.14.5
2. Grakn version (and platform): Grakn Core 1.5.6
3. Grakn client: Console

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Define a Type hierarchy:
```
define
organisation sub entity;
company sub organisation;
```

Now trying to undefine organisation throws an error since it has a subtype:
```
Error: INVALID_ARGUMENT: grakn.core.server.exception.TransactionException-Type [organisation] cannot be deleted as it still has incoming edges. Please check server logs for the stack trace.
All uncommitted data is cleared
```
This is as expected, although the error could be more clear.

We should be able to undefine organisation if we undefine company first:

```
undefine company sub entity;
```

Now we should be able to undefine organisation with
```
undefine organisation sub entity;
```
## Expected Output

`undefine organisation sub entity;` should succeed

## Actual Output

```
> undefine organisation sub entity;
Error: INVALID_ARGUMENT: grakn.core.server.exception.TransactionException-Type [organisation] cannot be deleted as it still has incoming edges. Please check server logs for the stack trace.
All uncommitted data is cleared
```
 
## Additional information

I have confirmed that the same is true for undefining attribute hierarchies, and relation hierarchies.

It is possible to undefine organisation in this case, but the undefine step for company needs to include `sub organisation` not `sub entity`:

```
define
organisation sub entity;
company sub organisation;
```

Then
```
undefine company sub organisation;
```
```
undefine organisation sub entity;
```

I have confirmed that this is also true for Relations and Attributes.

**Comment by krishnangovindraj** [comment]
This has since been fixed. Tested on 2.11.0
