### ISSUE TITLE
Control over prioritization of `match ... contains "..."`

### ISSUE THREAD

**Issue by johannesmutter** [vaticle/typedb#5357]
## Problem to Solve

The search results of queries with `contains` keyword are not prioritized very effectivly:

In most use cases results should be prioritized that **start** with the characters defined in `contains`  over those that just contain it multiple times or just once somewhere:

(1) **A** m **a** zon vs (2) R **a** spberry

## Current Workaround

One way to solve this is by extending the limit and sort afterwards, but this slows down the retrieval.

Another workaround could be regex. 
([some more info regex in the docs would be great!](https://dev.grakn.ai/docs/query/match-clause#with-a-given-regex)): 

`match $thing has name $name; $name like "((a|A)[^\s]*)\b"; get $name; limit 10;`

## Proposed Solution

Better prioritization in the get part of the query 

or a new keyword like:
`match $x ... startsWith "A"`

or more details in documentation on how to apply regex

Thank you!

**Comment by flyingsilverfin** [comment]
If you can use regexes for now, please look at the schema-level regex documentation here:
https://dev.grakn.ai/docs/schema/concepts#restrict-attributes-value-by-regex

You should be able to use the regex you write out! In fact, works for me by matching Amazon btu not Raspberry!

I will add the link to the supported java regex to the `like` regex query section.

**Comment by flyingsilverfin** [comment]
@johannesmutter  We don't plan on adding new sytax (eg. `startswith`) to Graql for a little while, as work on other parts of Grakn so I'm hoping the above solution works for you? If yes, we can close this issue :)

**Comment by krishnangovindraj** [comment]
The regex solution seems to have addressed the case.
