### ISSUE TITLE
Query Profiler Roadmap

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5358]
Following the team's discussion on how to return query profiling data, the future of benchmarking, here are preliminary components:

* Replace `zipkin` with a new grakn repository (possibly core package) called something like `profiling` which will have one function acting as a `collect(msg)` and aggregator of timing information (collect information similarly to zipkin, and aggregate spans into a tree)
* `profiling` will additionally act as a collector for data on the execution of reasoner - the entirety of the resolution tree should be collected, along with statistics such as how many times each rule was triggered. 
* `profiling` will also store the query plan and the estimated ahead of time cost of the query plan
* Overall, `profiling` will collect four areas of data: `tracing` (timing components), `resolution` (reason resolution tree, including dead ends and possibly timing), `planning` (query plan, estimated cost), `statistics` (rules fired how many times, possible other statistics)
* gRPC protocol will be extended to include `queryprofile`: a grpc representation of `profiling` data. It should be use the `profiling.aggregate()` functionality. Having the profiling data in the responses will help our users and clients inspect some of the operations performed by Grakn (such as which plan was executed and how many rules were run)
* Out of band collection for large numbers of queries being profiled - we re-use the `profiling` component with a different interface to receive messages sent out of band from Grakn to the collection server (replacement for Zipkin). This then would aggregate a result and persist it to a backend such as Grakn. The current interface to benchmark dashboard over GraphQL would not change, just the adapter that reads from storage.

Here is the initial roadmap:
1. @kasper-piskorski will iterate a bit on the collection of the full query resolution tree and rule statistics. For now, we can write these to logs and find a simple textual way to visualise them when they are not too large.
2. We will have a design session for extending the gRPC protocol @marco-scoppetta  @kasper-piskorski
3. [next priority not decided yet]

Would work towards implementing #5220 and #5344

**Comment by flyingsilverfin** [comment]
Results of design session with @marco-scoppetta  @kasper-piskorski 

1. Since each query corresponds to a single reasoner tree instance, we want to return a resource handle to that tree that can be used to read it from a client at any time.
2. The general idea is that on `tx.query()`, we don't just return the `iterator_id` anymore, but a set of handles to the server, such as `resolutionTreeId`, `queryProfileId`, and optionally later the `queryTracingId`
3. The Resolution Tree ID should allow us to read from the transaction the reasoner tree in full, parts of it as needed etc, to be designed as useful by @kasper-piskorski 
4. The future Query Profile ID will allow access to aggregate information such as number of times each rule was triggered, query plan, also accessed as a remote resource on the transaction
5. If we decide to allow this functionality in band as well, the Tracing resource on the server that will replace Zipkin's tracing can be accessed similarly, storing all tracing for the query. NOTE that tracing may be handled separately because we want to trace things other than just `.query()`, such as opening sessions, committing transactions etc. One idea is to create separate `TracingClient`s

Important big note: all of these resoruces are populated lazily on the server, so must call a `.next()` to build any of these resources. Clients will be implementing a new query response object that return not just a iterator anymore, but an object that has a `response.iterator().next()` or a `.response.profile().whatever()`. Probably want to implement a separate client-side method `queryWithAnalysis()` or something that toggles the reasoner tree collection, query profile collection etc.

**Comment by flyingsilverfin** [comment]
Not relevant in Grakn 2.0 anymore!

**Comment by sanmai-NL** [comment]
@flyingsilverfin Is #5220 still relevant then?

**Comment by flyingsilverfin** [comment]
@sanmai-NL  interesting to see thatold issue! I'd say yes, in a way to is accessible to our users. We already have one internally we enable for debugging, but we should expose it to the user :)

**Comment by flyingsilverfin** [comment]
Do you have an interest in that?
