### ISSUE TITLE
Semantic difference not applied correctly on roles if relation is not persisted

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#5396]
## Description

When applying semantic difference in cases when roles are specialised, we poll the database for existence of relations for a specific role player. If the relation is inferred and not persisted, it won't be found. The consequence is that the answer the semantic diff is applied to will be filtered out. This may lead to incorrect propagation of answers within the query cache.

## Reproducible Example

Parent query: `(role: $x, role: $y) isa someRelation;`

Child query: `(specificRole: $x, specificRole: $y) isa someRelation;`

Semantic diff: { ($x: specificRole), ($y: specificRole)}

## Expected Output
All answers are propagated correctly filtered by the semantic difference.

## Actual Output

Will only work if relation instances in question are persisted in the database

**Comment by flyingsilverfin** [comment]
Semantic difference is no longer used in 2.0
