### ISSUE TITLE
INVALID_ARGUMENT on adding attributes

### ISSUE THREAD

**Issue by bfour** [vaticle/typedb#5409]
## Description

I created a simple schema as in the picture below. When trying to add the mass attribute to phone or unit to mass, I get 

```
INVALID_ARGUMENT: InvalidKBException-A structural validation error has occurred. Please correct the [`2`] errors found.
The Role [@has-attribute-value] which is connected to Relation Type [@has-attribute] does not have a sub Role Type which is connected to the sub Relation Type [@has-mass]
The Role [@has-attribute-owner] which is connected to Relation Type [@has-attribute] does not have a sub Role Type which is connected to the sub Relation Type [@has-mass]
```
EDIT: works, after a restart of grakn server

## Environment

1. OS (where Grakn server runs): Windows 10
2. Grakn version (and platform): Grakn Core 1.5.8
3. Grakn client: Workbase and console
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create schema as shown where product, electronics and phone are abstract
2. try to add attributes as described

## Expected Output

no error

## Actual Output

```
INVALID_ARGUMENT: InvalidKBException-A structural validation error has occurred. Please correct the [`2`] errors found.
The Role [@has-attribute-value] which is connected to Relation Type [@has-attribute] does not have a sub Role Type which is connected to the sub Relation Type [@has-mass]
The Role [@has-attribute-owner] which is connected to Relation Type [@has-attribute] does not have a sub Role Type which is connected to the sub Relation Type [@has-mass]
```
 
## Additional information

![image](https://user-images.githubusercontent.com/1163867/64394541-f8b6b880-d056-11e9-8d0a-83aff51fb18b.png)

**Comment by flyingsilverfin** [comment]
@bfour  have you been able to reproduce this again by any chance?

**Comment by bfour** [comment]
Unfortunately not, but I'll report if I get to it again.

**Comment by flyingsilverfin** [comment]
Closing as not reproducible
