### ISSUE TITLE
grakn.properties should be refactored to be more user-friendly

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#5435]
## Problem to Solve

`grakn.properties` need to be more user-friendly, with consistent use of terms that are user-centric.

Its user-friendliness can be improved especially in these areas:
1. we user interchangeable terms such as `host` and `hostname`. we need to just use one terminology
2. implementation specific term such as `grpc.port`. it will be more user-centric if we call it `port` or `server.port`
3. accepts JanusGraph configuration. This is mainly useful for internal developers when  debugging / tweaking parameters and need to be adapted to be more user-friendly.

**Comment by vmax** [comment]
`grakn.properties` has been dramatically simplified for 2.0, so the issue has been resolved.
