### ISSUE TITLE
Negation Performance Querying Unshared Roles

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5490]
## Description
We find an interesting performance bug when querying for roles played by a type and not played by another type (its parent).

## Environment
Grakn Core 1.6.0

## Reproducible Steps
1. Load the `social-network` schema from docs (https://github.com/graknlabs/docs/blob/master/files/social-network/schema.gql)
2. Try this query:
`match $x type photo; $y type media; $x plays $role; not {$y plays $role;}; get; count;`
Observe that it a) never seems to terminate in reasonable time b) cannot be killed easily c) `htop` tells us that all CPU cores are churning like crazy computing this result

compared to:
3. `match $x type photo; $y type media; $x plays $role; $x sub $y; not {$y plays $role;}; get; count;`
This query only adds the additional constraint `$x sub $y`, which adds no real further restriction on the size of the set of results for the query without the negation component, but executes quickly!

## Expected Output
Empty set in reasonable time

## Actual Output
Doesn't terminate in reasonable time

**Comment by krishnangovindraj** [comment]
Has since been fixed.
Tested on 2.14.3 : Returns `0` almost instantly.
