### ISSUE TITLE
Process exited with code '3': ''

### ISSUE THREAD

**Issue by StrangeTcy** [vaticle/typedb#5517]
## Description

Trying to run `grakn server start` leads to an error:

> Starting Storage.....FAILED!
> Unable to start Storage.
> Process exited with code '3': ''
> An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
> Process exited with code '3': ''

## Environment

1. OS (where Grakn server runs): Ubuntu 18.4
2. Grakn version (and platform): Grakn Core 1.5.9
3. Grakn client:  console
4. Other environment details: Java was manually set to 8, so now`java -version` reports 

> openjdk version "1.8.0_222"
> OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
> OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
> 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Install grakn from repository (`sudo apt install grakn-core-all`)
2.  Make sure java 8 is used (`sudo update-alternatives --config java`)
3. Run `grakn server start`
4.  The error in the logs is as follows:

> 2019-11-26 01:33:29,150 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
> grakn.core.daemon.exception.GraknDaemonException: Process exited with code '3': ''
>         at grakn.core.daemon.executor.Storage.start(Storage.java:223)
>         at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
>         at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
>         at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
>         at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)

## Expected Output

Starting Storage ... SUCCESS
Starting Grakn Core Server...SUCCESS
and so on

## Actual Output

See step 4 above

**Comment by lolski** [comment]
Could be the same issue as this one: https://github.com/graknlabs/grakn/issues/5336

Could you try starting it with `sudo`? eg., `sudo grakn server start`?

**Comment by StrangeTcy** [comment]
It was the same issue, possibly.

So, I did the following:

1. just ran `grakn server start` as a non-root user (let's call him user). This resulted in an access denied error.
2. modified access rights: `sudo chown user:user /opt/grakn/core/server/services/cassandra/cassandra.yaml
`, and then tried to `grakn server start` again. This resulted in the same `code:3` error I mentioned above.
3. `sudo grakn server start` after that has lead to a different error: `An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Process exited with code '100': ''
`
The logs have this to say about that last error:

> [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
> grakn.core.daemon.exception.GraknDaemonException: Process exited with code '100': ''
>         at grakn.core.daemon.executor.Storage.start(Storage.java:223)
>         at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
>         at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
>         at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
>         at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)

**Comment by ancailliau** [comment]
I experience the same issue with ``Process exited with code '100': ''`` after upgrading to 1.6.0. 

Re-installing the 1.5.9 version solved the issue. 
``apt-get install grakn-core-server=1.5.9 grakn-console=1.0.1 grakn-core-all=1.5.9``

I'm running ubuntu 18.04: 
```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Installed grakn packages are :

```
# apt-cache policy grakn-*
grakn-core-console:
  Installed: (none)
  Candidate: 1.5.8
  Version table:
     1.5.8 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.7 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.6 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.5 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.4 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.3 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.2 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.1 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
grakn-core-all:
  Installed: 1.5.9
  Candidate: 1.6.0
  Version table:
     1.6.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
 *** 1.5.9 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
        100 /var/lib/dpkg/status
     1.5.8 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.7 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.6 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.5 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.4 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.3 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.2 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.1 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
grakn-core-bin:
  Installed: (none)
  Candidate: 1.5.8
  Version table:
     1.5.8 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.7 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.6 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.5 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.4 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.3 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.2 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.1 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
grakn-bin:
  Installed: 0.2.1
  Candidate: 0.2.1
  Version table:
 *** 0.2.1 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
        100 /var/lib/dpkg/status
     0.2.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     0.1.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
grakn-console:
  Installed: 1.0.1
  Candidate: 1.0.2
  Version table:
     1.0.2 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
 *** 1.0.1 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
        100 /var/lib/dpkg/status
grakn-core-server:
  Installed: 1.5.9
  Candidate: 1.6.0
  Version table:
     1.6.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
 *** 1.5.9 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
        100 /var/lib/dpkg/status
     1.5.8 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.7 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.6 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.5 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.4 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.3 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.2 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.1 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
     1.5.0 500
        500 https://repo.grakn.ai/repository/apt trusty/main all Packages
```

**Comment by flyingsilverfin** [comment]
Closing, please open another issue if you see similar issues in 2.0!!
