### ISSUE TITLE
Process exited with code '100': '' after upgrading to Grakn 1.6.*

### ISSUE THREAD

**Issue by SamuelHassine** [vaticle/typedb#5541]
## Description

Starting Grakn 1.6.0 or Grakn 1.6.1 on Grakn 1.5.9 data is not working. When trying to start the Grakn server, the following error occurred:

```
Starting Storage.....FAILED!
Unable to start Storage.
Process exited with code '100': ''
An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Process exited with code '100': ''
```

## Environment

1.  Ubuntu 16.04.6 LTS 
2. Grakn Core 1.6.*
3. All

## Reproducible Steps

1. Up and running Grakn Core 1.5.9
2. Shutdown the server
3. Start Grakn Core 1.6.0 on the same "db" directory

## Expected Output

Successful Grakn Core run.

## Actual Output

Grakn crashes during the boot-up process with the following exception:

 ```2019-12-19 23:25:23,698 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
grakn.core.daemon.exception.GraknDaemonException: Process exited with code '100': ''
	at grakn.core.daemon.executor.Storage.start(Storage.java:223)
	at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
	at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
	at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
	at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)
```
 
## Additional information

None.

**Comment by kasper-piskorski** [comment]
The reason why this happens is because we updated the default cass cluster name from `Grakn Example Cluster` (pre 1.6.0) to `Grakn Cluster`. What you need to do when migrating is to update the cluster name entry to the old value in `server/services/cassandra/cassandra.yaml`:

```
cluster_name: Grakn Example Cluster
```

Then Grakn will start normally.

**Comment by SamuelHassine** [comment]
@kasper-piskorski: Thanks a lot I will try this solution. Do you have an idea on how to automate this in a Docker deployment environement? Do you plan to ensure smooth migration from the Docker image Grakn 1.5.9 to Grakn 1.6.0 with persistent data?

**Comment by kasper-piskorski** [comment]
You can automate it by adding an extra command:
```
sed -ri 's/cluster_name:.*/cluster_name: Grakn Example Cluster/g' <grakn-distro-path>/server/services/cassandra/cassandra.yaml
```

**Comment by SamuelHassine** [comment]
@kasper-piskorski yes thanks, do you think it is possible to add for instance a envvar in the Grakn Docker Image KEEP_OLD_CLUSTER_NAME for instance? Because for users with persistent data, just upgrading the Docker image to 1.6.1 will break the boot-up process.

**Comment by richard-julien** [comment]
Or just a generic CLUSTER_NAME env.

**Comment by kasper-piskorski** [comment]
We'll look into that.

**Comment by richard-julien** [comment]
Thanks. More globally you should consider have some automated tests and migration in order to provides smooth upgrade of the database.

**Comment by kasper-piskorski** [comment]
Just a heads up. We will put an alternative way to make 1.5.9 compliant with 1.6.x in the docs, here is the PR: https://github.com/graknlabs/docs/pull/251

**Comment by richard-julien** [comment]
Sounds good at a first solution for manual deployment but not for a "production ready" docker deployment. I dont really want to advice users of openCTI to ssh a running container to do the migration and then redeploy new version of grakn with docker-compose... Could be very helpful to have a real built in migration system in grakn to prevent this... Of course I can fork the docker image you provide and integrate a migration system of my own but I will not be happy with that :)

**Comment by richard-julien** [comment]
By the way, it's possible to know the version of the database only in the db files (server/db directory)?

**Comment by kasper-piskorski** [comment]
That's totally understandable. We'll have a stab at an integrated system.

**Comment by SamuelHassine** [comment]
Hello @kasper-piskorski thanks for your answer. Do you plan to integrate it now?

**Comment by flyingsilverfin** [comment]
No longer applicable as the storage engine is not cassandra in 2.0
