### ISSUE TITLE
Matching queries and rules using integer comparisons return additional incorrect results

### ISSUE THREAD

**Issue by brettforbes** [vaticle/typedb#5544]
## Description
**Matching queries and rules using integer comparisons return additional incorrect results**
Consider a simple array of arrays, modelled by a 'trace' relation with two integer indexes. The use case is an event log (array of arrays) that holds traces (an array) of events (an event name only at this point). All array indexes are zero-based.

A match query made to find the first event in every trace, implies finding a trace that `has traceid $b, has index 0;`. This statement correctly returns the first event in every trace (i.e. where index=0), but also returns every event in the first trace, (where traceid=0, and index between 0 and 3). The additional records from the first trace are incorrectly selected as their index !=0.

A previous attempt to build a transitive rule, using the comparator `$index1 < $index2` was abandoned as the rule matched the reverse condition as well (i.e. when `$index1 > $index2`). Further, it was determined that the process mining needed a directly follows relation, rather than a transitive one, so this approach is not needed and was only mentioned to show the scope of the issue with integers. The code is attached below, along with images demonstrating the issue (slides 24-27 of my workbook)
[GRAKN Modelling v9.pptx](https://github.com/graknlabs/grakn/files/4028336/GRAKN.Modelling.v9.pptx)

[process_mining_basic.zip](https://github.com/graknlabs/grakn/files/4028282/process_mining_basic.zip)

## Environment

1. OS (where Grakn server runs): { Windows 10, local and slow :) }
2. Grakn version (and platform): { v1.61 }
3. Grakn client: {  client-python }
4. Other environment details: Code has a Visual Studio workspace file

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. {Setup a keyspace called "alpha1" }
2. {Load alpha.gql from schema directory}
3. { Run basic_upload.py in the terminal}
4. {Open Workbase, attach to keyspace and run queries in schema directory}

## Expected Output

{ See slides 24-27, errors are shown on 26 and 27}

## Actual Output

{see above}
 
## Additional information

{ see above }

**Comment by krishnangovindraj** [comment]
Closing, since we haven't had these issues for a while, these integer comparisons are covered by our tests and the example will be hard to port to the present version.
