### ISSUE TITLE
Attribtue Deduplicator Flaky Test (very rare)

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5555]
## Description
https://app.circleci.com/jobs/github/flyingsilverfin/grakn/5216 shows an instance of failure of Attribute Deduplicator test, however reproducing it has been impossible so far.

## Environment
https://app.circleci.com/jobs/github/flyingsilverfin/grakn/5216
CircleCI linux machine, Grakn 1.6.1

## Reproducible Steps
Haven't been able to reproduce, but should be by running `AttributeUniquenessE2E.shouldMergeAttributesInConcurrentTransactions`

## Expected Output
Should have 10 unique attributes.

## Actual Output
Returned 11 unique attributes one time.

**Comment by marco-scoppetta** [comment]
:open_mouth:

**Comment by flyingsilverfin** [comment]
Attribute deduplication is now handled at the rocksdb layer
