### ISSUE TITLE
Graql clean command causes DriverTimeoutException

### ISSUE THREAD

**Issue by BFergerson** [vaticle/typedb#5562]
## Description

Executing the "clean" command via the Graql console causes DriverTimeoutException.
I've also seen this issue occur when running:
```java
grakn.client.GraknClient.keyspaces().delete("grakn")
```

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: client-java & console

## Reproducible Steps

```sh
wget https://github.com/graknlabs/grakn/releases/download/1.6.2/grakn-core-all-linux-1.6.2.tar.gz
tar -xf grakn-core-all-linux-1.6.2.tar.gz 
cd grakn-core-all-linux-1.6.2/
./grakn server start
./grakn console

Welcome to Grakn Console. You are now in Grakn Wonderland!
Copyright (C) 2019 Grakn Labs Limited

grakn> clean
Are you sure? CLEAN command will delete the current keyspace and its content.
Type 'confirm' to continue: 
grakn> confirm
Cleaning keyspace: grakn
...
grakn.client.exception.GraknClientException: UNKNOWN: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT20S. Please check server logs for the stack trace.
	at grakn.client.exception.GraknClientException.create(GraknClientException.java:49)
	at grakn.client.GraknClient$Keyspaces.delete(GraknClient.java:793)
	at grakn.console.ConsoleSession.clean(ConsoleSession.java:273)
	at grakn.console.ConsoleSession.run(ConsoleSession.java:163)
	at grakn.console.GraknConsole.run(GraknConsole.java:112)
	at grakn.console.GraknConsole.main(GraknConsole.java:140)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT20S. Please check server logs for the stack trace.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at grakn.protocol.keyspace.KeyspaceServiceGrpc$KeyspaceServiceBlockingStub.delete(KeyspaceServiceGrpc.java:216)
	at grakn.client.GraknClient$Keyspaces.delete(GraknClient.java:791)
	... 4 more
```

## Expected Output

Expected the clean command to work

## Actual Output

The clean command throws a GraknClientException

**Comment by BFergerson** [comment]
Attached logs

[cassandra.log](https://github.com/graknlabs/grakn/files/4117916/cassandra.log)
[grakn.log](https://github.com/graknlabs/grakn/files/4117917/grakn.log)

**Comment by adiv5** [comment]
Any progress in this? I am getting the same error. Addtionally, I tried deleting from the workbase. but i still end up getting same error. Any Help appreciated

**Comment by flyingsilverfin** [comment]
how many things do you guys have in your keyspace?
```compute count in thing; ```

**Comment by adiv5** [comment]
getting this error :  Only get and compute path queries are supported for now.

**Comment by flyingsilverfin** [comment]
Try this: shut down your server.  Copy of your database (ie literally copy-paste your grakn distribution that contains the data and all that)...

In your copy, navigate into `server/db/cassandra/data`. You should see the names of each keyspace in a folder. Try deleting that folder you were trying to clean and restart the server. Keyspace should be completely gone :) Hopefully this works!

**Comment by p3t3rix** [comment]
Happens to me also:
-start docker image with grakn (docker run -d -p 48555:48555 graknlabs/grakn:latest)
-execute simple snippet (probably the same method as in the console)
` try (var client = new GraknClient("localhost:48555");
      var session = client.session("test");) {
  client.keyspaces().delete("test");
}
`
-get the error: UNKNOWN: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT20S.

Version: 1.8.1 of grakn-client

**Comment by vmax** [comment]
With 2.0.0 this should no longer happen as we don't use Cassandra anymore
