### ISSUE TITLE
How to add Grakn server to autostart everytime the machine boots up?

### ISSUE THREAD

**Issue by NetEyes** [vaticle/typedb#5564]
How to add Grakn server to autostart everytime the machine boots up?
i,e:
systemctl enable grakn

**Comment by flyingsilverfin** [comment]
If you have installed grakn via `apt-get` or something similar, you should be able to put this in a `cron` or `init.d` command...

https://stackoverflow.com/questions/12973777/how-to-run-a-shell-script-at-startup

I don't see why `grakn server start` or `/path/to/grakn/executable server start` shouldn't be possible! Hope this helps!

**Comment by flyingsilverfin** [comment]
If you have installed grakn via `apt-get` or something similar, you should be able to put this in a `cron` or `init.d` command...

https://stackoverflow.com/questions/12973777/how-to-run-a-shell-script-at-startup

I don't see why `grakn server start` or `/path/to/grakn/executable server start` shouldn't be possible! Hope this helps!

**Comment by vmax** [comment]
@NetEyes in vaticle/common#102 we've included a systemD unit file into APT installation of Grakn Core. Therefore, in 2.0.3, it would make `systemctl enable grakn-core` possible on systemD-based systems.
