### ISSUE TITLE
Super important, please don't use Java language keywords as variables or keywords in Grakn or Graql language 

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb#5568]
## Problem to Solve

Found in the code-base that the `var` keyword was used, not an issue upto Java 9 but later on it will be as starting Java 10 we have the `var` keyword as a reserved word.

## Proposed Solution

Use another name or expanded form of the keywords `var` whichever works best.

Note: issue raised on the back of [slack discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900).

**Comment by krishnangovindraj** [comment]
the TypeQL var function did not turn out to be an issue.
