### ISSUE TITLE
[UI/UX] Save console space and clutter with compact error reporting

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb#5569]
## Problem to Solve

When an exception occurs an error message and call stack is printed inside the console - this clutters up screen space and also the call stack isn't immediately useful.

Feedback like this in the Console does not help much other than clog up the screen:

```
java.nio.file.NoSuchFileException: ../shared/data.sgq
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at 
	at grakn.core.console.GraknConsole.run(GraknConsole.java:104)
	at grakn.core.console.GraknConsole.main(GraknConsole.java:140)l
```

## Current Workaround

N/A

## Proposed Solution

Just report the error and mention detailed error is logged elsewhere (print log file location). 

In case, of the container, create this log file in a location outside the container - ask the user to share such a volume with the container when in the context of the container. Clients might be scrapping log files into logging tools/systems. _See suggestion raised via [issue](https://github.com/graknlabs/grakn/issues/5565)._

## Additional Information

On the back of the [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900)

**Comment by vmax** [comment]
Given that Console has been rewritten from scratch for 2.0, new, more specific issues should be raised in [`vaticle/typedb-console`](https://github.com/vaticle/typedb-console) in case the need arises.
