### ISSUE TITLE
Grakn server limited to Java 8 which is EOL since January 2019

### ISSUE THREAD

**Issue by grexe** [vaticle/typedb#5572]
## Description

I'm surprised to find a cutting-edge solution like Grakn being limited to a very outdated Java version (JDK8) which has been discontinued as of Jan, 2019 already.
I need Grakn to run on a recent LTS release like JDK11 at least.

## Environment

1. MacOS X 10.15.3 (19D76)
2. Grakn core 1.6.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run `grakn server` in a terminal in Grakn's home directory
2. be amazed by the error "Unsupported Java version [11] found. Grakn needs Java 1.8 in order to run."

## Expected Output

Grakn server should happily run in a more modern environment using latest stable JDK, at least the most common setup OpenJDK 11.

## Actual Output

Grakn refuses to even start with OpenJDK 11.
 
## Additional information

I have some experience with upgrading complex solutions from JDK 8 to 11 and am willing to help with a PR or at least with testing and debugging which component needs attention. Afaik, sub projects used by Grakn are already JDK 11 compatible.

**Comment by grexe** [comment]
Please note: I understand almost 80% of Java installations are still using JDK 8, e.g. cf [Baeldung Java 2019 survey](https://www.baeldung.com/java-in-2019), but considering the special user group of Grakn, I suppose many more people will use latest technologies and at least latest stable versions.
This is also reflected in a [more recent report by JRebel 2020](https://www.jrebel.com/blog/2020-java-technology-report), where 5.5% even use Java 12 or newer, amounting to a total of 28% of developers using Java 11+.
Since this breaks Grakn on these setups and blocks me from using it at all, I consider this a bug.

Here is Oracle's announcement:
https://blogs.oracle.com/java-platform-group/end-of-public-updates-is-a-process%2c-not-an-event

**Comment by kasper-piskorski** [comment]
The current biggest showstopper is that we are using Cassandra 3.X. To Use Java 11 we would need to upgrade to Cass 4.X.

**Comment by grexe** [comment]
oh no, thanks for pointing this out @kasper-piskorski, that's a bit of a bummer that Cassandra is lagging behind considerably here...
No problem though, will use another JDK for Grakn, but missing out on considerable performance and GC improvements in JDK11+ then...

**Comment by grexe** [comment]
I see Cassandra 4.0 is quite some time in the making already, originally scheduled for Q4/2019, currently at [4.0-alpha3](https://github.com/apache/cassandra/releases/tag/cassandra-4.0-alpha3)

Could make a perfect timing with Grakn 2.0 to bring in some considerable additional performance improvements (communication over Netty2, virtual table optimizations etc.), what do you think?

**Comment by kasper-piskorski** [comment]
I think it's worth investigating. We could try using the alpha version to see how much work would need to be done to provide the upgrade.

**Comment by 2xyo** [comment]
On stable Debian GNU/Linux 10 (buster) :
```console
$ apt show grakn-core-all 
Package: grakn-core-all
Version: 1.7.0
Priority: optional
Section: contrib/devel
Maintainer: Grakn Labs <community@grakn.ai>
Installed-Size: unknown
Depends: openjdk-8-jre, grakn-core-server (=1.7.0), grakn-console
 (=1.0.4)
Download-Size: 10.7 kB
APT-Sources: https://repo.grakn.ai/repository/apt trusty/main all Packages
Description: Grakn Core (all)
```
Could you at least allow other java 8 in `Depends` section like : 
- oracle-java8-installer
- adoptopenjdk-8-hotspot-jre | adoptopenjdk-8-openj9-jre | adoptopenjdk-8-openj9xl-jre
- java8-runtime-headless | java8-runtime

So grakn could be easily installed with `apt`/`apt-get`on Debian 10 :smiley:

**Comment by grexe** [comment]
> The current biggest showstopper is that we are using Cassandra 3.X which only supports Java 8. To Use Java 11 we would need to upgrade to Cass 4.X which is not released yet.

well finally, this day has come now:=)
https://www.datastax.com/resources/webinar/cassandra-40-preview-most-reliable-elastic-fastest-cassandra-ever-emea

**Comment by Thell** [comment]
Perhaps another option, as a workaround, @grexe could be to use dummy control packages to meet the dependency check on the openjdk install. I tested this on Windows WSL Ubuntu 20.04 and had the grakn server up and connected to grakn Workbase on the host pretty quickly. (I haven't tested anything except that it starts and connects but that's better than a show stopper!)

Essentially...

```shell
sudo apt -y install equivs
equivs-control openjdk-8-jre.control
equivs-control openjdk-8-jre-headless.control
vim openjdk-8-jre.control # edit to reflect latest apt version
vim openjdk-8-jre-headless.control # edit to reflect latest apt version
equivs-build openjdk-8-jre.control
equivs-build openjdk-8-jre-headless.control
dpkg -i openjdk-8-jre_8u275-b01-0ubuntu1~20.04_all.deb
sudo dpkg -i openjdk-8-jre_8u275-b01-0ubuntu1~20.04_all.deb
sudo dpkg -i openjdk-8-jre-headless_8u275-b01-0ubuntu1~20.04_all.deb
sudo apt install grakn-core-server
sudo apt install grakn-console
sudo apt install grakn-core-all
sudo grakn server start
```
and check

```shell
 Ubuntu  ~  $  dpkg -l | grep jdk
ii  adoptopenjdk-8-hotspot-jre        8u275-b01-3                       amd64        OpenJDK Runtime Environment 8 (JRE) with Hotspot by AdoptOpenJDK
ii  openjdk-8-jre                     8u275-b01-0ubuntu1~20.04          all          Dummy entry.
ii  openjdk-8-jre-headless            8u275-b01-0ubuntu1~20.04          all          Dummy entry
```

```shell
Ubuntu  ~  $  grakn console

Welcome to Grakn Console. You are now in Grakn Wonderland!
Copyright (C) 2020 Grakn Labs

grakn>
```

Change the IP from `127.0.0.1` to `localhost` on Workbase and connect...

![image](https://user-images.githubusercontent.com/2185020/100280292-8f59e880-2f2d-11eb-90b4-58f619c0c110.png)

**Comment by flyingsilverfin** [comment]
in 2.0, we require Java 11 and greater!
