### ISSUE TITLE
Graql's formal verification tests

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5578]
## Problem to Solve

We plan to have a 4-part approach to testing graql and reasoning.

1. Graql Axiomatic tests - testing axioms and theorems using assertions about the consequences of write and read queries in graql, in a way that doesn't trigger any inference
2. Integrity tests - testing the integrity of the knowledge base using the semantics of a valid KB
3. Operational tests - internal reasoner tests for query unification using subsumption relations
4. Resolution tests - requires an oracle, for which we use a completed KB with all inferred facts materialised via forward-chaining. We compare this with a KB that uses backward-chaining inference (including comparing the exact rule resolution). The queries used for comparison [hand-made or generated over the complete KB] will also be generalised, and then checked for the subset relationship between answers of the original and generalised query.

1 and 2 are targeting graql and the state of the DB specifically, to enforce that the system behaves consistently and as expected. Both are used from within the BDD framework.

2 will be implemented to be used as an external tool as well as a library and live in the test-tools repository. This independent user of client-java can be saved as a binary and utilised by other clients in the BDD setting as well.

3 tests the internal reasoner query unification algorithm and is mostly complete #5576. It lives in the Grakn Core tests itself.

4 tests the inference algorithm more holistically from outside of the Grakn server, used within the BDD framework.

## Pieces of Work
1. Graql Axiomatic Tests

- [x] Create framework in BDD to test each allowed piece of the Graql operations that is defined in the syntax. The goal is to include both handwritten assertions over the expected output and compare the answers between types of queries. (https://github.com/graknlabs/verification/pull/3 and https://github.com/graknlabs/verification/pull/19)
- [x] Write different BDD scenarios for each of the _types_ of graql behaviors, including `define`, `undefine`, `match`, `insert`, `delete`. 

    * https://github.com/graknlabs/verification/pull/3
    * https://github.com/graknlabs/verification/pull/8
    * https://github.com/graknlabs/verification/pull/13

- [x] Implement a single test using the query answer comparison (https://github.com/graknlabs/verification/pull/17) 
- [x] Implement these BDD scenarios in `client-java` up to the currently defined scenarios (various PRs)
- [ ] flesh out scenarios with titles but no bodies in behavior specifications - https://github.com/graknlabs/verification/issues/18

2. Integrity Tests - based on theory of Graql semantics and invariants that should always hold

- [x] integrity tests for schema validation: https://github.com/graknlabs/verification/pull/9
- [ ] integrity tests for data validation: https://github.com/graknlabs/verification/issues/16

**Comment by krishnangovindraj** [comment]
Closing, as we closed vaticle/typedb-behaviour#16 as unplanned
