### ISSUE TITLE
Internal reasoner Atom hash codes may be unintentionally high-collision

### ISSUE THREAD

**Issue by adammitchelldev** [vaticle/typedb#5580]
## Description

**Potential performance bug with hash codes that requires further investigation.**

Hash codes within the reasoner atoms tend to follow the same hash code algorithm in the form:
```
int hashCode = 1;
hashCode = hashCode * 37 + field1.hashCode();
hashCode = hashCode * 37 + field2.hashCode();
return hashCode;
```
In theory, introducing the prime number multiplication provides good key distribution for ordered fields even when mod by a power of two (31 is commonly used as it can be done quickly with a `(i << 5) - i`), so it is useful for minimising collisions in `HashMap` or `HashSet`. However, this algorithm tends to assume that the hash code is only being compared to other hash codes of the same class, and as such is not intended to avoid collisions with other classes.

In the case of the reasoner, these hash codes are being used to generate hash codes for `com.google.common.base.Equivalence`, which is a class designed to make keys for multi-class situations where equivalence is more complex. This throws the metaphorical "spanner" in the works for using this hash code generation method since the actual class of the atoms is now considered part of the equality but not considered in the hash code.

Worse still is that missing or optional fields defaulting to adding 0 or 1 means that classes which are "empty" would often generate the same hash code of 37^2 (+2), two empty atoms would often be indistinguishable. This could lead to build-up of keys in the caches that result in unnecessary equivalence checking across multiple queries.

The expected performance impact of this bug is low though, since queries commonly introduce at least one or two values and the "order" of those values being different should be enough to introduce entropy to keep collisions down. It is potentially bad for "less strict" equivalence checking though, such as structural equivalence, which may not consider the values at all. Having good hashing makes bloom filters more effective (not that they are currently used).

## Solution

A solution to this would be at least to introduce a unique `private static final int HASH_CODE = <base>;` to each class to initialise `hashCode` with. This would avoid the "empty class" and "same fields" collisions.

Further improvements to the algorithms could be made (e.g. in `AtomicEquivalence`, a set is hashed by sorting it and then doing the shifting algorithm instead of simply XORing them (they do not require order and there are no duplicates since they are in a set)).

**If this change is made, it should be well recorded and documented.**

**Comment by flyingsilverfin** [comment]
Profiling the current 2.0.2 state shows little to no time spent in hashing, and the current class does not exist at all, so we close the issue.

**Comment by adammitchelldev** [comment]
Performance issue would have been due to hash collisions, not time spent hashing.
