### ISSUE TITLE
Insertion of attribute ownership isn't made when attribute has previously been inferred by a match

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5585]
## Description

When inserting the ownership of an attribute with a `match insert` query, the query throws no error, but fails to insert the `has` edge to the attribute owned. It does this when the attribute has previously been inferred by a rule on a previously executed match query. This set of `match` query followed by `match insert` query need to have taken place within the same transaction, and programmatically such that they are made in quick succession.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: client-java

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load the attached schema
2. Run the attached Java test

The test fails if there is a different number of results for the queries: `match $x isa employment; get;` and `match $x isa employment, has start-date $sd; get;`

The workaround is to close the transaction and open a new one in-between making the `match` query and the `match insert` query.

## Expected Output

The above queries should return the same `employment`, as the `employment` should be inserted with a `start-date`.

## Actual Output

The `start-date` is not owned by the `employment`, although the `start-date` has itself been inserted.
[DateAttributeBugTest2.txt](https://github.com/graknlabs/grakn/files/4236572/DateAttributeBugTest2.txt)
[schema.txt](https://github.com/graknlabs/grakn/files/4236574/schema.txt)

**Comment by krishnangovindraj** [comment]
No longer relevant as we no longer have inference in write queries.
