### ISSUE TITLE
Rewrite MapReduce InputFormats (Hadoop, CQL, Grakn) into one class

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb#5593]
## Problem to Solve

The `//mapreduce` package provides a Hadoop MapReduce `InputFormat` that is implemented by`InputFormatHadoop`. `InputFormatHadoop` requires a `VertexDeserialiser` but itself also takes in another Hadoop MapReduce `InputFormat`: `InputFormatCQL`, which also takes in a Hadoop Map Reduce `InputFormat`: `InputFormatGrakn`. So we can see now that we probably don't need 3 Hadoop MapReduce `InputFormat`s that compose each to other. This is where the meat of the code sits, and can definitely be collapsed into one simple `InputFormat` class that built specifically just for Grakn.

## Proposed Solution

Rewrite `InputFormatCQL`, `InputFormatGrakn`, and `InputFormatHadoop` (along with their `RecordReader`s) into one class.

**Comment by flyingsilverfin** [comment]
in 2.0, we no longer use `compute`, and will likely introduce an entirely new architecture when it returns
