### ISSUE TITLE
Should double and boolean attributes be allowed as keys?

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5598]
## Description
At present it is possible to assign a `double` or a `boolean` attribute as a `key`, but is there ever a use case for these?
For a `double` key, if permitted, we should check that comparisons with `0.0`, `-0.0`, `NaN` are handled well. Also we should keep in mind that floating point comparison cross-platform is also tricky.

**Comment by krishnangovindraj** [comment]
Using doubles and boolean as keys was disabled in TypeDB (commit `0fd1d5b72e0772d8f2ac5783a029395a72d1dce7`)
It also fixes #5438
