### ISSUE TITLE
Inserting identical Attribute with different Keys succeeds

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5601]
## Environment

1. OS (where Grakn server runs):Mac OS 12
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: anywhere
4. Other environment details:

## Reproducible Steps
In console:
1.`define define name sub attribute, datatype string, key ref; ref sub attribute, datatype long;`
2. `commit`
3. `insert $x "john" isa name, has ref 0;`
4. `commit`
5. `insert $x "john" isa name, has ref 1;`
6. `commit`
7. `match $x isa name, has name $a; get;`

## Expected Output
Exception on the second commit due to key validation

## Actual Output

{$a 1 isa ref; $x "john" isa name;}
{$a 0 isa ref; $x "john" isa name;}
 
## Additional information
Validation error for key

**Comment by krishnangovindraj** [comment]
This has since been fixed. Tested on 2.14.3
```
define
 name sub attribute, value string, owns ref @key;
 ref sub attribute, value long;
# (Success)

insert $x "john" isa name, has ref 0;
# (Success)
```


```
insert $x "john" isa name, has ref 1;

## Error> [THW06] Invalid Thing Write: Attempted to assign a key of type 'ref' onto a(n) 'name' that already has one. 
```
