### ISSUE TITLE
test-assembly-* no longer tests if the OLAP / compute framework is loaded at runtime

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#5602]
We want to ensure that the OLAP framework is loaded properly.

The current approach is to run a test which executes `compute count`.

However, with the introduction of the instance count cache, it hits this cache instead of the OLAP framework: https://github.com/graknlabs/grakn/blob/master/test/common/GraknApplicationTest.java#L60

The short term action that achieves the original goal is to update the test to another kind of `compute` query such as `compute centrality`.

**Comment by krishnangovindraj** [comment]
Closing, since we no longer have OLAP/compute
