### ISSUE TITLE
gRPC error in kglib -Received RST_STREAM with error code 1","grpc_status":13

### ISSUE THREAD

**Issue by Frazad** [vaticle/typedb#5631]
## Description
     GRPC Error while writing predictions on grakn while training. i have shared a error screenshot.
     i am working on opencti , which i built on grakn , and i am trying to run kgcn on it. i tried it many 
    times but i never get this error before.
## Environment

1. OS : { Ubuntu 18.4}
2. Grakn version: { 1.6.2 Grakn Core on my personal vm instance on gcp}
3. Kglib 0.2.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Run kgcn on any problem , i run it on opencti }
2. { training model }
3. { writing predictions }

## Expected Output

{ Expected output is , predicted output of kgcn and relation with probability quries should be written on grakn and kgcn stop smoothly }

## Actual Output

{ Error while writing predictions on grakn . GRPC error }
 
## Additional information
![bug-report](https://user-images.githubusercontent.com/44872960/76099164-88302a80-5fec-11ea-899c-30e78de832a7.png)
![bug-report2](https://user-images.githubusercontent.com/44872960/76099223-9f6f1800-5fec-11ea-8a87-d879c7472a68.png)

{ screenshots are attached}

**Comment by krishnangovindraj** [comment]
Too old to reproduce. Both Grakn/TypeDB and kglib/typedb-ml have been rewritten since.
