### ISSUE TITLE
The restriction on the number of negation blocks inside a rule body is not enforced consistently.

### ISSUE THREAD

**Issue by MajaTr** [vaticle/typedb#5648]
## Description

The documentation page on [negation blocks](https://dev.grakn.ai/docs/pattern/negation) claims that 

> each rule can only have a single negation block.

However, some rules with two negation blocks are not rejected.

## Environment

1. OS (where Grakn server runs): Ubuntu 16.04
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run
```
define label sub attribute, datatype string;
define edge sub relation, relates source, relates destination;
define vertex sub entity, has label, plays source, plays destination;
```
2. Define the first rule
```
define impossible sub relation, relates x;
define impossible-rule sub rule, when { 
  $_ (source: $0, destination: $1) isa edge; 
  not { $_ (source: $0, destination: $2) isa edge; }; 
  not { $_ (source: $2, destination: $1) isa edge; }; 
}, then { 
  $_ (x: $0) isa impossible; 
};
```
3. Define the second rule
```
define possible-passing sub relation, relates x;
define possible-passing-rule sub rule, when {
  $_ (source: $1, destination: $0) isa edge; 
  not { $_ (source: $0, destination: $2) isa edge; }; 
  not { $_ (source: $2, destination: $1) isa edge; }; 
}, then { 
  $_ (x: $0) isa possible-passing; 
};
```
4. Try to define the third rule
```
define possible-failing sub relation, relates x;
define possible-failing-rule sub rule, when { 
  $_ (source: $0, destination: $2) isa edge; 
  not { $_ (source: $0, destination: $0) isa edge; }; 
  not { $_ (source: $1, destination: $0) isa edge; }; 
}, then { 
  $_ (x: $0) isa possible-failing; 
};
```
Note that these rules are not dependent on each other, they're included to contrast their behaviour. 

## Expected Output

All three rules should be rejected with the message `The rule [<rule-name>] contains multiple negation blocks.`

## Actual Output

Only the third rule is rejected.
 
## Additional information

The conditions in the first rule can never hold simultaneously, and I thought it's the reason why it passes validation, i.e. it gets optimised away. However the second rule passes validation as well, even though it can't be optimised away this way.

**Comment by flyingsilverfin** [comment]
We can now have as many negations in rules as we like in 2.0
