### ISSUE TITLE
Writes via client Concept API won't behave predictably with iteration after streaming optimizations

### ISSUE THREAD

**Issue by adammitchelldev** [vaticle/typedb#5706]
## Problem to Solve

When iterating over mutable data in a "purely lazy" fashion, writes can affect the results in later iteration. In a write Transaction, this side-effect might be defined to be possible, since we expect to be able to read our own writes.

Since Concept API methods can be invoked whilst iterating query results or an iterable Concept API method, it is possible for the user to request that data is changed during iteration. Under the old style, where iteration was achieved with "one-at-a-time" iteration methods, the order was well-defined, and therefore the behaviour was predictable in a correctly implemented client (with fully lazy iteration).

However, synchronous lazy iteration is slow on a network, since each new result must be fetched in a blocking RPC call, introducing a full round-trip of latency and preventing concurrent operations between the client and the server. In order to alleviate this, we are moving towards async calls, starting with iteration streaming, where the server will calculate the results of the iteration and send them to the client in advance of the client code performing the iteration (streaming in batches to a client buffer).

This presents a problem, because the results are no longer able to be affected by Concept API writes made during iteration. If the underlying iterator sees the results, this will manifest as **unpredictable reads of writes within a transaction**, which is only ever going to be bad. If we want to support iteration that reads "mid-iteration" writes, there needs to be a solution.

## Proposed Solutions

Here are some options:
1. Do not allow an iterator to be affected by writes that happen after the iteration begins. The client can still open new iterators that will see existing writes but would not see new writes reflected in old iterators. This would allow the keeping of the optimisation.
2. Revert streaming/lazy iteration in a write transaction to be synchronous one-at-a-time. We can keep the optimisation for the results of `tx.execute()` but would lose optimality for any streamed queries and results of iterable Concept API methods.

**Comment by krishnangovindraj** [comment]
It is currently accepted that concurrent writes and reads within a transaction will produce non-deterministic answers.
If snapshot-like behaviour is desired, one needs to use separate transactions.
