### ISSUE TITLE
Clean up mentions of Implicit in Compute framework

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#5737]
## Problem to Solve
#5722  removes implicit types, roles and relations, from the DB. This means that some of the implementation in the analytics/compute framework needs to change, though tests are still passing. Notably the `KCoreVertexProgram` makes heavy usage of a property called `IMPLICIT_MESSAGE_COUNT` that should not be relevant anymore, or refactored.

## Proposed Solution
* Update `VertexProgram` classes using `IMPLICIT_MESSAGE_COUNT`

**Comment by krishnangovindraj** [comment]
Compute framework no longer exists
