### ISSUE TITLE
Test that the Builder pattern TypeQL wrapper functions identically to its equivalent TypeQL

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb#5749]
## Problem to Solve

Since migrating our Graql language ITs to BDD, we have lost coverage of our Builder pattern (which can not be tested in BDD).

## Proposed Solution

We should add integration tests for the Graql Builder pattern.

**Comment by krishnangovindraj** [comment]
The `ParserTest` does check the parsed language against the queries constructed with the builder pattern.
