### ISSUE TITLE
Error message testing

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb#5750]
## Problem to Solve

Since migrating Graql language ITs to BDD, we have lost some test cases that tested if the error message generated by a particular erroneous scenario matched a particular pattern.

The error cases whose detail is lost are:

1. Given `define name sub attribute, value string`, attempting to `define name value boolean` throws "Cannot insert property `%s %s` on existing concept `%s`".
2. `match $x isa movie; delete $y isa thing;` throws "the delete clause variable [%s] is not defined in the match clause"
3. `match $x isa person; $r isa name; $r "John"; delete $r isa person;` throws "it is not of the required type (or subtype of)"
4. `match $x has title $a; delete $x has thing $a;` throws "Cannot delete attribute ownership, concept [$a] is not of required attribute type [thing]".
(Note: using a "too specific" type (downcasting, ie: `match $x has name $n; delete $x has first-name $n`) currently throws the same error message)
5. `match $m isa movie; delete $m isa! entity` throws "it is not of the required direct type [entity]"
6. Given `define reflexive sub relation, relates refl; athing sub entity, plays refl; insert $r isa reflexive, relates $p as refl; $p isa athing;` then `match $r(refl: $x) isa reflexive; delete $r(refl: $x, refl: $x)` throws "Cannot delete role player [$x]; it does not play required role (or subtypes of) [refl]"
(Note: using a "too specific" role (downcasting, ie: `match $r(refl: $x) isa reflexive; delete $r(sub-refl: $x)`) throws the same error message)
7. `define column sub thing` throws "'column' cannot be a subtype of 'thing'"
8. `insert $x > 18 isa age;` throws "cannot insert a concept with a predicate"
9. `insert $x isa person, has ref 0; $x id V123; $x id V456;` throws "A concept `$x isa person, has ref 0;` cannot have multiple properties `V456` and `V123` for `id`"
10. `insert $r (employee: $x, employer: $y) isa employment; $y isa company, has name "Sports Direct";` throws GraqlSemanticException-"$x doesn't have an 'isa', a 'sub' or an 'id'"
(Note: inserting an attribute value with no type throws the same error message)
11. `match ($x, $y) isa friendship; get $x; group $y;` throws "the variable [$y] is out of scope of the query"
(Note: sorting by a variable that is out of scope throws the same error message)
12. `undefine employment has name;` throws "Failed to: undefine [employment] has [name]. Attribute ownership does not exist."
13. `undefine person has name;` with existing instances of `person` that have a `name` throws: "Failed to: undefine [person] has [name]. There exists instance of this pattern."
14. `undefine child has name;` when `child sub person` and `person has name` throws: "Failed to: undefine ownership of [child] has [name]. Attribute ownership is inherited from a super type."
15. `undefine person sub entity;` when instances of `person` exist throws: "Type [person] cannot be deleted as it still has incoming edges"
(Note: undefining a parent entity that has children throws the same error message)
16. `match $x != $y; get;` throws "Variables used in comparisons cannot be unbounded [$x, $y]"
17. `match $x isa ganesh; get;` throws "label 'ganesh' not found"
18. `match (person: $x) isa relation; get;` throws "'person' is not a role type. perhaps you meant 'isa person'?"
19. `match ($x) isa person; get;` throws "'person' is not a relation type. perhaps you forgot to separate your statements with a ';'?"
20. `match $x has person "Luke"; get;` throws "type 'person' must be an attribute-type"
21. `insert $x isa company, has age 10;` (where company can't have 'age'), throws "The type [company] is not allowed to have an attribute of type [age]"
22. `match $x isa friend; get;` throws "friend is not a type and so does not have instances"
23. `match $x isa person; insert $x isa company;` throws "Downcasting concepts from type `Base Type [ENTITY_TYPE] - Id [] -Label [person] to type ... is not allowed"
Note: this is a bad error message - it's a side cast, not a downcast!
24. `match $x isa person; get $y;` throws "the variable [$y] is out of scope of the query"

## Current Workaround

The BDD tests, which do not support error message testing at present, test that an error was thrown, but do not inspect the error message to verify that it is correct.

**Comment by alexjpwalker** [comment]
While some of the error messages have inevitably changed since this issue was created, I believe it is still relevant - we still have a large number of tests that test "throws exception" without validating the error message.

This has masked coverage issues in the tests before, for example, when errors in match aggregate queries were supposed to test that certain attribute value types were incompatible with certain aggregate operators, but in fact the error thrown was "could not convert GraqlMatch.Aggregate to GraqlMatch", ie a bug in the test.

**Comment by krishnangovindraj** [comment]
Subsumed by typedb-behaviour#221
