### ISSUE TITLE
Omitting relation variables in rule body is more efficient but can't be visualised

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5762]
## Problem to Solve

This issue has been highlighted by Workbase's `explain` feature. When explaining an inferred relation, we would like to visualise all of the elements from the inferring rule's body. Currently, this is not possible (without hacks) in Workbase; This is because the explanation given only includes concepts for the variables given in the rule's body. If the rule's body skips a variable, e.g. skipping a relation variable `($x, $y);`, then this relation has never been materialised.

This non-materialisation is for good reason: materialising relations in rule bodies incurs an expected performance penalty of approx +50% for reasoning queries. But it makes visualisation difficult. This represents a efficiency/explainability tradeoff. Presently, whether the user adds relation variables in their rule determines whether they get efficiency or visual explanations in Workbase.

For example in the case of a transitive rule, this will be more efficient:

```
location-hierarchy-is-transitive sub rule,
when {
  (superior-location: $a, subordinate-location: $b) isa location-hierarchy;
  (superior-location: $b, subordinate-location: $c) isa location-hierarchy;
}, then {
  (superior-location: $a, subordinate-location: $b) isa location-hierarchy;
};
```

Whereas this will allow the user to see how the inference was made in Workbase by right-clicking and hitting `explain`:

```
location-hierarchy-is-transitive sub rule,
when {
  $r1(superior-location: $a, subordinate-location: $b) isa location-hierarchy;
  $r2(superior-location: $b, subordinate-location: $c) isa location-hierarchy;
}, then {
  (superior-location: $a, subordinate-location: $b) isa location-hierarchy;
};
```

## Workaround

The user-side workaround at present is to `undefine` and `define` each rule with or without missing variables according to whether they need to run in a performant or visually explainable way.

## Proposed Solution

There are broadly four possible solutions:

1. Implement the materialisation of rule body variables only when the user calls `.explain()`, this would be performant and fully visually explainable
2. Use dummy nodes in Workbase for Concepts that we know are present, but which we don't have a Concept object for
3. Always add a variable for relations so that they are always materialised OR materialise them regardless of variable presence
4. Change the UX altogether to introduce `explain` queries, or change the behaviour at the highest level in some other way

We were aiming to implement (1), however when a rule body contains a very general statement like `($x, $y) isa relation;`, there could be multiple instances of different types that could satisfy this pattern: this query needs to be executed again with id substitutions, and multiple results could be returned. Discerning the concrete type can be achieved by inspecting the pattern of the `then` of the rule that comes with this explanation. Then a more specific query can be made. This is essentially un-picking the type inference that has already been made.

There is also ambiguity in terms of how a result was created, for example we would need to ensure that the concepts materialised match the resolution tree that was initially made by the reasoner - two rules could infer the same relation, or multiple relation instances (of different types) between the same roleplayers.

Overall, this approach was found to be complex, with uncertainties over how brittle it may be and the errors it could introduce. It is an optimisation over the initial optimisation of non-materialisation.

Solution (2) is possible but not ideal, and we feel tha the issue should be fixed properly in Grakn itself, rather than patched in Workbase.

Therefore we prefer solutions (3) or (4). We plan to see the scale of performance penalty of (3) once our faster backend is integrated. The penalty may/should be minimal and could be acceptable. We should in any case consider (4), as this could give the new feature of streaming back all possible explanations, rather than just the one that Grakn used to find a `match` result.

**Comment by jmsfltchr** [comment]
This issue supersedes #5753

**Comment by flyingsilverfin** [comment]
In 2.0, omittingn or not omitting the relation variable is no longer relevant to explanations!!
