### ISSUE TITLE
Grakn doesn't display error message for mismatched data type at insert (double\float)

### ISSUE THREAD

**Issue by kubpie** [vaticle/typedb#5774]
#5574  Description

Grakn wouldn't display an error, while the **inserted** data format doesn't match the type in the schema.
In effect an attribute of type _double_  was assigned data of type np.float() 
That created unwanted unique IDs for attributes that should be sharing the same value.

Related to the issue described in: https://github.com/graknlabs/grakn/issues/5759#issue-637217622

## Environment

1. OS (where Grakn server runs):Windows 10
2. Grakn version (and platform): Grakn Core 1.6.2
3. Grakn client:  Python Client 1.6.1, 
4. Other environment details:  Workbase 1.2.7

## Reproducible Steps

Please see the original issue post ([link](https://github.com/graknlabs/grakn/issues/5759#issue-637217622)) for the descriptio of schema and data migration file.

## Expected Output

Displayed error message about data type mismatch after invalid 'insert' query transaction.

## Actual Output

No error message.

**Comment by flyingsilverfin** [comment]
Thank you!

**Comment by krishnangovindraj** [comment]
From Joshua;
At some point we fixed a bug where TypeDB double datatypes were being stored as smaller floats.
We believe this is fixed, but please re-open if it still occurs
