### ISSUE TITLE
Missing Ascii art from `grakn server start` and `grakn server stop`

### ISSUE THREAD

**Issue by daniel-crowe** [vaticle/typedb#5781]
## Description

{ Upon installing Grakn 1.8.0 and running `grakn server start` in terminal, the _Grakn Server_  Ascii art was missing. } 

## Environment

1. OS (where Grakn server runs): { Mac OS 10.15 }
2. Grakn version (and platform): { Grakn Core 1.8 }
3. Grakn client: { N/A }
4. Other environment details: Installed via homebrew via terminal 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Run: `grakn server start` via terminal }

## Expected Output

{ Grakn server starts with Ascii art }

## Actual Output

{  Grakn server starts without Ascii art}
 
## Additional information

{ N/A
<img width="765" alt="Screenshot 2020-06-22 at 11 13 44" src="https://user-images.githubusercontent.com/57318771/85277310-20a6c980-b47b-11ea-96c2-bee7bc29882c.png">
 }

**Comment by flyingsilverfin** [comment]
Should be fixed in 2.0, as the process remains in the foreground
