### ISSUE TITLE
Remove tests using Client Java

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb#5789]
## Problem to Solve

We want to remove all cyclic dependencies in Grakn, or any semantically incorrect dependencies that contribute to "cycles". Quite often these incorrect dependencies are also "smells" to other underlying wrong decisions, such as Client Java's usage in Grakn Core tests. Client Java is one of our "database client libraries", and thus should not be used to run tests on the server-side itself.

## Proposed Solution

Search for every usage of `@graknlabs_client_java`, which are all in tests, and do either one of the following:
1) If the test makes sense, but is valuable in that it verifies the correctness of the client behaviour, then migrate it to Client Java.
2) If the test makes sense, but is valuable in that it verifies the correctness of the server behaviour, then replace `GraknClient` from Client Java with one from the server.
3) If the tests don't make sense, delete it, or merge it into some other test class where you think it would make sense.

**Comment by dmitrii-ubskii** [comment]
Resolved: at the time of writing there are no usages of TypeDB Client Java anywhere in the codebase.
