### ISSUE TITLE
Rule debugging

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb#5792]
## Problem to Solve

Rules can fail to behave correctly for many reasons, and they are currently very hard for a user to debug. See https://github.com/graknlabs/grakn/issues/5660 for an example.

## Current Workaround

Keep trying different things and pray that they work.

## Proposed Solution

It would be useful to have a tool that scans rules for potential issues (e.g: https://github.com/graknlabs/grakn/issues/5660) and flags them up to the user.

**Comment by flyingsilverfin** [comment]
Our visual tracing system makes rule debugging much easier for us internally. Error messages and rule commit validation should be better now too, in 2.0.
