### ISSUE TITLE
Reasoner treats attribute variable as a value only for attribute attachment across types

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5809]
## Description

Inferring a new attribute based on an existing attribute, where the two have differing types, doesn't make sense in the current syntax. This is nonsensical because a variable in Graql always captures type information, and so a single variable in this scenario is being used with two different types.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 1.8
3. Grakn client: client-java

## Current behaviour

In a rule such as this:
```
born-in-location-implies-residency-date sub rule,
      when {
          $bi(born-in_place-of-birth: $location, born-in_child: $person) isa born-in;
          $r(residency_resident: $person, residency_location: $location) isa residency;
          $person isa person, has date-of-birth $dob;
      }, then {
          $r has start-date $dob;
      };
```
We can see that the variable `$dob` is used to refer to an attribute of type `date-of-birth` in the `when`, but of type `start-date` in the `then`. A variable in Graql refers to both a type **and** value (in the case of an attribute), so this case is an exception.

Our resolution testing framework highlights this issue when it tries to run a query such as:
```
match 
$bi(born-in_place-of-birth: $location, born-in_child: $person) isa born-in;
$r(residency_resident: $person, residency_location: $location) isa residency;
$person isa person, has date-of-birth $dob;
$r has start-date $dob;
get;
```
This yields an error due to the contradiction of types.

## Possible Alternative

The following might be expected to work
```
born-in-location-implies-residency-date sub rule,
      when {
          $bi(born-in_place-of-birth: $location, born-in_child: $person) isa born-in;
          $person isa person, has date-of-birth == $sd;
          $r(residency_resident: $person, residency_location: $location) isa residency;
      }, then {
          $r has start-date $sd;
      };
```
However in this case the rule doesn't pass validation as the variable `$sd` doesn't have a type given in the `when` and is therefore considered to be unbound.

Binding it as follows will commit successfully:
```
born-in-location-implies-residency-date sub rule,
      when {
          $bi(born-in_place-of-birth: $location, born-in_child: $person) isa born-in;
          $person isa person, has date-of-birth == $sd;
          $sd isa start-date;
          $r(residency_resident: $person, residency_location: $location) isa residency;
      }, then {
          $r has start-date $sd;
      };
```
However this changes the meaning of the rule, as `$sd` must already exist as a `start-date` for the rule to be triggered.

**Comment by flyingsilverfin** [comment]
This is not implemented and wil be brought back when we have arithmetic. Closing as of 2.0.2
