### ISSUE TITLE
Validation of rule body incorrect when attaching attribute

### ISSUE THREAD

**Issue by lriuui0x0** [vaticle/typedb#5813]
## Description

It seems that role player validation is applied to both the `when` and the `then` clause, when I only want move the attribute value.

## Environment

1. OS (where Grakn server runs): { Mac OS 10 }
2. Grakn version (and platform): { Grakn Core 1.8.0 }
3. Grakn client: { console }

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Run query:
```
define
number sub attribute, value long, plays successor_prev, plays successor_next;
successor sub relation, relates successor_prev, relates successor_next;
eval-input_0 sub number, value long;
eval-output sub number, value long;
eval sub entity, has eval-input_0, has eval-output;
func_successor sub rule, 
when { 
  $eval isa eval, has eval-input_0 $input; 
  $input-number isa! number;
  $input == $input-number;
  $output isa! number;
  (successor_prev: $input-number, successor_next: $output) isa successor;
},
then {
  $eval has eval-output $output;
};
```

2. See this error:
```
INVALID_ARGUMENT: InvalidKBException-A structural validation error has occurred. Please correct the [`1`] errors found.
Rule [func_successor] attempts to define a rule containing a relation pattern with type [eval-output] that cannot play role [successor_next] in relation [successor]
```

**Comment by alexjpwalker** [comment]
Could you try to reduce the "Reproducible Steps" scenario to be the smallest possible scenario, @lriuui0x0? Currently it's hard to pinpoint the problem.

**Comment by JRWest2000** [comment]
__NOTE__

This is based on a logical analyst of the required functionality and common coding errors without any knowledge of the underlying code so please allow for implementation details. To summarise look for something that should have been removed and was overlooked then an erroneous assumption that all unconsumed items belong to the last list member.  

__DETALIED EXPLANATION__

Could Be way off base but It looks like:

this line should return $input as a __value__
  $eval isa eval, has eval-input_0 $input; 

this line should return $input-number as an __attribute__
  $input-number isa! number;

this line automatically converts the __attribute__ reference $input-number to the __value__ owned by $input-number.
which would require creating a temp variable with the type long. to hold the value. 
  $input == $input-number;

__Possibal result__

The temp variable gets deleted but not, all instances of the variable type long flag, are deleted from the ruel 
so when executing the line.
 (successor_prev: $input-number, successor_next: $output) isa successor;
the reasoner recognizes that $output is the last available variable in the when clause and assumes that the verabile type flag stack is error free so it assinges all remaining flags to the last variable. the result is $output is assigned the type long flag and fails the valid role target test.

**Comment by krishnangovindraj** [comment]
Error message suggests it was not allowed to use a sub-type as a role-player.
Since the issue was created, attribute inheritance has been revised to a point where this is not reproducible.
