### ISSUE TITLE
LICENSE and README.md text files packaged with executable bit set in 1.8.0

### ISSUE THREAD

**Issue by mcarifio** [vaticle/typedb#5818]
## Description

Looks like the LICENSE and README.md text files packaged with executable bit set in 1.8.0:

 -r-xr-xr-x       0/0         34520 ./grakn-core-all-linux-1.8.0/LICENSE
 -r-xr-xr-x       0/0          7703 ./grakn-core-all-linux-1.8.0/README.md

Yes, it's very much a quibble.

**Comment by dmitrii-ubskii** [comment]
Resolved as of 2.14.3
