### ISSUE TITLE
Check for client to server compatibility

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5835]
## Problem to Solve

Presently the behaviour that users see when connecting their client to an incompatible Grakn version is undefined, often giving an RPC error.

## Current Workaround

Compatibility table in the docs and synchronised releases of compatible clients when the server introduces breaking changes.

## Proposed Solution

Likely a new protocol is required that can determine whether the client and server are compatible. This should remain consistent indefinitely for backwards compatibility.

**Comment by flyingsilverfin** [comment]
This is implemented in #6813
