### ISSUE TITLE
No keyserver available

### ISSUE THREAD

**Issue by MathRig** [vaticle/typedb#5840]
Hi, 

I tried to install gran on an Ubuntu Server following the doc here : 
https://dev.grakn.ai/docs/running-grakn/install-and-run?tab=linux#using-debian  

I have an issue with the GPG keyserver:
Executing: /tmp/apt-key-gpghome.lXfhMpw2Ja/gpg.1.sh --keyserver keyserver.ubuntu.com --recv 8F3DA4B5E9AEF44C 
gpg: keyserver receive failed: 

I tried to find the key on the keyserver.ubuntu.com but didn't find it. 

Any idea? 
Regards, 
Math.

**Comment by flyingsilverfin** [comment]
Thanks for reporting! @vmax  maybe you can take a look when you've got a mo?

**Comment by vmax** [comment]
Same as #5887, I believe this was an intermittent issue on Ubuntu's keyserver and is now resolved.
