### ISSUE TITLE
Unexpected results from reasoning when querying a transitive relation, even after commit, until exiting and relaunching console

### ISSUE THREAD

**Issue by VladGan** [vaticle/typedb#5881]
## Description

In the schema, I have 3 types of entities: city, country, continent.
And the rule `t-location`: if A belongs to B, B belongs to C, then A belongs to C.

I do an insert query:
```
insert 
$a isa city, has name "London"; 
$b isa country, has name "Uk"; 
$c isa continent, has name "Europe"; 
$new-location-1 (located: $a, locating: $b) isa t-location;
$new-location-2 (located: $b, locating: $c) isa t-location;
```

after that, I run `commit`

Now, when I run 

`match (located:$a, $b) isa t-location; $a has name $a-name; $b has name $b-name; get $a-name, $b-name;`

It returns incorrect results:
```
{$a-name "Uk" isa name; $b-name "Europe" isa name;}
{$a-name "London" isa name; $b-name "Uk" isa name;}
{$a-name "London" isa name; $b-name "Europe" isa name;}
{$a-name "Uk" isa name; $b-name "London" isa name;}.  <==== there is no (located: Uk, location: London) relation in DB
```

In order to get correct results, I have to quit the console, enter it again, and run the same match query, so it looks like although 'commit' was executed, match queries act like it was not.

Also, it looks like the issue is not reproducible every single time, since I got the correct result once out of ~4 attempts. 

## Environment

grakn console version
1.0.8

grakn server version  
1.8.1

## Additional information

Schema
```
define

name sub attribute, value string;

geo-location sub entity,
abstract,
has name,
plays locating,
plays located;

t-location sub relation,
	relates located,
	relates locating;

transitive-location sub rule,
when {
	(located: $a, locating: $b) isa t-location;
	(located: $b, locating: $c) isa t-location;
},
then {
	(located: $a, locating: $c) isa t-location;
};

city sub geo-location;
country sub geo-location;
continent sub geo-location;
```

Insert query
```
insert 
$a isa city, has name "London"; 
$b isa country, has name "Uk"; 
$c isa continent, has name "Europe"; 
$new-location-1 (located: $a, locating: $b) isa t-location;
$new-location-2 (located: $b, locating: $c) isa t-location;

commit
```

Incorrect match queries: 

```
 match (located:$a, $b) isa t-location; $a has name $a-name; $b has name $b-name; get $a-name, $b-name;
```

```
 match ($a, locating: $b) isa t-location; $a has name $a-name; $b has name $b-name; get $a-name, $b-name;
```

![Screenshot 2020-09-08 at 17 09 31](https://user-images.githubusercontent.com/6169272/92501180-15e80f00-f1f6-11ea-9980-df485d11d900.png)

**Comment by krishnangovindraj** [comment]
This is likely fixed since. Cannot reproduce on 2.14.3
