### ISSUE TITLE
Rules with an inferred variable atom type erroneously commit

### ISSUE THREAD

**Issue by maxbaxt** [vaticle/typedb#5886]
## Description

It would be nice if we could infer the type of an atom as well as its value. However, this will be difficult to implement because it require a lot more from the unifier than it can currently do. However, trying to do this (as this code shows) does commit, but the rule is never used. 

The rule should therefore fail commit, the issue must come from the rule validator.

## Environment

Grakn 1.8.3

## Reproducible Steps

Load the following schema into a Grakn schema:

```
    element sub entity,
    plays first,
    plays second;

    symmetric sub relation,
    relates first,
    relates second;

    symmetry sub rule,
    when {
        $s sub symmetric;
        (first: $a, second: $b) isa $s;
    }, then {
        (first: $b, second: $a) isa $s;
    };
```

## Expected Output

It should fail to load (and give a message about how you need to use a concrete atom type.

## Actual Output

commits successfully, but the rule can never be used.

**Comment by flyingsilverfin** [comment]
This is solved a while ago by checking the `then` of the rule is always insertable, piggy-backing off of type inference.
