### ISSUE TITLE
Grakn install Ubuntu 18.04 NO_PUBKEY 8F3DA4B5E9AEF44C

### ISSUE THREAD

**Issue by faustus25** [vaticle/typedb#5887]
## Description

Cannot install Grakn due to no pub key available

Install instructions:
https://dev.grakn.ai/docs/running-grakn/install-and-run

**_Using APT

As a superuser, add the repo:_**

```
sudo apt install software-properties-common apt-transport-https
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 8F3DA4B5E9AEF44C
sudo add-apt-repository 'deb [ arch=all ] https://repo.grakn.ai/repository/apt/ trusty main'
```

## Environment

Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

## Reproducible Steps
 ```
sudo add-apt-repository 'deb [ arch=all ] https://repo.grakn.ai/repository/apt/ trusty main'
Hit:1 http://ubnrepo.fmr.com/ubuntu18/ubuntu bionic InRelease
Hit:2 http://ubnrepo.fmr.com/ubuntu18/ubuntu bionic-security InRelease
Hit:3 http://ubnrepo.fmr.com/ubuntu18/ubuntu bionic-updates InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Get:5 https://repo.grakn.ai/repository/apt trusty InRelease [1588 B]
Err:5 https://repo.grakn.ai/repository/apt trusty InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8F3DA4B5E9AEF44C
Reading package lists... Done
W: GPG error: https://repo.grakn.ai/repository/apt trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8F3DA4B5E9AEF44C
E: The repository 'https://repo.grakn.ai/repository/apt trusty InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Henkan** [comment]
Try to add the port and protocol to the command, like that:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8F3DA4B5E9AEF44C`.

**Comment by faustus25** [comment]
Did not work either:

`
 sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8F3DA4B5E9AEF44C
Executing: /tmp/apt-key-gpghome.FzKG7Rsq0J/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 8F3DA4B5E9AEF44C
gpg: keyserver receive failed: No keyserver available
`

**Comment by vmax** [comment]
I've just tried fetching the key again and confirmed that it's present and can be fetched. Mostly likely, the Ubuntu's keyserver was down at that time and it is already resolved by them.
