### ISSUE TITLE
Inherit role-playabillity on super-role from its sub-roles

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb#5888]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

When defining a super-relation with sub-relations thereof, the role (relates) of the super-relation should inhert the roles (relates) of all its sub-relations for the playabillity of other entites.

## Current Workaround

The roles for every sub-relation has to be specificly definied as playability.

## Proposed Solution

Allow to inherit the role from sub-relations (if verbose with current behaviour a dedicated command might make sense)

## Additional Information

schema:
![grafik](https://user-images.githubusercontent.com/72193785/94910306-d636df00-04a4-11eb-9dc7-0f4e0e24e879.png)

data:
![grafik](https://user-images.githubusercontent.com/72193785/94910436-02eaf680-04a5-11eb-92a2-086a90c69ad6.png)

error:
The type [price] of role player [V40968416] is not allowed to play Role [parameter-for-funX]
The type [price] of role player [V40968416] is not allowed to play Role [parameter-for-funY]

**Comment by flyingsilverfin** [comment]
The role playability model has solidified in TypeDB/Grakn 2.x, please reopen it if any other issues like this arise :)
