### ISSUE TITLE
Rules interact expectedly, likely caused by false positive in alpha equivalence

### ISSUE THREAD

**Issue by maxbaxt** [vaticle/typedb#5891]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

When two rules have the same conclusion and so can be applied to the same atom, the result of one rule application can mistakenly affect or substitute the other. This occurs when the rule bodies are similar but have a real difference, and likely caused because the program incorrectly identifies the rules as alpha equivalence.

## Environment

Grakn core

## Reproducible Steps

Start and local Grakn server and then load the following schema into it:

```
define

person sub entity,
plays member,
plays host,
plays attendee,
plays speaker,
has tag,
has name;

party sub relation,
relates member,
relates host;

conference sub relation,
relates attendee,
relates speaker;

tag sub attribute,
value string;

name sub attribute,
value string;

rule-1 sub rule,
when {
    (attendee: $x, speaker: $y) isa conference;
    (member: $x, member: $y, host: $y) isa party;
}, then {
    $y has tag "P";
};

rule-2 sub rule,
when {
    (attendee: $x, speaker: $y) isa conference;
    (member: $x, member: $y, host: $x) isa party;
}, then {
    $y has tag "P";
};


insert
    $bob isa person, has name "bob";
    $alice isa person, has name "alice";
    $charlie isa person, has name "charlie";
    $dennis isa person, has name "dennis";

    (attendee: $bob, speaker: $alice) isa conference;
    (member: $alice, member: $bob, host: $alice) isa party;

    
    (attendee: $charlie, speaker: $dennis) isa conference;
    (member: $charlie, member: $dennis, host: $charlie) isa party;
```

Now enter the console and run the following match:
```
match $x isa person, has name $n, has tag "P"; get;
```

## Expected Output

Alice fulfils rule-1, and Dennis fulfils rule-2. Therefore, we should return both Alice and Dennis.

## Actual Output

Only Dennis is returned.
 
## Additional information

We also ran this with rule-1 and rule-2 having different conclusions. This resulted in the expected behaviour. Therefore this bug can only be reproduced with the rules interacting, not in isolation.

This test was designed to create an instance of such interaction between similar rule bodies. If it is indeed caused by alpha equivalence, it is likely this occurs elsewhere and fairly frequented. Therefore resolving it is quite important.

**Comment by dmitrii-ubskii** [comment]
The output is as expected as of TypeDB 2.14.3.
Updated schema:
```typeql
define

person sub entity,
  plays party:member,
  plays party:host,
  plays conference:attendee,
  plays conference:speaker,
  owns tag,
  owns name;

party sub relation,
  relates member,
  relates host;

conference sub relation,
  relates attendee,
  relates speaker;

tag sub attribute, value string;
name sub attribute, value string;

rule rule1:
when {
    (attendee: $x, speaker: $y) isa conference;
    (member: $x, member: $y, host: $y) isa party;
} then {
    $y has tag "P";
};

rule rule-2:
when {
    (attendee: $x, speaker: $y) isa conference;
    (member: $x, member: $y, host: $x) isa party;
} then {
    $y has tag "P";
};
```
