### ISSUE TITLE
It takes a long time to compute the shortest path with client-python

### ISSUE THREAD

**Issue by YishuiLi** [vaticle/typedb#5893]
## Description

It takes a long time to compute the shortest path with client-python.

## Environment

1. OS (where Grakn server runs): CentOS 7
2. Grakn version (and platform): Grakn Core 1.8.3 (using docker)
3. Grakn client: client-python
4. Other environment details: 
    CPU: 4cores*4sockets
    memory: 24GB

## Reproducible Steps

1. migrate BioGrakn Covid data source
2. use client-python, compute the shortest path between the two disease instances with ids of V301817928 and V152633472: 
    compute path from V301817928, to V152633472;

## Actual Output

It takes 1400s to return the result. How to speed up the query?

When using client-python to execute three compute queries at the same time, causes DriverTimeoutException
![image](https://user-images.githubusercontent.com/16732930/97111795-b305f500-171b-11eb-925b-e04de12881b7.png)

**Comment by dmitrii-ubskii** [comment]
Closing as invalid as the shortest path functionality has been removed from TypeDB and isn't planned in the near future.
