### ISSUE TITLE
Bazel build does not work in Mac environment unless RPM is not installed

### ISSUE THREAD

**Issue by maxbaxt** [vaticle/typedb#5896]
## Description

Running `bazel build //....` fails with the following error is RPM is not installed on the machine:

```
__main__.InvalidRpmbuildError: /usr/local/bin/rpmbuild is not executable
```

## Environment

1. OS (where Grakn server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. Grakn version (and platform): Grakn Core 1.8
3. Other environment details: RPM is not installed
 
## Current Workaround

This can be overcome by installed RPM, for instance by running `brew install rpm`.

**Comment by vmax** [comment]
As we no longer provide RPM packages, this is not an issue anymore.
