### ISSUE TITLE
Unknown error when trying to form 3-player relation with rule

### ISSUE THREAD

**Issue by hmprt** [vaticle/typedb#5899]
Environment: Grakn Core 1.8.4 on Mac OS 10.14.6
             (using client-python though can reproduce error in Grakn Console as below)

Goal: Trying to infer a 3-player relationship between subject, object and verb (or predicate) given dependency and part-of-speech tags modelled as token attributes.

Steps to reproduce:

1) Load schema:

  grakn console -k debug -f debug.gql

2) Insert data:

  grakn console -k debug

  insert $t0 isa token, has doc_index 0, has dependency "nsubj", has text "John", has head_token_index 1; $t1 isa token, has doc_index 1, has part_of_speech "VERB", has text "saw"; $t2 isa token, has doc_index 2, has dependency "dobj", has text "Jim", has head_token_index 1;

  commit

3) Try to match relation derived through rule:

  input query:

    match $r isa simple-ternary-relation; get;

  expected output:

    {$r id Vxxxx isa simple-ternary-relation}

  actual output:

    Error: UNKNOWN: grakn.core.kb.graql.reasoner.ReasonerException: Invalid state in variable predicate [[$subject_head == $verb_head]] with answer [[$1605031742582800/V8248][$1605031742582804/V8200][$1605031742582808/V4256][$object/V8336][$object_head/V4152][$subject/V4120][$subject_head/V4152][$verb/V16440][$verb_index/V4096]]: either a concept is missing or not an attribute.. Please check server logs for the stack trace.
    All uncommitted data is cleared

**Comment by flyingsilverfin** [comment]
hi @hmprt  we're in the process of validating known 1.8 bugs vs Grakn 2.0 -- can you provide the `debug.gql` file for the schema that helped reproduce this issue please?

**Comment by haikalpribadi** [comment]
Hi @hmprt, sorry for the late response on this issue! Was busy working on 2.0 release at the end of last year. I know this issue no longer exists in Grakn 2.0.0-alpha. Have you got a chance to upgrade to latest Grakn? Unfortunately we won't be able to fix any issues in Grakn 1.8.X (and earlier) anymore at this point. But we'll make sure to confirm this bug no longer exists in 2.0.

If you can share the schema you loaded into Grakn 1.8, that would be really helpful!

**Comment by flyingsilverfin** [comment]
@hmprt if this issue persists in the 2.0 version, please open another issue! Closing for now as active development of 1.x has ended.
