### ISSUE TITLE
Re-enable copying attributes by value using reasoner arithemetic

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#5912]
## Problem to Solve

As detailed in issue https://github.com/graknlabs/grakn/issues/5809, attribute attachment using a copy-by-value is incoherent with Graql.

## Proposed Solution

The most correct solution we have is to introduce a clause in rules that is able to:
- manipulate attribute values
- create new attribute instances based on those values

Example, using purely hypothetical syntax:
```
born-in-location-implies-residency-date sub rule,
  when {
    $bi(born-in_place-of-birth: $location, born-in_child: $person) isa born-in;
    $person isa person, has date-of-birth $dob;
    $r(residency_resident: $person, residency_location: $location) isa residency;
  }, compute into start-date $sd {
    $sd = $dob;
  }, then {
    $r has $sd;
  };
```

**Comment by flyingsilverfin** [comment]
Closing since #6654  was merged and released :)
