### ISSUE TITLE
Core 1.8: export use multiple transactions per type

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6000]
## Description
Currently, in Core 1.8.4, the data export feature uses a single transaction per schema Type. This means that if there are many instances of a particular type, a single very large and long lived transaction could end up making the system OOM. However, this is not confirmed, and would be a JanusGraph errror.

## Environment
Grakn Core 1.8.4, any platform.

## Reproducible Steps
Run an export with a large number of data points ( > 20k) for a single type.

Then, on command line, run:
```
./grakn server export my_keyspace dump.grakn
```

## Expected Output

Successful export

## Actual Output
JanusGraph error, such as `EdgeStoreQuery` exceptions.

**Comment by haikalpribadi** [comment]
This issue can be of high priority if there is anyone blocked on their migration because of this issue. But I can't confirm that's the case.

**Comment by flyingsilverfin** [comment]
In TypeDB 2.8.0 we can be sure there are no OOM's during pure read transactions, so this is a non-issue
