### ISSUE TITLE
TypeDB process hangs if the computer goes to hibernation 

### ISSUE THREAD

**Issue by VladGan** [vaticle/typedb#6030]
## Description

I started grakn server from the IntelliJ terminal using this command: 
`bazel run //server:server-bin-mac`

Then I left it for the night and closed the computer.

The next day bazel command was killed in the terminal, but the grakn process was still running.

Trying to reproduce the issue by leaving Mac closed for a couple of minutes while grakn is running did not succeed.

## Environment

1. OS (where Grakn server runs): macOS Catalina 10.15
2. Grakn version (and platform): `3bf66c6462f09e41adee452a7b4a6b4dde752450`
3. Grakn client: console `577f4a3fd4454c1f88c82d2be5a924d61571e80f`

## Expected Output

Grakn process should not hang for no apparent reason.  If the parent `bazel` process is killed, the grakn process should also be killed, since it is a child of the bazel process (the same way they are both killed on Ctrl+c).  

## Actual Output

Grakn process hangs and can be seen using `jps` command.

**Comment by dmitrii-ubskii** [comment]
Killing the parent bazel process by any means (SIGTERM, SIGKILL, ^C, closing the terminal) reliably kills TypeDB server. I have not encountered an issue with hibernation either. Closing as not reproducible.
