### ISSUE TITLE
Enable Reasoner in Data Write Transactions

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6076]
## Problem to Solve
Currently, reasoning is only enabled in read transactions (schema or data). We should carefully reconsider how to enable reasoning in data write transactions.

## Current Workaround
Open a data read transactions for each reasoning query that needs to be performed.

## Proposed Solution
Data write transactions could support reasoning, with the following requirements
1. we need to correctly invalidate inferred facts or reasoning queries that are running and depend on data that is being deleted (or inserted, if negation is present)
2. we also need to correctly resolution actor states in the data delete/insert scenarios
3. consider semantics of inserting an inferred fact, or facts depending on inferred concepts, as well as the semantics of deleting an inferred concept that may appear again in the next query (unintuitive)4. 

## Additional Information
Write transactions are currently do not support reasoning, see https://github.com/graknlabs/grakn/pull/6068

**Comment by haikalpribadi** [comment]
So this goes post-production @flyingsilverfin ?

**Comment by flyingsilverfin** [comment]
yes @haikalpribadi

**Comment by dmitrii-ubskii** [comment]
Closed as not planned
