### ISSUE TITLE
Migrate forward-chaining oracle for BDD resolution testing from 1.8

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6103]
## Problem to Solve
Currently, we have a package `//test/behaviour/resolution/framework` that must be ported from 1.8, and implemented to allow mirroring a backward-chained database with a fully materialised forward-chained one.

We will try to break down the work into two parts:
1. implement forward-chaining, so we can check the total number of answers in forward chaining, and using regular reasoning is the same
2. implement explanation-based answer checking, to ensure that the explanations for answers return a valid line of reasoning.

## Current Workaround
N/A, just using hand-written test outputs to verify reasoning answers, instead of the forward-chaining oracle.

## Proposed Solution
* implement forward-chaining oracle, and test explanations against forward-chaining resolution paths.

## Additional Information
* part 2, checking answers based on explanations, will have to be done later than part 1.

**Comment by jmsfltchr** [comment]
This split makes sense, we should go ahead and do it since part 1 is already a very useful test!

**Comment by jmsfltchr** [comment]
Completed as of some time ago!
