### ISSUE TITLE
Difficult to read RocksDB error when loading high number of queries per commit

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb#6105]
## Description

I try to load data with a high number of queries per commit, but get an error that is difficult to read.

## Environment

1. OS: Mac OS 10.14
2. Grakn version: Grakn Core on commit graknlabs/grakn@eae2568
3. Grakn client-python version: client-python 2.0.0-alpha-5
4. Python version: 3.9

## Reproducible Steps

1. Clone and run Grakn on commit: graknlabs/grakn@eae2568
2. Go to this repository: https://github.com/graknlabs/biograkn-covid
3. On this branch: biograkn_benchmarking_2
4. In `migrator.py` set `ctn = 700` and run on a running Grakn
5. And then at some point you get a RocksDB Exception

## Actual Output
 
```
grakn.common.exception.GraknClientException: org.rocksdb.RocksDBException: Transaction could not check for conflicts for operation at SequenceNumber 3068083 as the MemTable only contains changes newer than SequenceNumber 3948411.  Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error. Please check server logs for the stack trace.
```

## Additional information

![image](https://user-images.githubusercontent.com/20223184/106196801-ca84cc00-61a9-11eb-890f-62325125e4ea.png)

**Comment by haikalpribadi** [comment]
I think this may come down to providing useful error message for when the user has too many queries in their transaction.

**Comment by krishnangovindraj** [comment]
Checked with @flyingsilverfin : "now that we implement Isolation at the TypeDB layer we don't have this issue anymore"
