### ISSUE TITLE
Segfaults in session cleanup fixed by temporary sleep

### ISSUE THREAD

**Issue by Phillammon** [vaticle/typedb#6135]
Client-python tests invoke segfault in grakn-core 2.0. Can be repaired by adding 0.01 second sleep prior to performing session cleanup.

Bandaged by https://github.com/graknlabs/client-python/pull/177/commits/0b810a680ddc77a8a0401b24823e0ef264bed19c in client-python

**Comment by dmitrii-ubskii** [comment]
Resolved as of 2.14.3
