### ISSUE TITLE
Add more verifications in statistics test

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#6138]
Improve statistics tests to perform the following:

- assert that concept count is correct even when concepts are inserted in parallel, for entities, attributes, and relations
- assert that has edge count and relation count correctly filters out inferred has edges and relations

**Comment by lolski** [comment]
I'm assigning it to priority high since incorrect statistics will cause query planner to work suboptimally.

**Comment by flyingsilverfin** [comment]
Implemented in #6527
