### ISSUE TITLE
Undefining a rule that infers a type does not allow that type to be undefined

### ISSUE THREAD

**Issue by Phillammon** [vaticle/typedb#6150]
## Description

Undefining a rule does not properly update type references of types of concept it could legally infer, meaning that a type cannot be subsequently undefined, even if that rule was the only thing referencing that type in any way.

## Reproducible Steps

Can be reproduced via docs tests, specifically test job `graql-lang-test`, even more specifically `test__09_schema__01_concepts__graql_native__23`

## Expected Output

The type "fluency" is deleted, as nothing in the schema still references it and no concepts have that type.

## Actual Output

```grakn.client.common.exception.GraknClientException: [TYW05] Invalid Type Write: The type 'fluency' is referenced in rules '[grakn.core.graph.structure.impl.RuleStructureImpl$Persisted@6854043e]', and cannot be deleted. Please check server logs for the stack trace.```

**Comment by krishnangovindraj** [comment]
This has since been fixed. Tested on 2.14.3
