### ISSUE TITLE
Traversal Engine Graph Combinator

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb#6194]
## Problem to Solve

The type-resolver performance is becoming a detrimental problem to the query engine. For larger "multi-hop" queries, such queries with 7 relationships or higher (that are quite common), the type-resolver may cause a significant slow-down if the schema it touches is diverse/complex. But this behaviour is not expected; the slow-down is caused by the _"permutative"_ nature of traversal engine answers that type resolver depends on. But this is the wrong behaviour designed into type resolvers algorithm.

The fundamental problem with type-resolver is that it is not actually a traditional "graph traversal" in which most user queries are expected to be. The goal of the type-resolver algorithm, is to find "all possible (type) vertices that can form a valid query". Which means, it is actually looking for _"all valid **combinations** of vertices"_ that can satisfy a given query, **as opposed to** all valid **"permutations"** of vertices that can satisfy a given query. This problem is actually a variant of the [_"connected-components"_](https://en.wikipedia.org/wiki/Component_(graph_theory)) graph clustering problem, where the exception is that we need to map a vertex in the query to a set of vertices in the answer.

## Current Workaround

None.

## Proposed Solution

We should not have used `GraphIterator` engine to implement type-resolver algorithm. We should implement a _"graph combinator"_ algorithm, specifically for type-resolver. In a big graph, we should implement it in a [Pregel](https://blog.acolyer.org/2015/05/26/pregel-a-system-for-large-scale-graph-processing/)/[BSP](https://en.wikipedia.org/wiki/Bulk_synchronous_parallel) style algorithm. But in a small graph such as the schema graph in which the type-resolver operates on (only once for all queries with the same schema structure!), we just need to do a simple DFS!!! And the DFS is NOT equal to `GraphIterator` algorithm - `GraphIterator` is a permutation algorithm! The type-resolver is only a combination problem, so we just need to implement a "graph combinator" DFS algorithm in the `TraversalEngine`.

## Additional Information

This feature will solve all the type-resolver performance issues that we see among our users, including those are captured in issue https://github.com/graknlabs/grakn/issues/6155, https://github.com/graknlabs/grakn/issues/6161, and https://github.com/graknlabs/grakn/issues/6183.

**Comment by lriuui0x0** [comment]
@haikalpribadi I don't have context on this one, why do we care about combination instead of permutation?

**Comment by haikalpribadi** [comment]
Yes this is high on our list this right now @thomaschristopherking thanks for sharing!

**Comment by thomaschristopherking** [comment]
hi, @haikalpribadi @flyingsilverfin  I noticed that the most recent release doesn't address this feature, as far as I know. Is this likely to come soon/is there any update on this one?

**Comment by haikalpribadi** [comment]
I believe this is next on @flyingsilverfin list of priorities, @thomaschristopherking. So I think it's fair to say it's highly likely to come out int the next release if there isn't any drastic blocker.

**Comment by flyingsilverfin** [comment]
@thomaschristopherking we're starting to design this now and get to work on the implementation. Given that the vacations are peppered around august it's unlikely to get done for some more weeks :)

**Comment by flyingsilverfin** [comment]
Solved with #6431 !!
