### ISSUE TITLE
Deleting 1m relations results in Grakn being killed

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb#6237]
## Description

When I try to delete over 1m relations Grakn dies. 

## Environment

OS (where Grakn server runs): On Azure with Ubuntu 18.04
Grakn version (and platform): Grakn Core Alpha 8
Grakn client: Console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download biograkn-covid from master (commit 44381f6) and put it on an Azure machine
2. Run migrator.py (to speed up the loading relevant to this bug, you can uncomment all the loaders in that file, except for `insertSchema`, `uniprotMigrate` and `proteinAtlasMigrator`)
3. After loading, run `match $p isa expression; delete $p isa expression; ` in the console. This will lead Grakn to be killed. 

## Expected Output

Deletion of relations. 

## Actual Output

In the console I get: `[CLI02] Illegal Client Operation: Unable to connect to Grakn server.`
The Grakn server is killed

## Additional information

![image](https://user-images.githubusercontent.com/20223184/110004406-50e37f00-7d0f-11eb-9afb-7b3624c5ca85.png)
![image](https://user-images.githubusercontent.com/20223184/110004417-54770600-7d0f-11eb-98b7-48d24d8d75b6.png)

**Comment by haikalpribadi** [comment]
Can you retest this using latest `master`? We may have already fixed this.

**Comment by flyingsilverfin** [comment]
this was probably an OOM and addressed by https://github.com/vaticle/typedb/pull/6324 , if not fixed previously. Closing, but can be re-opened if still an issue
