### ISSUE TITLE
Update error message from internal to user facing: Invalid concept conversion from 'EntityTypeImpl' to 'AttributeType'

### ISSUE THREAD

**Issue by daniel-crowe** [vaticle/typedb#6248]
## Description

Error message given by Grakn when defining the below schema should be updated to be more user friendly. 
 
## Environment
1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 2.0-alpha-9
3. Grakn client: console

## Reproducible Steps
Attempting to define the following schema: 
`define
organisation sub entity,
owns country;
country sub entity;
`
## Expected Output

###Return error message: 
#### Generic: 
`Invalid Type Read: Type <my-schema-type> isa <schema-type> and cannot be owned by a concept type.`

#### Specific: 
`Invalid Type Read: Type 'country' isa entity and cannot be owned by a concept type.`

## Actual Output

Returns error message: 
`Invalid Type Read: The type 'dept_name' does not exist.`

**Comment by haikalpribadi** [comment]
Thanks for the bug report @daniel-crowe, don't forget to remove they curly brackets in the issue template.

With regards to the "Actual Output" above, does it actually say "dept_name"? That term does not exist in the short schema you wrote in the reproducible steps above.

**Comment by alexjpwalker** [comment]
@daniel-crowe Which of the error messages do we get - the message in the issue title (Invalid concept conversion), or the message in the issue body (Invalid type read)?

**Comment by daniel-crowe** [comment]
@flyingsilverfin @alexjpwalker here's the error message in the latest TypeDB version: `[TYR01] Invalid Type Read: Invalid concept conversion from 'EntityTypeImpl' to 'AttributeType'. Please check server logs for the stack trace.`

**Comment by flyingsilverfin** [comment]
Closed with #6347
