### ISSUE TITLE
Compress encoding prefixes

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb#6258]
## Problem to Solve

Grakn's encoding prefix uses a single byte of storage, restricting it to the range [0..255]. So far, we are using 0 for `INDEX_TYPE`, 50 for `STATISTICS_THINGS`, 100 for `VERTEX_THING_TYPE`, 180 for `VERTEX_ROLE`, 190 for `STRUCTURE_RULE`. 200 and above are reserved for Grakn Cluster.

This is not good. There's almost no space left to play with, which heavily constricts our ability to cleanly add new functionalities to Grakn in the future. Every time we _move_ an existing encoding to a new number, every existing Grakn database will lose compatibility with all future releases of Grakn.

## Proposed Solution

We should compress down the encoding prefixes to free up space while Grakn Core remains in alpha.

**Comment by flyingsilverfin** [comment]
We compressed encoding prefixes in TypeDB 2.6.0, and reserved a larger range for Cluster to use for prefixes
