### ISSUE TITLE
Grakn console throws up errors when starting it

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb#6261]
## Description

When you enter Grakn console, it throws up several log errors. 

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Grakn client: Console
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn
2. Go into console with `./grakn console`
3. See error

## Actual Output

![image](https://user-images.githubusercontent.com/20223184/111676355-fae5ff80-8815-11eb-9e6a-dd9da454a488.png)

**Comment by haikalpribadi** [comment]
I think this is related to our change of the logback file names, @lolski . Let's look into this together tomorrow.

**Comment by flyingsilverfin** [comment]
Resolved in 2.0.0 production release
