### ISSUE TITLE
Migrator in biograkn-covid not working

### ISSUE THREAD

**Issue by Omar12399** [vaticle/typedb#6262]
## Description

Migrator in biograkn-covid is not working for me.

## Environment

1. OS: Windows 10 and Ubuntu
2. Grakn version: Grakn core 2.0 and Biograkn-covid 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. start grakn server
2. migrator: lower ctn to 20 (also tried default at 500)
3. migrator: comment out coronavirusMigrator and cord_ner_migrator (also tried leaving on)
3. run migrator

## Expected Output

Migrator completed without errors.

## Actual Output

On Windows 10: issues with specific databases: dgidbMigrator and proteinAtlasMigrator
UnicodeDecodeError for DGIdb
PermissionError for Human Protein Atlas

On Ubuntu: no issues with those databases but instead error after:
Migrate 'Subject_CORD_NER.csv'
Sending API call to fetch articles Metadata
--------Loading journals---------
See screenshot below.
 
## Additional information

![image](https://user-images.githubusercontent.com/80971019/111804787-afdcf280-88d0-11eb-958c-9ed8327ad850.png)

**Comment by alexjpwalker** [comment]
Is this the issue that was reported in Discord and didn't have any associated error logs in the server logs, @Omar12399 ?

**Comment by dmitrii-ubskii** [comment]
Resolved by https://github.com/typedb-osi/typedb-bio/pull/28
