### ISSUE TITLE
Restarting the server after an exception violates RocksDB assertion

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb#6268]
## Description

After a client runs an insert query which refers to a type that does not exist, an exception is thrown on the client side, and an error is logged on the server side. If we decide to shutdown the server now, then restart it again, we get an assertion error from RocksDB:
```
Assertion failed: (valid_), function key, file ./db/db_iter.h, line 152.
```

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 2.0.0-alpha-9
3. Grakn client: client-java
4. Other environment details: NA

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn server
2. Load schema with type A: `define a sub entity;`
3. Insert entity with random type: `insert $x isa b;`
4. Shutdown server
5. Start server
6. See error:
```
Assertion failed: (valid_), function key, file ./db/db_iter.h, line 152.
```

## Expected Output

Server boots up fine.

## Actual Output

```
Assertion failed: (valid_), function key, file ./db/db_iter.h, line 152.
```
 
## Additional information

This occurred when loading `graknlabs/biograkn-semmed@master` into `haikalpribadi/grakn@rocksdb-write-throughput` with a migrator logic that tried to insert an attribute with a type that does not exist.

**Comment by flyingsilverfin** [comment]
This has been solved, the cause was that we were using iterator over 0 values in RocksDB without checking it was valid first!
