### ISSUE TITLE
Vulnerabilities in Grakn v2.0.2

### ISSUE THREAD

**Issue by Duckduckflo** [vaticle/typedb#6301]
Hello, we are using Grakn container graknlabs/grakn:2.0.2 and as part of our CI/CD pipeline we scan all container images using Sysdig Secure. Sysdig reports all vulnerabilities in images as well as providing fix information where it exists. It has informed us that for graknlabs/grakn:2.0.2 there are two patchable packages:
 - guava-23.0 (java)
 - mercurial-4.8.2 (python)
Guava (package path: /opt/grakn-cluster-all-linux/console/lib/com-google-guava-guava-23-0.jar:guava) vulnerability (fixed in 23.6.1) description is: Google Guava contains a flaw in the AtomicDoubleArray::readObject() function in com/google/common/util/concurrent/AtomicDoubleArray.java that is triggered when deserializing Java objects. With specially crafted serialized data, a context-dependent can cause a process linked against the library to exhaust available memory.
Mercurial (package path: /usr/lib/python2.7/dist-packages/mercurial) vulnerability (fixed in 4.9) description is: Mercurial contains a flaw that is triggered during the handling of symlinks and subrepositories. This may allow a local attacker to bypass the program's path-checking logic and write files outside of a directory.
Do you please know if these vulnerabilities have been mitigated, and if so could you please share literature on why? If they aren't mitigated, do you please know if there is a plan/roadmap to updating to patched versions? Thanks.

**Comment by flyingsilverfin** [comment]
These dependencies don't exist or have been upgraded.
