### ISSUE TITLE
Seemingly non-terminating query with limit 1 and parallelism

### ISSUE THREAD

**Issue by thomaschristopherking** [vaticle/typedb#6305]
## Description

Executing the following query via the console client causes the execution to seemingly never terminate. This is when parallel is 'True'. However, setting parallel to False or removing the limit 1 on the end of the query does not cause this issue.

## Environment

1. Windows 10 or Ubuntu 20.
2. Grakn Core 2.0.2
3. Console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load the schema [response_template.txt](https://github.com/vaticle/typedb/files/6399754/response_template.txt)
2. Execute the following query in the console with parallel set to True:

    `match $response_template isa response_template, has topic "smalltalk", has intent "happy_holidays", has identifier $id, has attribute $data; {$response_template has portfolio_id "101";} or {not {$response_template has portfolio_id $pid;}; }; limit 1;`

3. The execution doesn't seem to terminate. You might also need to restart your db and possibly your system.

## Expected Output

The query terminates.

## Actual Output

The query does not terminate. However, there are no noticeable memory or CPU spikes either.

**Comment by flyingsilverfin** [comment]
Heya - this isn't reproducible following your steps, first of all there's no data, and also the query throws this error:
`[TYR03] Invalid Type Read: The type 'person' does not exist. Please check server logs for the stack trace.`

Also there should be a `limit 1` on your query?

**Comment by thomaschristopherking** [comment]
Hi, I've copied the correct query in from our earlier chat (the other one was from one of the other bugs). The lack of data is intentional, this issue occurs without any data (and also with).

I've just crashed my db again to confirm.

**Comment by flyingsilverfin** [comment]
Fix is implemented in https://github.com/vaticle/typedb/pull/6314
