### ISSUE TITLE
Error during import of data from exported db

### ISSUE THREAD

**Issue by nicolamassarenti** [vaticle/typedb#6310]
Hi,

This issue is because of an error we are encountering with import/export from Linux Ubuntu 20.04 to Windows 10.

## Environment

1. OS: Linux Ubuntu 20.04, Windows 10
2. Grakn version: `Grakn 2.0.2`

## Details
When exporting, the server printed the following log:
`Exported 1726 entities, 1584 attributes, 8099 relations (20098 roles), 6810 ownerships`

The schema is:
```
define

lemma sub attribute,
    value string;

name sub attribute,
    value string;

relation-type sub attribute,
    value string;

sentiment sub attribute,
    value string;

text sub attribute,
    value string;

token-type sub attribute,
    value string;

category sub relation,
    relates sub-category,
    relates super-category;

class sub relation,
    relates sub-class,
    relates super-class;

containing sub relation,
    relates contained,
    relates container;

element sub relation,
    relates sub-element,
    relates super-element;

instance sub relation,
    relates sub-instance,
    relates super-instance;

mined-relation sub relation,
    owns relation-type,
    relates child,
    relates contained,
    relates head;

property sub relation,
    relates sub-property,
    relates super-property;

synthesis sub relation,
    relates express,
    relates synthesize;

chapter sub entity,
    owns name,
    plays category:super-category,
    plays class:sub-class;

characteristic sub entity,
    owns name,
    plays property:sub-property;

concept sub entity,
    owns name,
    plays element:super-element,
    plays instance:sub-instance;

document sub entity,
    owns name,
    plays class:super-class;

object sub entity,
    owns name,
    plays element:sub-element,
    plays property:super-property,
    plays synthesis:synthesize;

paragraph sub entity,
    owns name,
    plays category:sub-category,
    plays containing:container,
    plays instance:super-instance;

sentence sub entity,
    owns sentiment,
    owns text,
    plays containing:contained,
    plays containing:container,
    plays mined-relation:contained,
    plays synthesis:express;

token sub entity,
    owns lemma,
    owns token-type,
    plays containing:contained,
    plays mined-relation:child,
    plays mined-relation:head;

```

The schema is imported and exported with no problems.

I exported (from Ubuntu) the data command `grakn server export <DB_NAME> data.grakn`.

My colleague imported the data with command `grakn server import <DB_NAME> data.grakn` and got some errors. We repeted the import and got different errors. They are shown in the pictures below:

![image](https://user-images.githubusercontent.com/38035878/117001937-3ca60900-ace3-11eb-9850-76544c4cf8e7.png)

![image](https://user-images.githubusercontent.com/38035878/117002003-4e87ac00-ace3-11eb-8c87-dff011afb0bd.png)

and the following is the error shown in the promt with the import command:
<img width="952" alt="Immagine 2021-05-04 124831" src="https://user-images.githubusercontent.com/38035878/117002055-5fd0b880-ace3-11eb-9aed-d2e3e8507ccf.png">

It may be useful to know that with a different version of the db with same schema but different data we were able to import the data.

Why do we have these errors? Is this a bug of the import module?

Thanks.

**Comment by nicolamassarenti** [comment]
Update: we were able to import the data+schema by copying my folder located in `/opt/grakn/core/server/data/<DB_NAME>`, then pasting it in the grakn data folder in Windows.

Since this process has worked, I believe that there is a bug in the import module.

**Comment by flyingsilverfin** [comment]
Oh this is a super useful issue!! thank you -- is there any chance you can also upload the original database (distribution) for us to investigate with?

**Comment by nicolamassarenti** [comment]
Hi @flyingsilverfin,

unfortunately for privacy reasons we cannot share the content (data) of the database. 

If it helps, we previously had a simpler version of the schema: it was the same but without `containing`, `mined-relation` and `synthetize` relations, without `sentences` and `tokens` entities. With that version of the database we were able to import it (with command `grakn server import <DB_NAME> data.grakn`) from one computer to another. 

Hope it helps!

Best,
Nicola

**Comment by flyingsilverfin** [comment]
It would really be a huge help if we could fix this issue for our wider community, since it has only been seen rarely! If we get an NDA signed would that be helpful? We can arrange that...

Alternatively, if you mind spending 5 mins on this, maybe you can create a copy of the database (copy-paste the `data/db-name` directory into a new name in the same location `data/db-clone`), and then using a delete query to delete all the attributes? This way only the entities and relations and no actual "datapoints" are kept which you can send us? Hopefully this version of the database also has the same import issue :)

**Comment by nicolamassarenti** [comment]
Hi @flyingsilverfin,

your second idea works for us. I've managed to delete all the attributes. In the _.zip_ attached there is both the data exported in the _*.grakn_ file and the copy of the db folder.

Hope this helps! 
Let me know! 

[grakn_issue_db_no_attributes.zip](https://github.com/vaticle/typedb/files/6435301/grakn_issue_db_no_attributes.zip)
