### ISSUE TITLE
the command `brew tap vaticle/tap` leads to an error

### ISSUE THREAD

**Issue by JonThom** [vaticle/typedb#6335]
## Description

the command `brew tap vaticle/tap` leads to an error

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform): TypeDB 2.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run `brew tap vaticle/tap`

## Expected Output

set up vaticle tap

## Actual Output

```
brew tap vaticle/tap
````
> ==> Tapping vaticle/tap
> Cloning into '/usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap'...
> remote: Enumerating objects: 307, done.
> remote: Counting objects: 100% (203/203), done.
> remote: Compressing objects: 100% (131/131), done.
> remote: Total 307 (delta 51), reused 182 (delta 31), pack-reused 104
> Receiving objects: 100% (307/307), 44.61 KiB | 1015.00 KiB/s, done.
> Resolving deltas: 100% (81/81), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap/Formula/typedb.rb
> No available formula with the name "typedb".
> In formula file: /usr/local/Homebrew/Library/Taps/vaticle/homebrew-tap/Formula/typedb.rb
> Expected to find class Typedb, but only found: TypeDB.
> Error: Cannot tap vaticle/tap: invalid syntax in tap!

**Comment by vmax** [comment]
@JonThom could you try that again? I want to understand if my fix in https://github.com/vaticle/homebrew-tap/commit/d285c4c0a70b982631adb8402c86d4c6c77acc8f worked

**Comment by JonThom** [comment]
@vmax just ran  
```
brew tap vaticle/tap 
brew install vaticle/tap/typedb
``` 
and it worked - great!
