### ISSUE TITLE
Variable Roles Feature is flakey

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6355]
## Description

The tests for variable roles sometimes break and are not being run in CI for this reason. The cause is presently unknown.

## Environment

1. OS (where TypeDB server runs): Grabl
2. TypeDB version (and platform): TypeDB 2.1.2
3. TypeDB client: BDD feature (client-java)

## Reproducible Steps

Steps to create the smallest reproducible scenario:

- Enable the test feature and re-run multiple times

**Comment by dmitrii-ubskii** [comment]
Enabled and green as of 2.14.3: https://github.com/vaticle/typedb/blob/2.14.3/.factory/automation.yml#L106
