### ISSUE TITLE
Improve reasoner resolvable planning

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6358]
## Problem to Solve

Reasoner's current planning can end up in combinatorial states that have to be worked around (sometimes unsuccessfully). To improve this, we should use a statistics-driven planning, similar to traversal planning, to order choose which order to execute resolvables (components of a reasoning conjunction).

Currently, we just maximise the number of bound variables we are given, choosing retrievables over concludables, and then try to optimise hitting the cache as much as possible.

## Current Workaround

You can't tweak the planner manually, but you can tweak your query by adding/removing some additional constraints to force different plans to appear.

## Proposed Solution

Implement a cost-based planning.

High level ideas already discussed:
* can use the traversal optimiser's value as the cost of a retrievable
* a concludable can be costed by breaking down into rules recursively up to a limited depth (say 3). Fundamentally everything must end as a retrievable! Aggregate those costs into a final cost in the concludable plus the retrieval cost of the concludable
* we may want to try to estimate the number of answers a resolvabel will produce because this can act as a multiplier over the number of messages/subsequent lookups that are performed. The answer size estimate plus bindings to the next resolvable affect the cost of the next resolvable: 1 set of bindings might lead to N answers, but there are M bindings so the cost is M*C and answers is M*N
* we should include negations as part of the planning (eg. doing negations just at the end doesn't make much sense, consider `match $x isa ...; ($x)...; not { $x iid 0x123; };`

It may be enough to start with to only improve retrievable planning. However, we would still have to solve the problem of how to carry costs across retrievables/figure out the aggregated cost function and how to optimise it, so we should probably just solve it all in one shot.

**Comment by dmitrii-ubskii** [comment]
Resolved by #6656
