### ISSUE TITLE
Reasoner doesn't infer collaborator

### ISSUE THREAD

**Issue by lriuui0x0** [vaticle/typedb#6365]
Please find data at https://www.dropbox.com/home/Engineering/Reasoner?preview=data.tar.gz

You can run the following query, and returns result:

```
match $u isa user, has name "alexjpwalker"; $t isa team, has name "Engineers" ; $r isa repository, has symbol "vaticle/web-docs" ; ($u, $t) isa team-member ; ($r, $t) isa repo-team ;
```

Grabl has the following rule:

```
rule repo-collaborator-team-rule:
    when {
        (repo: $x, team: $y) isa repo-team;
        (team: $y, member: $z) isa team-member;
    }
    then {
        (repo: $x, collaborator: $z) isa repo-collaborator;
    };
```

Yet the following query doesn't return result:

```
match $u isa user, has name "alexjpwalker" ; $r isa repository, has symbol "vaticle/web-docs"; ($u, $r) isa repo-collaborator ;
```

**Comment by lolski** [comment]
Closing the issue because it's invalid.

The issue occurred during troubleshooting and was caused by not enabling Reasoner in Console. Once Reasoner was enabled, the answer was produced as expected.
