### ISSUE TITLE
Enable usage of external config file in default locations

### ISSUE THREAD

**Issue by haskie-lambda** [vaticle/typedb#6372]
## Problem to Solve

Installing TypeDB in a readonly location produces a number of problems as explained in the linked issues.
Especially configuration is difficult to achieve and calls for wrapper scripts etc.

Akin to config files in other programs and services like vim,neovim,ssh,recoll,zsh & co 
parsing the config file from default locations like

- `$HOME/.typedb.properties`
- `$HOME/_typedb.properties` (windows)

would be a nice way to configure typedb when installed in a readonly container.

## Current Workaround

Using a wrapper script with commandline parameters; However there is issue #6370 which limits
this greatly

## Proposed Solution

parsing the config file from default locations like

- `$HOME/.typedb.properties`
- `$HOME/_typedb.properties` (windows)

if it is not found in the install location, with the following precedence order:
- commandline arguments 
- config file of the install location
- config file in `$HOME`

## Additional Information

#6370
#6371

**Comment by flyingsilverfin** [comment]
The mentioned designs are finished and should take care of any related issues
