### ISSUE TITLE
Introduce ENCODING_VERSION in storage to catch breaking changes

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6376]
## Problem to Solve

In the future, we will end up modifying the storage data format, which is a non-backward compatible change. To prevent users from migrating blindly to a version that is incompatible, we should store the data version number in storage and check it on bootup.

## Current Workaround

Don't migrate by referencing the data folder if there is a known incompatibility.

## Proposed Solution

Add to the SYSTEM encoding enum a ENCODING_VERSION. This is incremented when a breaking change occurs, and validated on startup to check that the persisted ENCODING_VERSION is the same as what is supported by the source code.

**Comment by haikalpribadi** [comment]
"data" is to generic. We should call it `encoding_version`.

**Comment by flyingsilverfin** [comment]
Implemented with #6484
