### ISSUE TITLE
[New feature required] Compute the Shortest Path

### ISSUE THREAD

**Issue by yiouyou** [vaticle/typedb#6393]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Need 'Compute the Shortest Path' features like in Grakn 1.8.4, such as ```compute path from V229424, to V446496, in [person, friendship];```

## Current Workaround

Don't support yet in new TypeDB

## Proposed Solution

Sorry, no idea.

## Additional Information

Feature details mentioned in https://github.com/vaticle/docs/blob/80ba09226ad666dea44f788898f04eac18c25cab/11-query/07-compute-query.md

**Comment by lolski** [comment]
Merged with https://github.com/vaticle/typedb/issues/6394
