### ISSUE TITLE
Analystics / OLAP

### ISSUE THREAD

**Issue by yiouyou** [vaticle/typedb#6394]
### Need 'Find the Most Interesting Instances' features like in Grakn 1.8.4, such as 

1) Compute centrality using degree
```compute centrality of organisation, in [organisation, person, employment], using degree;```

2) Compute centrality using k-core
```compute centrality using k-core, where min-k=5;```

3) Identify Clusters
```compute cluster in [person, employment, organisation], using connected-component, where contains=V12488;```

4) Compute clusters using k-core
```compute cluster in [person, friendship], using k-core, where k=3;```

### Need 'Compute the Shortest Path' features like in Grakn 1.8.4, such as

1) `compute path from V229424, to V446496, in [person, friendship];`

## Current Workaround

Don't support yet in new TypeDB.

## Proposed Solution

Sorry, no idea.

## Additional Information

Feature details mentioned in https://github.com/vaticle/docs/blob/80ba09226ad666dea44f788898f04eac18c25cab/11-query/07-compute-query.md

**Comment by lolski** [comment]
Hi!

The 2.0 release is a complete rewrite of the 1.x, done with the motivation of making it much more optimised. Currently it's already much faster than 1.x, but there are still many areas that can be improved even further.

That is our primary focus as of now and we'll start the discussion of bringing back the analytics / OLAP feature, once it's done.

**Comment by jamesreprise** [comment]
We don't yet support analytics in TypeDB. Closing as no longer relevant.
