### ISSUE TITLE
Re-enable failing reasoner correctness steps

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6396]
## Description

Many steps that verify the reasoner's soundness or completeness fail. These failures need to be investigated and fixed so that they can be reinstated. 

## Environment

1. OS (where TypeDB server runs): Grabl
2. TypeDB version (and platform): TypeDB 2.2.0 as of https://github.com/vaticle/typedb/pull/6374
3. TypeDB client: none, internal correctness verification

## Additional Information

Each is demarked by `# TODO: Fails` so that they can be found easily.

**Comment by dmitrii-ubskii** [comment]
Resolved by https://github.com/vaticle/typedb-behaviour/pull/222
