### ISSUE TITLE
Remove all usages of `.iterator.next()` to get one element

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6404]
## Problem to Solve

Throughout the core codebase we have usages where we open an iterator and only retrieve the first element. This can end up being inefficient because we do not release the underlying Rocks iterators (if it backed by a rocks iterator). 

## Proposed Solution

We should use `.first()` if we only want to retrieve the first or some element from an iterator. This method will automatically call `.recycle()` on the iterator

**Comment by haikalpribadi** [comment]
Solved by https://github.com/vaticle/typedb/pull/6413
