### ISSUE TITLE
Match Bug - Unable to find entity by attribute

### ISSUE THREAD

**Issue by nicolamassarenti** [vaticle/typedb#6426]
Hi,

I've deployed on GKE typedb server (version 2.3.2). I am connecting with the console (version 2.1.3) to the remote db. 

The DB schema has defined the entity `sentence`, that has the attribute `text`. 

With the query `match $s isa sentence, has text $t; get $s, $t;` I obtain the result:
```
...
{ $s iid 0x966e8008800000000000000d isa sentence; $t "Lo sportello metallico automatico a scorrimento verticale protegge l’operatore durante le operazioni di prelievo e deposito in baia durante la movimentazione dell’elevatore all'interno della macchina. Durante la fase di apertura/chiusura dello sportello, è attiva la barriera di protezione fotoelettrica multi raggio.  Tutte le baie di accesso sono dotate di sportello a chiusura automatica. L’apertura e la chiusura dello sportello a chiusura automatica di baia in modalità manuale è comandata dai pulsanti ausiliari montati lateralmente a ciascuna baia in prossimità del pulsante di arresto di emergenza a fungo." isa text; }
...
```

but, If I run the query:
```
match $x isa sentence, has text "Lo sportello metallico automatico a scorrimento verticale protegge l’operatore durante le operazioni di prelievo e deposito in baia durante la movimentazione dell’elevatore all'interno della macchina. Durante la fase di apertura/chiusura dello sportello, è attiva la barriera di protezione fotoelettrica multi raggio.  Tutte le baie di accesso sono dotate di sportello a chiusura automatica. L’apertura e la chiusura dello sportello a chiusura automatica di baia in modalità manuale è comandata dai pulsanti ausiliari montati lateralmente a ciascuna baia in prossimità del pulsante di arresto di emergenza a fungo."; get $x;
```

i receive back:
```
answers: 0, duration: 76 ms
```

I have a local db (version 2.2.0) with the same data. By running the same query I instead receive the expected entity.

Do you have any idea about how to solve this issue without downgrading the docker container to typedb version 2.2.0?

**Comment by flyingsilverfin** [comment]
Interesting - so to conclude in 2.2.0 the match query runs and in 2.3.2 you don't get an answer for it?

**Comment by nicolamassarenti** [comment]
Yes, that's correct

**Comment by nicolamassarenti** [comment]
Hello @flyingsilverfin , we are still encountering some problems. 

We are available to share our db but we would prefer to further describe our issue privately. Could you share us the email to which send the db and all additional information?

Thanks

**Comment by flyingsilverfin** [comment]
@nicolamassarenti yes please, use `joshua@vaticle.com` ! I'm working on this very soon so it would be very useful
