### ISSUE TITLE
Thing.isInferred: always returns 'false' for Attributes

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb#6430]
## Description

Thing.isInferred is always false for Attributes, even when they are inferred (i.e: they are returned by a query with reasoning on, but are not returned by a query with reasoning disabled)

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform):TypeDB 2.3.0
3. TypeDB client: client-java

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Create an entity type `person`, an attribute type `name`, and a rule:
```tql
define
rule steve-rule: when { $x isa person; } then { $x has name "Steve"; };
```
Then retrieve the attribute "Steve" in a query with reasoning enabled.

## Expected Output

`isInferred` should be true

## Actual Output

`isInferred` is false

## Additional information

This is important because new Studio will rely on the flag.

**Comment by flyingsilverfin** [comment]
Solved as of #6432
