### ISSUE TITLE
Enable naiive sorting on multiple variables

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6434]
## Problem to Solve

We would like to improve the efficiency of sorting on multiple variables - for now, by not transferring all answers over the network.

Since our sorting is already inefficient, and the next generation of traversal engine should support sorting on multiple variables directly, we can already offer inefficient sorting on multiple variables. This will enable users with enough server RAM to load and compute the sorted answers and usually limit it, before returning the sorted stream to the user.

## Current Workaround

Transfer all of the answers over the network and sort.

## Proposed Solution

Allow sorting on multiple query variables in the query language, to avoid massive network transfer costs. For now, sorting should be feasible on moderate answer sizes that fit into memory.

**Comment by flyingsilverfin** [comment]
Closed with #6437

**Comment by Tin-Nguyen** [comment]
Great thanks for working on this quickly
