### ISSUE TITLE
getPlayersByRoleType non-deterministically returns root type

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6440]
## Description

`getPlayersByRoleType` non-deterministically returns the root type `role`. We believe this is counter to the intention, which is that overridden supertypes should not be returned. This is crucial because it affects the reasoner's `materialise` operation.

## Environment

1. OS (where TypeDB server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. TypeDB version (and platform): { e.g. TypeDB 2.0.0, or TypeDB Cluster 2.0.0 on Google Cloud }
3. TypeDB client: { e.g. client-java, client-python, client-nodejs, or console }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

In the branch `reasoner-refactor`, commit `b25e64544613417b9d86b3250dc0f393de086dd7` from PR https://github.com/vaticle/typedb/pull/6429 the test `ExplanationTest.test_nested_explanations` fails non-deterministically. 

This has been debugged and found to be due to inconsistent results from `getPlayersByRoleType` which for this example sometimes contains only `friend` and sometimes contains both `friend` and `role`.

To see this error, add a breakpoint for line 520 (`return relationMap.equals(insertedMap);`) of `logic/Rule.java` to detect when the two are not equal. 

## Expected Output

We would expect the `insertedMap` and `relationMap` always to be the same, as a materialised `friendship` relation should always be determined to be insertable when found again by the same rule later (but with the direction reversed).

## Actual Output

The roles are mismatched, indicating that something likely went wrong at the graph storage layer.
 
## Additional information

This could be the cause of the long-running of scenario `given an undirected graph, all vertices connected to a given vertex can be found` which also has many symmetric relations.

**Comment by flyingsilverfin** [comment]
Solved with #6444
