### ISSUE TITLE
Reasoner inefficient for symmetric patterns

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6453]
## Problem to Solve

The reasoner can be very inefficient when it deals with two identical roleplayers in a relation. Consider when it's processing a concludable `$o($x, $y) isa link;`. If `$x=0x123` we create a `BoundConcludableResolver` with bounds `$x=0x123`. If `$y=0x123` we create a `BoundConcludableResolver` with bounds `$y=0x123`. `$x` and `$y` are equivalent here, so we have more resolvers than we need. This can cause a computationally explosive amount of additional work when this creates co-dependent cycles.

## Current Workaround

None

## Proposed Solution

Solution TBD.

## Additional Information

Scenario `given an undirected graph, all vertices connected to a given vertex can be found` replicates the issue.

**Comment by jmsfltchr** [comment]
After https://github.com/vaticle/typedb/pull/6497 this needs to be re-implemented, which should be quite trivial in the new architecture.

**Comment by krishnangovindraj** [comment]
At the current state of the reasoner (2.14.3), I believe we are as efficient as can be.
Consider the case of undirected transitivity (as mentioned) to create co-dependent cycles
```
rule undirected-transitivity: 
when { (node: $x, node: $y) isa edge; (node: $y, node:$z) isa edge; }
then { (node:$x, node: $z) isa edge; }
```
In a chain `1-2-3`, the query: `match $x isa node, has id 2; (node:$x, node: $y) isa edge;` 
Will generate the calls (showing the unifiers):
```
($x: 2, $y) isa edge;
($x, $y: 2) isa edge;

($x:1, $y) isa edge;
($x:3, $y) isa edge;
($x, $y:1) isa edge;
($x, $y:3) isa edge;
```

I believe all of these are required to be evaluated for correctness, and we are quite efficient in reusing the `ConcludableController.Processor` using alpha-equivalence.  TODO: verify and close.

**Comment by krishnangovindraj** [comment]
My previous comment likely misunderstands it. Specifically: "I believe all of these are required to be evaluated for correctness" 

What the issue suggests is likely to detect when the orders are not required for completeness and rule out redundant work (as in the example in the OP). Since it requires analysing/reasoning on the pattern itself, this puts it in the domain of query optimisation/rewriting

**Comment by flyingsilverfin** [comment]
@krishnangovindraj  i think it sounds like this is mostly solved though? The original issue was specifically about symmetric patterns + bounds, which is already taken care of purely through the alpha-equivalent concludables controllers. I'm going to close this for now, please make an issue if you spot something we can extract from this into a coherent piece of work.
