### ISSUE TITLE
Reasoner Planner

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6467]
## Problem to Solve

We require much more advanced planning for reasoner query execution. We will frame this as the task of minimising the total amount of work that needs to be done to explore all paths that could answer the user's query (rather than optimising for latency).

This task requires picking the optimal order in which to execute the user's initial query. The user's query will be in our internal Disjunctive normal form, so the task is reduced to picking ordering in conjunctions. However, we would also like to account for the cost of computing answers for rules. Rule bodies are also conjunctions, so we have a similar problem statement throughout.

## Current Workaround

Currently we use very basic heuristics.

## Research and Discussions

**Glossary**
Bound signature: The set of variables that will be bound when the traversal is executed.

**Claims/statements we can make:**

(A) A conclusion should have one cost of being concluded per bound signature. Although this doesn’t take into account that some work could already have been done in the computation graph.

Splitting a conjunction into Retrievables to be planned individually looks like a terrible idea. This is because each Resolvable can provide a different binding signature to the next element of the plan, depending upon the plan ordering.
Therefore, for this to work we would have to generate plans for all binding signatures for the conjunction and optimise their ordering. Better instead to create one plan which includes all Resolvables, using some precomputed cost for the Concludables present.

The cost of a concludable is dependent upon one of two architectures:
1. Somehow aggregate the cost of all rules that it could trigger (for a given bound signature)
2. Consider the cost of triggering each rule separately, in which case we can have a different optimal plan in the calling conjunction according the rule that will be explored.

Approach 2 could be more optimal in some cases, but as soon as there are multiple conclusions we would need a plan for the calling conjunction for each permutation of rules the concludables could trigger. This could be enormous, so is unviable. This would also contradict statement (A).

(B) We shouldn’t try to plan for work that has already been done. This is both hard to track and biases the planning weirdly.

In a recursive rule (looking at transitivity to start) we notice several things:

- In the general case we know that it’s cost is N^2, where N is determined by by some function of the statistics for the vertices and edges present, taking into account their connectivity.
- We think that the order of the cost should be the same regardless of the bound signature given, but intuitively there should be some reduction in cost if a fully-bound signature is given.

**Comment by flyingsilverfin** [comment]
@krishnangovindraj  we can consider this closed now?

**Comment by krishnangovindraj** [comment]
Yes.
