### ISSUE TITLE
Issues Installing Grakn 1.5.7

### ISSUE THREAD

**Issue by carltondaniel** [vaticle/typedb#6469]
Im trying to create knowledge base as mention in this (https://github.com/RasaHQ/tutorial-knowledge-base) repo for which i need to install Grakn 1.5.7 but this (https://repo.grakn.ai/#browse/browse:apt:packages%2Fg%2Fgrakn-console%2F2.0.0%2Fall%2Fgrakn-console%2Fpool%2Fg%2Fgrakn-console%2Fgrakn-console_2.0.0_all.deb) is the only archived source i found but no luck.

Thanks in advance

**Comment by jmsfltchr** [comment]
You can find all past releases here: https://github.com/vaticle/typedb/releases however I really recommend against using such an old version. I'll look at getting rasa updated to use TypeDB. In the meantime I believe it should be compatible with later versions of Grakn such as 1.8.x

**Comment by jmsfltchr** [comment]
Actually reopening until we decide what action to take on TypeDB support in Rasa

**Comment by jmsfltchr** [comment]
Closing this issue on the basis that we have shared how to access old TypeDB/Grakn versions and the real issue remaining is to update https://github.com/RasaHQ/tutorial-knowledge-base with guidance for using TypeDB, tracked by [this issue](https://github.com/RasaHQ/tutorial-knowledge-base/issues/15).
