### ISSUE TITLE
Make the Docker distribution use UTF-8 by default

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#6496]
Currently, the Docker distribution of TypeDB doesn't work well with UTF-8 characters. Alex [found](https://forum.vaticle.com/t/chinese-couldnt-be-displayed-normally-in-typedb-studio-2-4-0-alpha-4-docker-installed-typedb-couldn-t-save-chinese-normally/2697/2) that it can be fixed by setting the environment variable `LC_ALL=C.UTF-8` whenever the user creates a new container instance. An even better solution is to make the setting default, by adding it into the `assemble-docker` target.

**Comment by lolski** [comment]
@flyingsilverfin did you ever get around to fix this issue?

**Comment by flyingsilverfin** [comment]
noope not yet, should do that tho

**Comment by flyingsilverfin** [comment]
@lolski  @alexjpwalker  so looking into this we can update the dockerfile to update `LC_ALL` to the noted UTF-8 setting. However, it appears that this might require installing the `locales-all` package in ubuntu... which is a 132 MB package!

Should we do that or just ask the user to run the docker container with that setting?

**Comment by alexjpwalker** [comment]
Some findings after experimentation:

- When inserting Chinese text (in a string attribute value) via TypeDB Studio run on my Mac into TypeDB running in a Docker container, the insert succeeds. When reading Chinese text from TypeDB in my Docker container to TypeDB Studio on my Mac, the match succeeds and returns the correct characters.
- The same applies when running Console on my Mac.
- However, when running Console in the Docker container, doing the same Match query returns "??????" in place of the Chinese text.
- Also, even attempting to copy and paste Chinese characters into Console run in the Docker container, results in "????????" appearing in the space where the text should have been copied to.

I'll have a look at the Console code to see where we're going wrong.
