### ISSUE TITLE
Trying to force rule order gives non-deterministic results or hangs the database.

### ISSUE THREAD

**Issue by Slapfish** [vaticle/typedb#6500]
## Description

The first setup never finishes, the second gives sometimes two results, sometimes three.

## Environment

1. OS (where TypeDB server runs): Ubuntu 20.04
2. TypeDB version (and platform): TypeDB 2.5.0
3. TypeDB client: client-python

## Reproducible Steps
The text files contain a define section, an insert section and a query section.
[never_finishes.txt](https://github.com/vaticle/typedb/files/7746775/never_finishes.txt)
[non_deterministic_result_set.txt](https://github.com/vaticle/typedb/files/7746777/non_deterministic_result_set.txt)

I ran & generated those in Python (see additional information)
```
options = TypeDBOptions.core()
options.explain = True
options.infer = True
with session.transaction(TransactionType.READ, options) as transaction:
```

## Expected Output
First query:
Some output, or at least a way to interrupt the database, but SIGTERM doesn't seem to work.

Second query:
A stable size of the result set.

## Actual Output

First query:
It hangs, pegged at 100% CPU, stable memory usage, ignores SIGTERM.

Second query:

Sometimes two results, sometimes three results.
The one that goes missing 50% of the time is the `door` `common room` combination.
 
## Additional information

Full Python code for the first query: [main.txt](https://github.com/vaticle/typedb/files/7746841/main.txt)
Full python code for second query: [door.txt](https://github.com/vaticle/typedb/files/7746837/door.txt)

**Comment by jmsfltchr** [comment]
Hi, thanks for reporting! Both of these are serious issues and we will investigate them.
