### ISSUE TITLE
Redefining an attributetype value appears to commit successfully when, in fact, it fails.

### ISSUE THREAD

**Issue by JonThom** [vaticle/typedb#6510]
## Description

Redefining an attributetype value appears to commit successfully when, in fact, it fails.

## Environment

1. OS (where TypeDB server runs): Mac OS 10
2. TypeDB version (and platform): TypeDB 2.6.0
3. TypeDB client: client-python and console

## Reproducible Steps

create a new database
```
database create tmp
```

define an attribute type
```
$ transaction tmp schema write

tmp::schema::write*> define attr1 sub attribute, value boolean;

> Concepts have been defined
tmp::schema::write*> commit
> Transaction changes committed
```

then attempt to re-define the attribute's value:
```
$ transaction tmp schema write
tmp::schema::write> define attr1 sub attribute, value double;

> Concepts have been defined
tmp::schema::write*> commit
> Transaction changes committed
```

Open a read transaction to check whether it worked

```
$ transaction tmp schema read

tmp::schema::read> match $x sub attribute; $x value double;

```

## Expected Output

{ $x type a1 sub attribute; }
answers: 1, total (with concept details) duration: 16 ms

## Actual Output

answers: 0, total (with concept details) duration: 29 ms

**Comment by krishnangovindraj** [comment]
This was fixed by #6790
