### ISSUE TITLE
Declare database partitions with partition IDs

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb#6526]
## Problem to Solve

A database partition, backed by a RocksDB column family, uses "partition name" as its identifier.

The name is big in size and therefore a shorter identifier "partition ID" has been added, in order to keep TypeDB Cluster data replication efficient.

However, we can't yet remove the "partition name" in order to stay backwards compatible.

## Proposed Solution

Remove the legacy "partition name" and fully utilise "partition ID". But, do it with appropriate timing since it will require users to reload their data.

**Comment by flyingsilverfin** [comment]
Implemented with #6529
