### ISSUE TITLE
Cannot override inherited role after defining relation subtype

### ISSUE THREAD

**Issue by JonThom** [vaticle/typedb#6535]
## Description

As we know, when subtyping a relation, any roles that are not explicitly subtyped are implicitly inherited by the subtype:
```
define super_rel sub relation, relates super_rel_role;
define sub_rel sub super_rel;
# sub_rel implicitly inherits super_rel_role, but super_rel_role keeps super_rel as its scope
```
However, if the user subsequently tries to override `super_rel_role`:

```
define sub_rel relates sub_rel_role as super_rel_role;
```
An exception occurs: 

> com.vaticle.typedb.core.common.exception.TypeDBException: [TYW31] Invalid Type Write: The role type 'sub_rel_role' cannot override 'super_rel_role;' as it is either directly related or not inherited.

This is inconsistent, as the override would have worked fine if done while defining `sub_rel` originally, e..g 

```
define sub_rel sub super_rel, relates sub_rel_role as super_rel_role;
```

## Environment

1. OS (where TypeDB server runs): Mac OS 12.2.1
2. TypeDB version (and platform): TypeDB 2.6.3
3. TypeDB client: client-python; console

## Reproducible Steps

See above

## Expected Output

`sub_rel_role` should inherit from (and override) `super_rel_role`.

## Actual Output

Exception (see above)

**Comment by flyingsilverfin** [comment]
This is fixed in 2.11.0
