### ISSUE TITLE
Query slow-down on adding attribute comparison

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb#6550]
## Description
I have a molecular model dataset with a relation `bond` which forms cycles and is symmetric. 
```
    chemical_entity sub entity,
        plays constitutes:constituent,
        plays bond:constituent_1,
        plays bond:constituent_2;

    atom sub entity,
        owns atom_id @key,
        owns charge;

    atom_c sub atom;
    (...)

    bond sub relation,
        relates compound,
        relates constituent_1,
        relates constituent_2;

    single_bond sub bond;
    double_bond sub bond;
    aromatic_bond sub bond;

```   

The following are queries to identify benzene rings (6 `aromatic_bond` relations starting and ending with the same `atom_c` entity). The latter de-duplicates by enforcing an order.
```
# fast: 84 results in 132 ms
match
    (constituent_1:$c1, constituent_2:$c2) isa aromatic_bond;
    (constituent_1:$c2, constituent_2:$c3) isa aromatic_bond;
    (constituent_1:$c3, constituent_2:$c4) isa aromatic_bond;
    (constituent_1:$c4, constituent_2:$c5) isa aromatic_bond;
    (constituent_1:$c5, constituent_2:$c6) isa aromatic_bond;
    (constituent_1:$c6, constituent_2:$c1) isa aromatic_bond;
    $c1 isa atom_c, has atom_id $e1;
    $c2 isa atom_c, has atom_id $e2;
    $c3 isa atom_c, has atom_id $e3;
    $c4 isa atom_c, has atom_id $e4;
    $c5 isa atom_c, has atom_id $e5;
    $c6 isa atom_c, has atom_id $e6;
get
    $e1, $e2, $e3, $e4, $e5, $e6;

# slow: 14 results in 252487 ms 
match
    (constituent_1:$c1, constituent_2:$c2) isa aromatic_bond;
    (constituent_1:$c2, constituent_2:$c3) isa aromatic_bond;
    (constituent_1:$c3, constituent_2:$c4) isa aromatic_bond;
    (constituent_1:$c4, constituent_2:$c5) isa aromatic_bond;
    (constituent_1:$c5, constituent_2:$c6) isa aromatic_bond;
    (constituent_1:$c6, constituent_2:$c1) isa aromatic_bond;
    $c1 isa atom_c, has atom_id $e1;
    $c2 isa atom_c, has atom_id $e2;
    $c3 isa atom_c, has atom_id $e3;
    $c4 isa atom_c, has atom_id $e4;
    $c5 isa atom_c, has atom_id $e5;
    $c6 isa atom_c, has atom_id $e6;
    $e1 < $e2; $e1 < $e3; $e1 < $e4; $e1 < $e5; $e1 < $e6; 
    $e2 < $e3;
get
    $e1, $e2, $e3, $e4, $e5, $e6;

```

## Environment

1. OS (where TypeDB server runs):  **Ubuntu 18.04.6 LTS**
2. TypeDB version (and platform): **typedb-all-linux-2.8.1**
3. TypeDB client: **console**
4. Other environment details:

## Reproducible Steps
Steps to create the smallest reproducible scenario:
1. Download the files (linked at the bottom of the issue)
2. Create database and write schema (`typedb console --script=schema.script.tql`)
3. Insert data (`typedb console --script=data.script.tql`)
4. Open a `transaction mutamre data read` to run the queries in `queries.tql` (Also in the description above)
5. Compare the running times

## Expected Output
Expected both queries to run in approximately the same time

## Actual Output
The query without comparison returns in ~150 ms. The query with comparison times out after returning ~5 results (expected 7 results)
 
## Additional information
Files to reproduce: [mutamre.zip](https://github.com/vaticle/typedb/files/8729639/mutamre.zip)

**Comment by flyingsilverfin** [comment]
FYI @krishnangovindraj  since this is closed, does that mean your example can be merged into examples? Or is it dependent on something else?

**Comment by krishnangovindraj** [comment]
Will check and see.
