### ISSUE TITLE
Unable to install typedb-all 2.9.0 for Linux via APT

### ISSUE THREAD

**Issue by nicolamassarenti** [vaticle/typedb#6551]
Hi, I've tried to install typedb-all but I got this error message.

![image](https://user-images.githubusercontent.com/38035878/169844914-734369bd-8b40-4afe-948f-596da5212a88.png)

I'm running on Ubuntu 22.04 and I followed the instructions in this [page](https://docs.vaticle.com/docs/running-typedb/install-and-run#using-apt).

Instrad, I was able of running the commands:
```shell
sudo apt install typedb-server typedb-console
```

**Comment by flyingsilverfin** [comment]
hi @nicolamassarenti  that is odd! Can you try again with `2.9.0` which should be released please?

**Comment by nicolamassarenti** [comment]
When should it be released?

**Comment by flyingsilverfin** [comment]
Ah that is 2.9.0 that has the issue, not 2.8.1
We will re-release to fix this very soon!
