### ISSUE TITLE
RST_STREAM closed stream. HTTP/2 error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by stevehcox** [vaticle/typedb#6569]
## Description

I am in database::schema::write.

I have established a schema in .tql and the concepts have been successfully defined (source ../shema.tql) however, upon 'commit' the console throws back "RST_STREAM closed stream. HTTP/2 error code: PROTOCOL_ERROR". Any thoughts?

## Environment

1.  OS of TypeDB server: Mac OS 12.4,
2. TypeDB version (and platform): TypeDB version: 2.10.0 on AWS
3. TypeDB client:  console 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. See additional information....
2. { e.g. Load ... }
3. { e.g. Query ... }
4. { e.g. See error ... }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

~ % /typedb console --server X.X.X:1729

Welcome to TypeDB Console. You are now in TypeDB Wonderland!
Copyright (C) 2021 Vaticle

> transaction test_schema schema write
test_schema::schema::write>  source /schema.tql
Concepts have been defined
SKG_test::schema::write*> commit
RST_STREAM closed stream. HTTP/2 error code: PROTOCOL_ERROR

**Comment by stevehcox** [comment]
Hi Alex,

Thanks for following up.

It appears not – I was just writing a follow up – the error is repeated when I try to commit the schema in studio.  But I may have my settings all screwed up (sorry, I’m a healthcare person, not a data scientist).  Can you just list how TypeDB console, TypeDB studio and TypeDB server should be pointed so that I can commit the schema to the (AWS hosted) database? (either through studio or the console)….

Really appreciate this.

Steve


Steve Cox

[A picture containing text, sign, vector graphics  Description automatically generated]

[Logo, company name  Description automatically generated]
Direct:  +44 (0) 20 7924 2345  |  Mobile: +44 (0) 7920027145  |  ***@***.******@***.***>

Important notice:

This message is for the named recipient(s) only. It may contain confidential, proprietary or legally privileged information. No confidentiality is waived or lost by any mis-transmission. If you have received this message in error please immediately notify the sender, delete it and all copies of it from your system and destroy any hard copies. If you are not the intended recipient you must not use, disclose, distribute, print or copy any part of this message directly or indirectly. Internet communications are not secure and subject to possible data corruption, either accidentally or on purpose, and may contain viruses.
At RAIR.AI we are committed to protecting your privacy. This policy applies when we are acting as a controller of personal data, i.e. where we have determined the purposes and means of the processing of that personal data.  If you are a Customer or Supplier of RAIR Health Limited, or an employee of the same, please refer to https://rair.ai/customer-supplier-notice for an important notice regarding your rights as a data subject.

RAIR Health Limited is registered in England: No 10039808, 20 Dents Road, London, SW11 6JA


From: Alex Walker ***@***.***>
Date: Friday, 10 June 2022 at 16:38
To: vaticle/typedb ***@***.***>
Cc: Steve Cox ***@***.***>, Author ***@***.***>
Subject: Re: [vaticle/typedb] RST_STREAM closed stream. HTTP/2 error code: PROTOCOL_ERROR (Issue #6569)

Hi there - is this caused by the issue that we saw while using TypeDB Studio?

  *   vaticle/typedb-studio#567<https://github.com/vaticle/typedb-studio/issues/567>

**Comment by alexjpwalker** [comment]
@stevehcox - Happy to take a look. Could you provide a screencast / screen recording to demonstrate the issue?

**Comment by stevehcox** [comment]
Hi Alex,


I’m still having problems with Studio – I thought that I would wait for 2.11.0 in hope that the problem would shake out, but much the same, I’m afraid.  I am trying to connect to a schema on AWS – I know that it’s there and correct, because it worked in previous versions and I can also see it when I go into console manually (and indeed Studio).  I have put a recording of the config file for the server (I have tried both pointing the TypeDB server both at 0.0.0.0 and at the AWS IP address directly in the .yml file), firing up the server in console and also the studio ‘failure’.  I notice that when I attempt to configure the server for the 3.12.54.105:1729 connection – I get an error and I’m wondering whether this is the problem?



Frustratingly, I can nonetheless make the changes to the schema in console manually with the same server/console settings that seemingly don’t work for ‘Studio’.



The video, as suggested is here (https://www.dropbox.com/s/pbfruoed53tosdg/Screen%20Recording%202022-07-13%20at%2009.43.43.mov?dl=0)

Thanks again for your help!

S


Steve Cox

[A picture containing text, sign, vector graphics  Description automatically generated]

[Logo, company name  Description automatically generated]
Direct:  +44 (0) 20 7924 2345  |  Mobile: +44 (0) 7920027145  |  ***@***.******@***.***>

Important notice:

This message is for the named recipient(s) only. It may contain confidential, proprietary or legally privileged information. No confidentiality is waived or lost by any mis-transmission. If you have received this message in error please immediately notify the sender, delete it and all copies of it from your system and destroy any hard copies. If you are not the intended recipient you must not use, disclose, distribute, print or copy any part of this message directly or indirectly. Internet communications are not secure and subject to possible data corruption, either accidentally or on purpose, and may contain viruses.
At RAIR.AI we are committed to protecting your privacy. This policy applies when we are acting as a controller of personal data, i.e. where we have determined the purposes and means of the processing of that personal data.  If you are a Customer or Supplier of RAIR Health Limited, or an employee of the same, please refer to https://rair.ai/customer-supplier-notice for an important notice regarding your rights as a data subject.

RAIR Health Limited is registered in England: No 10039808, 20 Dents Road, London, SW11 6JA


From: Alex Walker ***@***.***>
Date: Monday, 13 June 2022 at 13:04
To: vaticle/typedb ***@***.***>
Cc: Steve Cox ***@***.***>, Mention ***@***.***>
Subject: Re: [vaticle/typedb] RST_STREAM closed stream. HTTP/2 error code: PROTOCOL_ERROR (Issue #6569)

@stevehcox<https://github.com/stevehcox> - Happy to take a look. Could you provide a screencast / screen recording to demonstrate the issue?

**Comment by alexjpwalker** [comment]
Hi Steve,

I see two interesting points in your screencast:

1. You're trying to launch TypeDB Server, but there is already an instance running at that address. Do you know when that instance was launched, and what version of TypeDB it is running?

2. On connecting to the database, it immediately says "The request message is not recognised" ie: the issue from https://github.com/vaticle/typedb-studio/issues/567 that we had previously looked at. Again, this indicates that the TypeDB version is incompatible with the TypeDB Studio version.

As discussed in https://github.com/vaticle/typedb-studio/issues/567, you need TypeDB 2.10.0 or above to run Studio. I would therefore conclude that you're _trying_ to run TypeDB 2.10.0, but it's failing to launch because you already have an older TypeDB running and using the same IP address and port.

If this is the case, and you want to retain your data, you'll need to migrate the data. Instructions for migration can be found here: https://docs.vaticle.com/docs/management/migration-and-backup

Once you've copied or exported your data, terminate the running TypeDB process using, say:
```
kill $(jps | grep TypeDBServer | awk '{print $1}')
```
After that, launch the new TypeDB server using `typedb server` (passing in your config file as normal). It should start successfully, and it should read "TypeDB Server bootup successful" (or similar).

Then, copy or import your data into the new server instance, and you're good to go.

**Comment by alexjpwalker** [comment]
Hi @stevehcox , did you get a chance to try the points described above?

**Comment by flyingsilverfin** [comment]
Closing since it's so out of date
