### ISSUE TITLE
Rule validation wrongly flags cases without negative cycles

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb#6599]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. OS (where TypeDB server runs): Mac OS 12.4
2. TypeDB version (and platform): 2.11
3. TypeDB client: N/A, server bug.
4. Other environment details:

## Reproducible Steps
```
  define
  concept sub entity,
    plays binary:first,
    plays binary:second;

    binary sub relation, relates first, relates second;
    road sub binary;
    reachable sub binary;

    roadblock sub binary;
    sleeping-snorlax-on-route sub binary;

    rule reachable-is-transitive:
    when{
      (first: $a, second: $b) isa road;
      (first: $b, second: $c) isa reachable;
      not {(first: $a, second: $b) isa roadblock; };
    } then {
      (first: $a, second: $c) isa reachable;
    };

    rule snorlax-blocks-roads:
    when{
      (first: $a, second: $b) isa sleeping-snorlax-on-route;
    }then{
      (first: $a, second: $b) isa roadblock;
    };
```

## Expected Output
Passes validation

## Actual Output
Fails validation

**Comment by flyingsilverfin** [comment]
@krishnangovindraj let's be a bit more diligent with the issues and make sure we don't leave the `{}` templates of the issue unpopulated at all! There shouldn't be any left by the time the issue is submitted

**Comment by flyingsilverfin** [comment]
You should also remove this issue from "In review" because it's not implemented yet, and add a milestone (such as `Bug Fixes`)
