### ISSUE TITLE
Variable role resolution non-deterministically receives too few answers

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb#6610]
## Description
The BDD scenario "converting a fixed role to a variable bound with 'sub role' (?)(Variable Role Resolution)" fails non-deterministically with `error java.lang.AssertionError: Expected [27] answers, but got [24] expected:<27> but was:<24>`

## Environment

1. OS (where TypeDB server runs):  grabl
2. TypeDB version (and platform): 2.11.1
3. TypeDB client: BDD tests
4. Other environment details:

## Expected Output
Assertion should succeed

( may be related to: #6355 )

**Comment by krishnangovindraj** [comment]
I stumbled on this test failing in other ways, and reduced it to a situation which fails deterministically (or at least, very very often) at the number of top-level answers produced.

We expect 22 answers, (copied in the file. The variables ($x,$y) may be mixed up)
[debug.feature.txt](https://github.com/vaticle/typedb/files/9168701/debug.feature.txt)

**Comment by flyingsilverfin** [comment]
@krishnangovindraj can you set this to run 1000 times overnight at some point and see we can consider this an open issue still? Reasoner BDD has been quite reliable recently from what i've seen

**Comment by krishnangovindraj** [comment]
Reasoner BDD has been reliable for months, running 100x did not reproduce. Closing as fixed.
