### ISSUE TITLE
Nested negations inside conditions are 'unsupported' but enabled

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb#6625]
## Description
In the rule-validation logic, we have assertions which would fail in the presence of nested negations in rules. These would fail during testing but would not in prod - potentially allowing nested negated cycles and violating stratification.

## Expected Output
Either a rule with nested negations would be detected and fail rule-validation , or rule-validation recurses into nested-negations.

## Actual Output
Nested negations (probably) pass schema-commit and open the door for an inconsistent logical model.

**Comment by flyingsilverfin** [comment]
@krishnangovindraj  is this still an issue with the updated rule validation you implemented in disjunctions in rules?

**Comment by krishnangovindraj** [comment]
Nested negations in rules are disabled at TypeQL level.
Further rule-validation now recurses into negations - This will rule out at least the cases which lead to contradictory cycles.
