### ISSUE TITLE
Able to set number as type label

### ISSUE THREAD

**Issue by AnzeBlaBla** [vaticle/typedb#6627]
## Description

I was able to use the `setLabel` method on the `ThingType` concept (javascript client) to set the type's label to "1". I was then unable to change it back (as this is probably unexpected behaviour) using TypeDB Studio.

Queries on the DB were returning that type but undefining it is not possible (because "1" is not a valid typeql type name)

## Environment

1. OS (where TypeDB server runs): Windows 10
2. TypeDB version (and platform): TypeDB 2.11.1
3. TypeDB client: client-nodejs
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Make a type in the database
2. Query it using the node client
3. Use the concept api to get a remote version and use the `setLabel` method to set the name to "1"

## Expected Output

The concept API wouldn't let the label be set to a number.

## Actual Output

The label is successfully set and new type is visible:

![image](https://user-images.githubusercontent.com/52180401/183925260-446df478-f989-498e-a467-9db4d6e2da0c.png)

**Comment by flyingsilverfin** [comment]
Fixed in #6630
