### ISSUE TITLE
Avoid redundant commit-time rule-revalidation

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb#6633]
## Problem to Solve
Rule validation is currently done twice - Once at rule-creation time and once at rule-commit time, where we reindex and revalidate all rules. The (type) satisfiability check on most rules do not need to be done unless the type definitions change. 
(Note: Negative-cycle validation still needs to happen )

Further, re-validating the then & when for conjunction coherence is redundant if the inferred types are not updated as well. 

## Proposed Solution
Add a check to prevent revalidating rules which don't need to be revalidated if nothing has changed.

**Comment by flyingsilverfin** [comment]
Implemented in #6634
