### ISSUE TITLE
TLS authentication

### ISSUE THREAD

**Issue by OlegKoshelev** [vaticle/typedb#6647]
Hello! We have come across with a problem TypeDB doesn't have opportunity to use tls-authentication. We need it to restrict access for unauthenticated users. Is it possible to inject it to TypeDB? We have own implementation of maintaining sslContext for both TypeDB and TypeDB-client-java. Is it possible to create merge requests to extend functional around tls-authentication?

**Comment by haikalpribadi** [comment]
We have it in TypeDB Cluster (the enterprise version).

**Comment by OlegKoshelev** [comment]
Is it planned to add supporting of tls-authentication  for a non-cluster version? We need only tls-authentication without login and password.

**Comment by haikalpribadi** [comment]
Well, not quite. It's our enterprise feature for the commercial technology, which would be a reason for you to adopt TypeDB Cluster. :)

**Comment by flyingsilverfin** [comment]
I'm closing this issue, since we note that authenticaton is a TypeDB Cluster-specific feature.
