### ISSUE TITLE
Retrieving type instance counts

### ISSUE THREAD

**Issue by qqliang** [vaticle/typedb#6665]
as title describes, when I loaded data to an entity or relation, how did I to check the size of data belong to an entity or relation? I have seen the storage data file of typedb, but I can't understand it's meaning.
![image](https://user-images.githubusercontent.com/23022359/195776423-05d6e4b1-95a2-455c-b47d-ca0363b714ba.png)

**Comment by flyingsilverfin** [comment]
Hi - if you reboot your server after changing the configuration file to log for the filter `com.vaticle.typedb.core.database.CoreDatabase` to level "debug", you should get a summary of the total number of `thing` + `has` and `role`

**Comment by qqliang** [comment]
> Hi - if you reboot your server after changing the configuration file to log for the filter `com.vaticle.typedb.core.database.CoreDatabase` to level "debug", you should get a summary of the total number of `thing` + `has` and `role`

it isn't count entity number, My question is how should I know the size of stored data, such as MB/GB etc.

**Comment by flyingsilverfin** [comment]
ahh right isn't it just the size of the `data` directory? You can find the total on Ubuntu by doing `du -sh /data/typedb/server/data/moccubex/data`

**Comment by flyingsilverfin** [comment]
We don't have a way to separate the size based on entities/relations/attributes right now since they are all stored in the same RocksDB instance :)
