### ISSUE TITLE
Deletion(unlink) of multiple constraints with multiple cardinality

### ISSUE THREAD

**Issue by lveillard** [vaticle/typedb#6699]
## Description
Can't delete two attributes when one has a cardinality > 1 

## Environment
typeDB 2.13.0

## Reproducible Steps
```
define
id sub attribute, 
    value string;
fName sub attribute,
    value string;
name sub attribute,
    value string;

Person sub entity,
    owns id,
    owns fName,
    owns name;
```

```
insert
$p isa Person, has id '1', has name 'Ann', has fName 'B', has fName 'C';
```

```
match
$p isa Person, has id '1', has name $name, has fName $fName;

delete 
$p has $name, has $fName;
```

## Expected Output

Delete both fNames and the name.

## Actual Output

 Error> [THW22] Invalid Thing Write: Invalid attempt to delete attribute ownership. The thing '$p' does not have attribute '$name'

**Comment by lveillard** [comment]
Working workaround:
```
match
$a isa Person, has id '1', has $att;
{$att isa name;} or {$att isa fName;};
delete
$a has $att;
```

**Comment by flyingsilverfin** [comment]
It's not a bug per-se, but it is an unexpected UX we should improve!

**Comment by flyingsilverfin** [comment]
If deletes become best-effort, as noted in https://github.com/vaticle/typedb/issues/6755 I think this would also be resolved?
