### ISSUE TITLE
Add a distinctive "ready" message at the very end of bootup console output

### ISSUE THREAD

**Issue by izmalk** [vaticle/typedb#6747]
## Problem to Solve

When we start TypeDB we have the ASCII logo and then the following output:

```
10:21:25.604 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - TypeDB Server is now running and will keep this process alive.
10:21:25.607 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - You can press CTRL+C to shutdown this server.
10:21:25.607 [main] INFO com.vaticle.typedb.core.server.TypeDBServer -
10:21:25.607 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - version: 2.14.3
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - listening to address: 0.0.0.0:1729
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - data directory configured to: /usr/local/var/typedb/data
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - bootup completed in: 6793 ms
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - ...
```

And this `...` at the end is kind of hard to address as a successful bootup message in the documentation.

## Current Workaround

> After showing TypeDB ASCII logo and logging the bootup completion time, TypeDB is ready for connections.

## Proposed Solution

Something distinctive enough to be recognized as the "All green, send your transactions now" and at the very end of the default bootup output (instead of `...`).

Some possible variants:

1. ___ Delete the last line and make `bootup completed in: xxxx ms` the last one ___
2. Waiting for connections / Ready for connections
3. Entering the event loop
4. Ready

**Comment by flyingsilverfin** [comment]
Fair point! @haikalpribadi  what do you think?
we could do:
```
10:21:25.604 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - TypeDB Server is now running and will keep this process alive.
10:21:25.607 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - You can press CTRL+C to shutdown this server.
10:21:25.607 [main] INFO com.vaticle.typedb.core.server.TypeDBServer -
10:21:25.607 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - version: 2.14.3
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - listening to address: 0.0.0.0:1729
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - data directory configured to: /usr/local/var/typedb/data
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - bootup completed in: 6793 ms
10:21:25.608 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - 
```

And just leave the log line with no content there?

**Comment by haikalpribadi** [comment]
I don't know why we have the `...` to begin with but your suggestion above looks fine to me @flyingsilverfin

**Comment by flyingsilverfin** [comment]
@izmalk would you like to try to implement this change and put a PR into TypeDB? It should be very simple in the root `//server/TypeDBServer` class in the vaticle/typedb repository

**Comment by izmalk** [comment]
> @izmalk would you like to try to implement this change and put a PR into TypeDB? It should be very simple in the root `//server/TypeDBServer` class in the vaticle/typedb repository

Thanks, I'd love to. But I hope someone who actually knows what he is doing will do the review =).
