### ISSUE TITLE
Evaluate SpeedDB

### ISSUE THREAD

**Issue by benjaminasmall** [vaticle/typedb#6748]
Performance and any other characteristics, compared to RocksDB.
Maven repo: https://mavenlibs.com/maven/dependency/io.github.speedb-io/speedbjni .

- Evaluate performance of `catalogue_of_live`
- Evaluate performance of simulator

Any other context from @flyingsilverfin.

**Comment by flyingsilverfin** [comment]
@benjaminasmall  I think we're good to close this given that @krishnangovindraj  has done our benchmarking now?

**Comment by benjaminasmall** [comment]
Agreed.
