### ISSUE TITLE
Sorted mapped iterator produces out of order values

### ISSUE THREAD

**Issue by jamesreprise** [vaticle/typedb#6753]
## Description

In a given scenario, an assertion is failed when attempting to take values from a sorted mapped iterator.

## Environment

1. OS (where TypeDB server runs): macOS Ventura 13.1
2. TypeDB version (and platform): TypeDB Cluster 2.15.0
3. TypeDB client: java 2.14.3

## Reproducible Steps

1. Use a schema like the following:
```
define
    username sub attribute, value string;
    password-hash sub attribute, value string;
    password-created-at sub attribute, value datetime;
    
    user-password sub relation, relates user, relates password;
    
    user sub entity, owns username, plays user-password:user;
    password sub entity, owns password-hash, owns password-created-at, plays user-password:password;
```
2. Load in appropriate data.
3. Run the following query:
```
match
    $u isa user, has username $n;
    (user: $u, password: $p) isa user-password;
    $p isa password, has password-hash $ph, has password-created-at $pc;
    get $ph, $pc; sort $pc; limit 2;
```

## Expected Output

No issue, query executes as expected and returns results.

## Actual Output

Throws error on assertion from `WhileSortedIterator`: "Sorted mapped iterator produces out of order values".

**Comment by dmitrii-ubskii** [comment]
@jamesreprise Couple follow-ups:
1) What's "appropriate data"? Does this issue occur with any data matched by the query?
2) Do you have a call stack from the server when the assertion is violated?

**Comment by jamesreprise** [comment]
>     1. What's "appropriate data"? Does this issue occur with any data matched by the query?
This was tested against multiple instances of the system database, and it was flaky as to whether the issue would trigger. There didn't seem to be anything significant about the particular data loaded in. The usernames and passwords were fixed, though the hashes were different every time as were the password creation times.
>     2. Do you have a call stack from the server when the assertion is violated?
Unfortunately not. You should be able to recreate the issue from https://github.com/jamesreprise/typedb-cluster/blob/0d153b985b07418c805a6a7752d8236fcfc03df5/database/UserManager.java#L354 - remove the patch where we sort the queries manually in memory and add back in the sorting and limiting like so:
```
).get("ph", "pc").sort(pair("pc", "desc")).limit(previousPasswords)).toList();
```
