### ISSUE TITLE
typeQL: Issues when scoping multiple unlinks

### ISSUE THREAD

**Issue by lveillard** [vaticle/typedb#6755]
## Description

It is really hard to selectively unlink ids from multiple roles at once in one query. 

## Reproducible Steps
My use case is to selectively scope unlinks to each role. Being the most complicated  case:
- Let teaching:year untouched
- Unlink every teaching:student, if any
- Unlink teaching:student with a particular ID

But let's simplify this use case to the key thing that i'm unable to do:
- Unlink an id that is shared in two different roles, in one single role while keeping the $roles variable

Consider this:
```
define

year sub entity, owns id;
person sub entity, owns id, plays teacher, plays student
teaching sub relation, relates teacher, relates student, relates year;

insert

$a isa person, has id '1';
$b isa person, has id '2';
$c isa person, has id '3';
$y isa year, has id '2000';
$a-b (teacher: $a, student: $a, student: $c, year: $y )isa teaching;

match
$t ($roles:$id) isa teaching;

$id isa person, has id '1'; 
$roles type teaching:student;

delete
#option a)
$t ($id); Unable to add role player '$id' to the relation, as there are more than one possible role type it could play

#option b)
$t ($roles:$id); #Illegal type variable '$roles' found in delete query.


```
## problem with a)
It makes completely sense for link (add) operations... but we are deleting! 

Also, potentially an $id playing two different roles could not get unlinked in the right place, or get unlinked in both places 😱.
We are not telling typeDB where to destroy the edge.

## Problem with b)
So let's add the "$roles" thas has been set to "
"b" should work to link Ids and the role types that link them

Other alternatives:
- In order to unlink roles we can try something like this

```
# 1) unlink every year, if any
# 2) unlink a particular student if it's there
# 3) keep students

match
$teaching ($all:$id) isa teaching;

{$id isa person, has id '1'; $all type teaching:student;}
 or
{$id isa year; $roles type teaching:year;};

delete
#option c) 
$teaching (teacher: $id);
$teaching (year: $id);

#option d)
$teaching (teacher: $id, year: $id);
```
## problem with c)
gets `The relation variable '$teaching' has multiple 'relation' constraints`
 
## problem with d)
gets `Invalid Thing Write: Could not delete roleplayer 'person' as relation 'teaching:year' does not relate it`

## Suggestion
- Enable a way to couple roletypes with iids `($roleType:$ids)` in order to be able to use them in deletes 
- if a set of $id become to multiple types, it is indeed impossible to asign them on a LINK (add) operation. However is completely possible to do it in UNLINK (delete) queries.

## Expected
```
delete
$teacher (teacher: $id, year: $id);
```
Should work if $id is a Union of some teacher and year iiids

**Comment by lveillard** [comment]
This is my try e)
```
match
$teaching (student: $students) isa teaching, has id 't';
$teaching2 (year: $year) isa teaching, has id 't';

delete
$teaching (student: $students);
$teaching2 (year: $year);
```

Not even this simple mutation works, i get the error
`Could not delete roleplayer 'year' as relation 'teaching:year' does not relate it.`

If i remove the line `$teaching (student: $students);` suddenly teaching:year does relate 'year' 🤔

**Comment by flyingsilverfin** [comment]
I assume we can implement just `delete $r ($roletype: $player)` to solve this issue?

**Comment by lveillard** [comment]
> I assume we can implement just `delete $r ($roletype: $player)` to solve this issue?

That would make me save at least 1 month of development. I would pay for it lol, already lost 5 to 6 days just to try to hack it

As long as:
- its smart enough to work in the case of an iid being shared in several roles and being unlinked only on those that are in the disjunction of types
- the unlink passes even if not every role has already linked stuff

**Comment by flyingsilverfin** [comment]
To implement all the points outlined here, we would:
allow `$type` variables in the `insert` or `delete` clauses of the query.
Allow deletes to be idempotent, ie. if they already occurred they are a no-op rather than throw an exception
