### ISSUE TITLE
TypeDB 3.0: Dependent attributes (auto-clean up)

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6766]
## Problem to Solve

In some data models, attributes are indendent domains that can be made to exist without any connections or ownerships - eg. inserting all valid names in Iceland! However, in some domains values only make sense when coupled with owners. 

This problem is the same as the specific feature request at: https://github.com/vaticle/typedb/issues/6389

## Current Workaround

Manually clean up orphaned attributes periodically or after data writes.

## Proposed Solution

We will introduce an annotation on attribute types, such as `@dependent`, which means that the attribute will be deleted if there are no owners of the attribute. This annotation will be done in the schema, per attribute type. The default will continue with attributes as non-dependent, which will allow them to exist independently.

**Comment by lveillard** [comment]
This is great!
I have the feeling that in 90% of use cases attributes make sense only when coupled with at least one thing. 

So I would propose to use the key for those cases that seem rarer and keep the autocleaning as a defaul behaviour. In the same case that linking a thing to an attibute is automatic if the attribute is already existing. 

So something like @keepOnLastUnlink might be more intuitive and clean than having >90% of schemas with @dependent tags on every attribute.

**Comment by maydanw** [comment]
Few thoughts:
1. Another possible naming can be @private, @shared and @global (as in classes the attribute is private to the specific entity or shared across the class type or just global). The implementation can be broken to @private and @global in the first phase and the split the global if there are requests in the future.
1. I would have voted for adding the @global keyword as in my use cases almost always the attributes are private by default.

**Comment by lveillard** [comment]
> Few thoughts:
> 
> 1. Another possible naming can be @Private, @shared and @global (as in classes the attribute is private to the specific entity or shared across the class type or just global). The implementation can be broken to @Private and @global in the first phase and the split the global if there are requests in the future.
> 2. I would have voted for adding the @global keyword as in my use cases almost always the attributes are private by default.

As a quick workaround, for private properties, we just name them as `{thingName}·{attributeName}` for instance `name` is global and `author·name` is private`

Not perfect but it helps to have things well structured.

**Comment by flyingsilverfin** [comment]
Closing in favor of https://github.com/vaticle/typedb/issues/7022! You guys will be happy with the conclusion ;)

**Comment by maydanw** [comment]
If I understood correctly then attributes are dependent unless stated
otherwise. Dependent attributes will be garbage collected automatically
