### ISSUE TITLE
How to define an entity type which can be a subtype of itself?

### ISSUE THREAD

**Issue by HzZbSH** [vaticle/typedb#6845]
## Problem to Solve

I found no way to define an entity type which can be a subtype of itself. It means i must create a redundant relation like:
```
define
    subBrand sub relation,
        relates parent_brand,
        relates child_brand;
    Brand sub entity,
        plays subBrand:parent_brand,
        plays subBrand:child_brand,
```
Is there any way to make the definition more elegant?

**Comment by SullivanDaly** [comment]
What you have currently is a great way to represent your data.

![Screenshot 2023-07-10 at 10 53 26](https://github.com/vaticle/typedb/assets/28625122/4af9d5ac-afea-4022-af37-b5c3436aafd8)

This structure let you create some brands with a nested parent/child structure.

If you want to have only one single level (a child can't be a parent), you may want to subtype your Brand entity with a ParentBrand and ChildBrand where they are playing their respective role in subBrand.

But even in this case, I would recommand your original design unless you have some specific usages for the two subtypes (specific roleplayer, or specific ownership for one of the two).
