### ISSUE TITLE
Extend configuration parser features

### ISSUE THREAD

**Issue by krishnangovindraj** [vaticle/typedb#6889]
## Problem to Solve
We currently have workarounds for certain cases in configuration parsing, which should be worked into the YAMLParser:
- switches for branches (Instead of enable flag per switch and validation logic for exactly-one being enabled)
- Optional fields
- Enums
- Lists of a generic type

## Proposed Solution
Implement these as primitives in YAMLParser.

### Use cases
1. We'd like the keystore path to be optional. This would be a lot easier if we had an Optional<T> parser
```
Path keyStorePath = yaml.asMap().containsKey(KeyStore.path.key()) ?
        KeyStore.path.parse(yaml.asMap(), path) :
        null;
```

**Comment by flyingsilverfin** [comment]
We've introduce optionals in #6913 and set a convention for blocks of optional entries versus leaf optional values
