### ISSUE TITLE
Could we use Chinese or other 'utf-8' characters as the variable names?

### ISSUE THREAD

**Issue by yiouyou** [vaticle/typedb#6899]
## Problem to Solve

Use Chinese characters as the variable names, since it's more readable in application and more mantenable in development.

## Current Workaround

No good solusion yet. Like the Python supports any utf-8 as the variable names, I suggest that TypeDB should do this as well.

## Proposed Solution

No idea. Probably, learn from Python.

## Additional Information

I'm considering use LLM to query TypeDB, if TypeDB supports utf-8 variable names, then no translation between them.

**Comment by flyingsilverfin** [comment]
Hi there - did you get to test this out in Console and Drivers? Is it only Studio that has this limitation?

**Comment by flyingsilverfin** [comment]
Implemented in https://github.com/vaticle/typedb/pull/6969
