### ISSUE TITLE
Multi role replacement bugs in 2.22

### ISSUE THREAD

**Issue by lveillard** [vaticle/typedb#6901]
[directLF (1).zip](https://github.com/vaticle/typedb/files/12672609/directLF.1.zip)
As the schema is a bit complex and i was not able to simplify and reproduce the error, i'm just sharing it here 👆 (schema + data)

# Bug one 

- Deletions of multiple roles at once do work as expected, this do work in the new 2.22 version:
```bash
match 
$a($role:$player);
$player has id $pid; $a has id $rid;
$u1 isa Unit, has id "person1";
$k2 isa Kind, has id "Book";
{$role type Unit:kinds;} or {$role type Attribute:kinds;};

delete
$a($role:$player);
```

however, if we transform it into a replace (reverting the previous deletion)
```bash
match 
$a($role:$player);
$player has id $pid; $a has id $rid;
$u1 isa Unit, has id "person1";
$k2 isa Kind, has id "Book";
{$role type Unit:kinds;} or {$role type Attribute:kinds;};

delete
$a($role:$player);


insert
$u1 (kinds: $k2);
```

This throws an error "Concept does not exist"
![image](https://github.com/vaticle/typedb/assets/29461076/7e205091-8ea8-484a-b573-d7b42b3a9490)

# Bug 2 
With the same schema and data (revert or reinitiate the data from the .zip file) there is an extrange issue when querying things that sub other things:

```bash
match 
$a($role:$player);
{$role type Value:unit;};
```

This should match some of the things in the data, but it does not

Same result:
```bash
match 
$a ($role: $player) isa Value;
$role type Value:unit
```
![image](https://github.com/vaticle/typedb/assets/29461076/2eb12b52-0459-41eb-8eb0-0c2e18b918e0)

if we get the roles, they are there
![image](https://github.com/vaticle/typedb/assets/29461076/aec9147f-d6c6-4515-9b6b-c5e6616f405b)

As a fun fact, for some reason, this works:
```bash
match 
$a ($role: $player) isa Value;
$role type Value:role; #role instead of the role name
```
(maybe is a third bug?)

I think it might be related to the fact that these players are relations and not entities.

**Comment by krishnangovindraj** [comment]
Minimised bug1:
```typeql
### schema
define
id sub attribute, value string;
rel sub relation, relates rol, plays rel:rol, owns id;
ent sub entity, owns id, plays rel:rol;

### data
insert 
$e1 isa ent, has id "e1";
$e2 isa ent, has id "e2";
$r (rol: $e1, rol: $e2) isa rel;

# query
match 
$r (rol: $e);
delete 
$r (rol: $e);
insert 
$e isa ent, has id "got-deleted";  # Insert anything to return results
```
The bug is that we return `$r`, which would since have been deleted since all its role players would have been deleted. This should be fixed when we address #6920  (planned for the next release)
Strictly, the bug isn't in the update query, but in a supplementary query that both studio & console do to fetch the role-players of `$r` when displaying the result.

(Will look at bug 2 next)

**Comment by lveillard** [comment]
hello! Did you reproduced the second bug? I think is related to extended relations

**Comment by krishnangovindraj** [comment]
Hi @lveillard ,
Yes, see: #6925 . It was a bug in how we traverse nested relations when the role is a variable.

**Comment by lveillard** [comment]
Sorry for not being doing a reduced version of the bug and thanks for the great job 💪

There is another open issue related to the other bug so feel free to close this issue

**Comment by flyingsilverfin** [comment]
Closing then :)
