### ISSUE TITLE
Broken repo for grakn

### ISSUE THREAD

**Issue by krish-yadav23** [vaticle/typedb#6907]
## Broken maven repo (https://repo.grakn.ai/repository/maven/) 

{ I am experimenting with typedb and i need to dump some data from csv files. I am running  latest typedb server from docker as mentioned on typedb website 

`docker pull vaticle/typedb:latest `

I followed  [Grakn.ai medium article](https://towardsdatascience.com/introducing-grami-a-data-migration-tool-for-grakn-d4051582f867)

However, when i try to resolve the maven in my Intellij project i am getting error:
Could not transfer artifact io.grakn.client:grakn-client:pom:1.8.3 from/to grakn.ai (https://repo.grakn.ai/repository/maven/): No such host is known (repo.grakn.ai)

Later i found out that the repo itself is not working. Is this repo shifted or something?

}

## Environment

1. OS (where TypeDB server runs): { Windows 11}
2. TypeDB version (and platform): { e.g. TypeDB 2.21.1 on docker}

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Use java code from the medium article and open it in intellij }
2. { Load maven decencies as mentioned in article inside pom.xml file}
3. { Reload all maven projects. This step will load all the dependencies from the mentioned repo }
4. { Error: Could not transfer artifact io.grakn.client:grakn-client:pom:1.8.3 from/to grakn.ai (https://repo.grakn.ai/repository/maven/): No such host is known (repo.grakn.ai)
 }

## Expected Output

{ Able to dump data from csv to typedb }

## Actual Output

{Error: Could not transfer artifact io.grakn.client:grakn-client:pom:1.8.3 from/to grakn.ai (https://repo.grakn.ai/repository/maven/): No such host is known (repo.grakn.ai)
 }

**Comment by krishnangovindraj** [comment]
The version you are using is extremely outdated, so the url of the repository has changed.
The artifact should still available at `https://repo.vaticle.com/repository/maven/`

**Comment by krishnangovindraj** [comment]
Closing this. Please, re-open if needed.

**Comment by krish-yadav23** [comment]
This still doesn't resolve my issue.

I am running typedb server in dcoker container.
2023-10-03 21:41:07 01:41:07.804 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - version: 2.21.1


`<repositories>
        <repository>
            <id>repo.vaticle.com</id>
            <url>https://repo.vaticle.com/repository/maven/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>com.vaticle.typedb</groupId>
            <artifactId>typedb-client</artifactId>
            <version>2.18.0</version>
        </dependency>
    </dependencies>`

This is the java code:
`package org.example;

import cli.LoadOptions;
import loader.TypeDBLoader;

public class LoadingData {

    public void loadData() {
        String uri = "localhost:1729";
        String config = "dataConfig.json";
        String database = "databaseName";

        String[] args = {
                "load",
                "-tdb", uri,
                "-c", config,
                "-db", database,
                "-cm"
        };

        LoadOptions options = LoadOptions.parse(args);
        TypeDBLoader loader = new TypeDBLoader(options);
        loader.load();
    }
}
`

Not able to resolve the LoadOptions and TypeDBLoader objects in this java code.

**Comment by jamesreprise** [comment]
Ensure that the osi-maven repository is also added:
```
<repository>
    <id>typedb</id>
    <url>https://repo.vaticle.com/repository/osi-maven/</url>
</repository>
```
and that you've declared the loader dependency:
```
<dependency>
    <groupId>com.vaticle.typedb-osi</groupId>
    <artifactId>typedb-loader</artifactId>
    <version>1.2.0</version>
</dependency>
```
    
See the full instructions: https://github.com/typedb-osi/typedb-loader/wiki/09-TypeDB-Loader-as-Dependency

**Comment by krish-yadav23** [comment]
I used same pom.xml as described in the instructions provided by you;

<repositories>
        <repository>
            <id>typedb</id>
            <url>https://repo.vaticle.com/repository/maven/</url>
        </repository>
        <repository>
            <id>typedb</id>
            <url>https://repo.vaticle.com/repository/osi-maven/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.vaticle.typedb-osi</groupId>
            <artifactId>typedb-loader</artifactId>
            <version>1.2.0</version>
        </dependency>
    </dependencies>


Still the same issue.

**Comment by jamesreprise** [comment]
From your code:
```java
package org.example;
import cli.LoadOptions;
import loader.TypeDBLoader;
```
I think these import paths are not specific enough. Can you try importing these by a full-er path, i.e. `com.vaticle.typedb.osi.loader.cli.LoadOptions`? Likewise for the Loader itself, something like `com.vaticle.typedb.osi.loader.loader.TypeDBLoader`.

**Comment by krish-yadav23** [comment]
# pom.xml

`


<?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
    
        <groupId>org.example</groupId>
        <artifactId>datamigration</artifactId>
        <version>1.0-SNAPSHOT</version>
    
        <properties>
            <maven.compiler.source>20</maven.compiler.source>
            <maven.compiler.target>20</maven.compiler.target>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        </properties>
    
        <repositories>
            <repository>
                <id>repo.vaticle.com</id>
                <url>https://repo.vaticle.com/repository/maven/</url>
            </repository>
    
            <repository>
                <id>typedb</id>
                <url>https://repo.vaticle.com/repository/osi-maven/</url>
            </repository>
    
        </repositories>
        <dependencies>
            <dependency>
                <groupId>com.vaticle.typedb</groupId>
                <artifactId>typedb-client</artifactId>
                <version>2.18.0</version>
            </dependency>
    
            <dependency>
                <groupId>com.vaticle.typedb-osi</groupId>
                <artifactId>typedb-loader</artifactId>
                <version>1.2.0</version>
            </dependency>
    
        </dependencies>
    
    </project>
`


# Java code:

`package org.example;

import com.vaticle.typedb.osi.loader.cli.LoadOptions;
import com.vaticle.typedb.osi.loader.loader.TypeDBLoader;

public class LoadingData {

    public void loadData() {
        String uri = "localhost:1729";
        String config = "dataConfig.json";
        String database = "databaseName";

        String[] args = {
                "load",
                "-tdb", uri,
                "-c", config,
                "-db", database,
                "-cm"
        };

        LoadOptions options = LoadOptions.parse(args);
        TypeDBLoader loader = new TypeDBLoader(options);
        loader.load();
    }
}
`

# Error

Cannot resolve symbol 'osi'
Cannot resolve symbol 'LoadOptions'
Cannot resolve symbol 'TypeDBLoader'

**Comment by krish-yadav23** [comment]
[krishnangovindraj](https://github.com/krishnangovindraj) This issue isn't resolved, can you please help ?

**Comment by krishnangovindraj** [comment]
@krish-yadav23 Could you try version `1.7.0` for typebd-loader please?
That seems to work on mine.

**Comment by krish-yadav23** [comment]
Thank you, i was able to proceed. However, i am now facing below issue while dumping data from csv file.

`Inside Loading data11:37:20.488 [main] INFO  com.vaticle.typedb.osi.loader.loader - validating your config...
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.vaticle.typedb.osi.loader.config.Configuration$GlobalConfig.getSchema()" because the return value of "com.vaticle.typedb.osi.loader.config.Configuration.getGlobalConfig()" is null
	at com.vaticle.typedb.osi.loader.config.ConfigurationValidation.validateSchemaPresent(ConfigurationValidation.java:287)
	at com.vaticle.typedb.osi.loader.loader.TypeDBLoader.load(TypeDBLoader.java:52)
	at org.example.LoadingData.loadData(LoadingData.java:21)
	at org.example.Main.main(Main.java:9)
`

**Comment by krishnangovindraj** [comment]
I think the config file structure may have changed to include the data.
Please refer to the wiki for typedb-loader: https://github.com/typedb-osi/typedb-loader/wiki/01-Global-Configuration

**Comment by krish-yadav23** [comment]
Okay, i tried that and now facing issue saying file  not found.


```
{
   "globalConfig":{
      "separator":",",
      "rowsPerCommit":50,
      "parallelisation":4,
      "schema":"src/test/resources/eduSchema.gql"
   },
   "entities":{
      "Instructor":{
         "data":[
            "src/test/resources/entity_instructor.csv",
         ],
         "config":{
            "separator":",",
            "rowsPerCommit":50
         },
         "insert":{
            "entity":"Instructor",
            "ownerships":[
               {
                  "attribute":"id",
                  "generator":"id",
                  "required":false
               },
               {
                  "attribute":"email",
                  "generator":"email",
                  "required":false
               },
               {
                  "attribute":"firstname",
                  "generator":"firstname",
                  "required":false
               },
               {
                  "attribute":"lastname",
                  "generator":"lastname",
                  "required":false
               }
            ]
         }
      }
   }
}
```

Error:

``` 
14:30:36.835 [main] INFO  com.vaticle.typedb.osi.loader.loader - validating your config...
14:30:37.276 [main] WARN  com.vaticle.typedb.osi.loader.loader - defaultConfig.parallelisation is not set - defaults to number of processors on machine * 8
14:30:37.276 [main] ERROR com.vaticle.typedb.osi.loader.loader - entities.Instructor.data: <null>: file not found
'''

Folder Structer:

![image](https://github.com/vaticle/typedb/assets/23015889/f31e4808-4d27-41a2-9a80-f95974871d78)

**Comment by krish-yadav23** [comment]
I was able to dump data in typedb after making changes to the config file.

```
{
   "globalConfig":{
      "separator":",",
      "rowsPerCommit":50,
      "parallelisation":4,
      "schema":"src/test/resources/eduSchema.gql"
   },
   "entities":{
      "Instructor":{
         "data":[
            "src/test/resources/entity_instructor.csv"
         ],
         "config":{
            "separator":",",
            "rowsPerCommit":50
         },
         "insert":{
            "entity":"Instructor",
            "ownerships":[
               {
                  "attribute":"id",
                  "column":"id",
                  "required":false
               },
               {
                  "attribute":"email",
                  "column":"email",
                  "required":false
               },
               {
                  "attribute":"firstname",
                  "column":"firstname",
                  "required":false
               },
               {
                  "attribute":"lastname",
                  "column":"lastname",
                  "required":false
               }
            ]
         }
      }
   }
}
```

Thank you [krishnangovindraj](https://github.com/krishnangovindraj), [jamesreprise](https://github.com/jamesreprise) for your help.
