### ISSUE TITLE
Can't get the number of an unknown enum value 

### ISSUE THREAD

**Issue by lveillard** [vaticle/typedb#6928]
## Description

Typedb thrwoing java error on TypeDB.coreClient(url)

## Environment

Fly.io with ubuntu, last version of typedb 2.24.17

## Reproducible Steps

Steps to create the smallest reproducible scenario:
- I created a vm in fly.io. It was working in older versions
```
[build]
  image = "vaticle/typedb:latest"
```
- I call from node the typeDB.coreClient
- This throws that java error:

![image](https://github.com/vaticle/typedb/assets/29461076/6a72fac1-b22d-4223-8f7d-672b14be9726)
`ERROR com.vaticle.typedb.core.server.TypeDBService -- Can't get the number of an unknown enum value.`
 java.lang.IllegalArgumentException:

**Comment by flyingsilverfin** [comment]
This is actually a bad error indicating that the protocol version mismatches. This will be fixed in 2.25.0 to be a useful error message. Closing since this is expected to be resolved, please reopen if 2.25.0 still has the issue

**Comment by lveillard** [comment]
Oh thanks! That explains it

**Comment by lveillard** [comment]
I guess for node we will need to wait as well for 2.25? 
It is still in 2.18.2 and is the one that triggers the issue with the latest version of typedb
